### PR TITLE
Dev/rofa/docs search

### PR DESCRIPTION
**Pull request by rfabre**
## PR Type

- Update to the implementation of Algolia Search box in Docs
- Add sitemap.xml to Docs (to be used by Algolia Search crawler)

## What is the current behavior?

- Algolia Search box is not displayed every time we load a documentation page
- No sitemap for docs

## What is the new behavior?

- Algolia Search box is displayed every time we load a documentation page
- A sitemap for docs is created by docfx

### <samp>🤖 Generated by Copilot at 5e85436</samp>

This pull request improves the documentation site by adding a sitemap file, fixing the docsearch feature, and minifying the main script. These changes enhance the SEO, usability, and performance of the documentation pages.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):
(https://dev.azure.com/nventive/UNO%20Marketing/_workitems/edit/272655)

### CODE REVIEW

**Review by agneszitte — COMMENTED** [review]
Is this normal that we are removing these files including docfx.js @rfabre ? (cc @jeromelaban)
image

**Comment by rfabre** [comment]
> Is this normal that we are removing these files including docfx.js @rfabre ? (cc @jeromelaban) image

The files are not removed, they are minified.

**Review by agneszitte — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
@mergifyio backport legacy/4x

**Comment by jeromelaban** [comment]
@Mergifyio backport release/stable/4.9

**Pull request merged**
