### PR TITLE
app: Fix ListView missing top elements when flinging #11809

### LINKED ISSUE #11809: ListView Virtualization can cause items to be hidden forever if scrolling too rapidly on WASM
### Current behavior

1. Bind a items source of a list view to an observation collection with 200 items.
2. Launch the app, observe the first item's binding.
3. Drag scrollbar to scroll to the bottom of the list. Then scroll back up.
4. Observe the first item in the list isn't the one observed at (2).

### Expected behavior

At (4), the first item is the one observed at (2).

### How to reproduce it (as minimally and precisely as possible)

Minimal repro:
https://github.com/roxk/UnoVirtualizationWasmBug

Video:
https://user-images.githubusercontent.com/16918354/227860838-022f44aa-9d09-43c7-975e-15e7ce27afda.mp4

### Workaround

Disable virtualization by using `StackPanel` as the `ItemsPanel`. But our app currently faces severe performance issues due to this workaround.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

```
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="4.8.15" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="4.8.15" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.8.15" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.11" />
```

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.5.3

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by roxk**
GitHub Issue (If applicable): closes #11809

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?
ListView would miss the top most 1st or 2nd items when scrolling from the bottom to the top quickly (in `VirtualizingPanelLayout`'s term, `isLargeScroll == true`).

## What is the new behavior?
ListView correct layouts the 1st item after scrolling from bottom to top quickly.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
I don't mind contributing a UI Test as well if it's not too hard/time-consuming. Having pointers to existing list view tests would be ideal.

Internal Issue (If applicable):
N/A

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for your contribution! 

THe PR is only missing a [runtime test for regression validation](https://platform.uno/docs/articles/uno-development/creating-runtime-tests.html), which should be somehow similar to this one (but only should be using `ContainerFromItem` to determine if the container for the first item is actually displayed:

https://github.com/unoplatform/uno/blob/98eff14058cc95ba4063e1313b2e935e0a7a1504/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs#L837-L874

**Comment by roxk** [comment]
Ok. Lemme add a test for that. Thanks for the pointer.

**Comment by roxk** [comment]
@jeromelaban I'm stuck at not having a way to grab the UI element's position relative to its parent since `ActualOffset` is not implemented. What's the recommended way to check whehter the container is visible? Note that the previous bug did create the element, it's just pushed off screen (`ActualOffset.Y` is negative relative to parent), so merely checking whether the item is created isn't enough.

**Comment by jeromelaban** [comment]
@roxk indeed, OffsetX and OffsetY are not implemented, but LayoutSlot is available and gives the right information. I've taken a look at your PR during my live stream today, if you want to check out what was needed to do it: https://www.youtube.com/watch?v=x5wCqc5_Yec

Thanks very much for working on this!

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
Thanks again for your contribution!

**Comment by roxk** [comment]
@jeromelaban That's awesome, thanks! Tested latest dev `4.9.dev-372` package and can confirm the issue is fixed. Any chance this can be back ported to 4.8? Or, is there any planned release date for 4.9?

**Pull request merged**
