### PR TITLE
feat: implement CoreWindows.Bounds

### LINKED ISSUE #7630: Implement Windows.UI.Core.CoreWindow.Bounds
## Why is this needed:
SyncFusion TimePicker places the popup on a location to present the time editor
## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly

### PR DESCRIPTION
**Pull request by iury-kc**
GitHub Issue (If applicable): closes #7630
 
## PR Type

What kind of change does this PR introduce?

- Feature 

## What is the current behavior?

CoreWindow Bounds property wasn't implemented.

## What is the new behavior?

Implemented like Windows Bounds property.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by iury-kc** [comment]
@jeromelaban 
How would be a way to test CoreWindow class in macOS and iOS ?

My UserControl test compares  this.Window.Current.Bounds and this.Window.Current.CoreWindow.Bounds to make sure CoreWndow.Bounds works. 


However, macOS and iOS have Windows classes instead UI.XAML.Window class. 

I think there's a better way to do that. But I couldn't figure out for now.

**Comment by jeromelaban** [comment]
The class `CoreWindow` should be available, what's not working here? Is it the type that is missing, something else?

**Comment by iury-kc** [comment]
On the UserControl for UI test:

`var wb = Window.Current.Bounds;`
`var SUT = Window.Current.CoreWindow.Bounds;`

Window is recognized as native. NSWindow for Apple, for instance. And the native window doen't have CoreWindow.

------------------

I'm trying a new approach:

We can instanciate a var w = Windows.UI.Xaml.Window();  and then change manually its bounds to see w.Current.CoreWindow.Bounds changing. 
Maybe even changing it to a Unit Test, instead UI.

However, in my humble opinion, it seams a weak test, as we are not testing the real behavior of an App.

**Comment by iury-kc** [comment]
Trying a new approach, unit tests instead ui as it was not passing.

**Review by jeromelaban — APPROVED** [review]
Very good! Thanks for your contribution!

**Pull request merged**
