### PR TITLE
chore: gitignore mergedstyles.xaml

### LINKED ISSUE #14318: Discuss whether mergedstyles.xaml should be git-ignored
This specific file is somewhat annoying for version control. I'm not sure if it should be git-ignored?

@MartinZikmund @jeromelaban ?

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #14318

## PR Type

What kind of change does this PR introduce?

## Copilot Summary

copilot:summary

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
A change like this will likely cause issues on opening the solution for the first time on a clean repo. We should be moving this file to obj, if possible.

**Comment by Youssef1313** [comment]
> A change like this will likely cause issues on opening the solution for the first time on a clean repo. We should be moving this file to obj, if possible.

I'll try building after a `git clean -xdf` to see if those issues are still there. I assumed it will be fine if passed CI.

**Comment by jeromelaban** [comment]
@Youssef1313 I recall issues in VS, specifically (but not precisely enough to tell you what...), not necessarily in CI.

**Comment by MartinZikmund** [comment]
We could maybe try to merge this and if problems arise make a workaround - e.g. some CI validation that checks whether the `mergedstyles.xaml` contain uncommitted changes after build and fail CI in such case?

**Comment by jeromelaban** [comment]
@Youssef1313 can you rebase, let's try and see if issues arises as @MartinZikmund suggested.

**Pull request merged**
