### PR TITLE
fix: Svg not loading

### PR DESCRIPTION
**Pull request by ajpinedam**
GitHub Issue (If applicable): closes #

related to #https://github.com/unoplatform/uno/issues/14465

## PR Type

What kind of change does this PR introduce?

- Bugfix
- 
## What is the current behavior?
SVG is no loading

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 81d709b</samp>

Fix SVG element arrangement bug in `SvgCanvas`. Refactor `ArrangeOverride` method to use a helper method `ArrangeFirstChild` in `SvgCanvas.cs`.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by ajpinedam** [comment]
@jeromelaban can you please attach the issue for the SVG to this PR? I could not find it in my assigned issues.

**Comment by morning4coffe-dev** [comment]
@ajpinedam Great! I think you mean this issue, right? https://github.com/unoplatform/uno/issues/11676

**Comment by jeromelaban** [comment]
Let's not fix this way, see https://github.com/unoplatform/uno/pull/14540/files#r1404327216

**Comment by ajpinedam** [comment]
Closing this PR. 

Fix in https://github.com/unoplatform/uno/pull/14540 will also fix the SVG issue.

**Pull request closed without merging**
