### PR TITLE
refactor: Removed app.manifest from Skia samples/templates apps.

### PR DESCRIPTION
**Pull request by HavenDV**
GitHub Issue (If applicable): closes #

According discussion: https://github.com/unoplatform/uno/discussions/9166

## PR Type

What kind of change does this PR introduce?

## What is the current behavior?

The templates and the example app contain an app.manifest with default content. For Skia applications, its removal has no effect (this includes file and registry virtualization for backwards compatibility, which should be taken into account). It's worth noting that the manifest file is required for WinUI applications because it has a significant effect on how it looks on high resolution screens.

## What is the new behavior?

They are removed

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
I am not sure about this - when I was adjusting DPI awareness support for GTK on Windows and WPF, the `dpiAwareness` was needed. Not sure if this changed somehow since then, but I would not remove these yet until we bring back DPI support on GTK renderers and verify it properly for both GTK and WPF

**Comment by HavenDV** [comment]
Yes, this is a controversial PR. I tested deleting the manifest on Windows 11 so the behavior may be different for other systems. Also, testing was just for visual differences (which are noticeable to the eye for WinUI, for example), so I might be missing something.

**Comment by jeromelaban** [comment]
It looks like there are some small conflicts based on related changes.

**Comment by jeromelaban** [comment]
Looks like there's still a missing ap.manifest file :)

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\VSSDK\Microsoft.VsSDK.targets(1447,5): Error VSSDK1016: Failed to create the zipfile "obj\Release\CSharp\Uno Platform\1033\UnoApp.zip". Could not find file 'C:\a\1\s\src\SolutionTemplate\UnoSolutionTemplate\Skia.Gtk\app.manifest'.
```

**Comment by HavenDV** [comment]
I'm still unsure about these changes due to @MartinZikmund's comment, so I think it's worth waiting for confirmation from him anyway. If there is any doubt, you can just close this PR

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
Looks like we're still using the manifest in the GTK app:

`CSC : error CS1926: Error opening Win32 manifest file D:\a\1\s\src\SamplesApp\SamplesApp.Skia.Gtk\app.manifest -- Could not find file 'D:\a\1\s\src\SamplesApp\SamplesApp.Skia.Gtk\app.manifest'`

**Pull request merged**
