### PR TITLE
fix: Fix CalendarDatePicker day item corner

### LINKED ISSUE #15177: [Gallery][WASM]CalendarDatePicker(Material, Cupertino)-When clicking on the calendar for the first time, the background for the date, month, and year is displayed as a square
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/8ffe4927-6009-46b9-ab54-d491db565beb

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/cbd3971c-210a-4c39-b020-ccc19fd09018

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click "CalendarDatePicker" from the "UI Components" list.
3.  Go to 'Material' section.
4. Click on 'Select a Date' option.
5. Notice that the background is showing as square for the last displays dates on the calendar.
6. Put cursor on those dates.
7. Notice that the background now changing as circle.

### Workaround

_No response_

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

WebAssembly

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #15177

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Can you add a screenshot of what this PR is fixing?

**Comment by Youssef1313** [comment]
@jeromelaban I forgot to link the issue, that's for https://github.com/unoplatform/uno/issues/15177 which has the video of current behavior.

Still not sure if this fixes it. I'll validate and also see if I can write a runtime test.

**Review by MartinZikmund — APPROVED** [review]

**Comment by MartinZikmund** [comment]
Oh that's some extreme web-based runtime test 😁😁😁😁

**Comment by MartinZikmund** [comment]
@mergifyio backport release/stable/5.1

**Pull request merged**
