### PR TITLE
fix: BindingExpression will now apply the FallbackValue when a Converter returns DependencyProperty.UnsetValue

### LINKED ISSUE #4458: Converter returning DependencyProperty.UnsetValue causes exception
## Current behavior

Throws exception.

## Expected behavior

Property value should result in the fallback value.

## How to reproduce it (as minimally and precisely as possible)

Create and use a converter from a binding that returns DependencyProperty.UnsetValue.

## Workaround

Have the converter return a known or specified via property on the converter, a specified fallback value.  This requires changing all converters though, which is not ideal.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

### PR DESCRIPTION
**Pull request by alove-kahua**
GitHub Issue (If applicable): Closes #4458

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?

When using a Converter that returns DependencyProperty.UnsetValue, the BindingExpression will currently throw an exception, output to the log, then apply the FallbackValue.

## What is the new behavior?

The BindingExpression will apply the FallbackValue without throwing the exception which helps performance as well as not outputting errors to the log.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [X] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

No unit test can be written, since the outcome is the same aside from the internal exception and log output.

Internal Issue (If applicable):

### CODE REVIEW

**Review by davidjohnoliver — APPROVED** [review]

**Comment by jeromelaban** [comment]
I'll take a look at adding a unit test

**Comment by jeromelaban** [comment]
@alove-kahua here's a test you can add to your PR: https://github.com/jeromelaban/uno/commit/fae76c554e8d07f0fcefce6ee2a3fbd45fecdad1

**Comment by jeromelaban** [comment]
@alove-kahua regarding https://github.com/jeromelaban/uno/commit/fae76c554e8d07f0fcefce6ee2a3fbd45fecdad1#commitcomment-44088548

Without your change, the second assertion fails because the MyProperty value is `Windows.UI.Xaml.UnsetValue` where it should be the fallback value of the binding.

**Comment by jeromelaban** [comment]
@alove-kahua If you allow me to update your branch, I can merge this change.

**Review by carldebilly — APPROVED** [review]

**Pull request merged**
