### PR TITLE
Removing invalid this for Storyboard.SetTarget

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): #1767 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

SourceGenerator generates a `this` keyword for `Storyboard.SetTarget`, which is invalid as it is generated within a `static` class.

## What is the new behavior?

The `this` keyword is no longer generated.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by davidjohnoliver** [comment]
Thanks Martin! 

Can you add a test for this? When it just needs to be a binary builds/fails-to-build test, all you need to do is add the relevant Xaml to the XamlGenerationTests project (which is verified to build by the CI):
https://github.com/unoplatform/uno/tree/master/src/SourceGenerators/XamlGenerationTests

**Comment by MartinZikmund** [comment]
> Thanks Martin!
> 
> Can you add a test for this? When it just needs to be a binary builds/fails-to-build test, all you need to do is add the relevant Xaml to the XamlGenerationTests project (which is verified to build by the CI):
> https://github.com/unoplatform/uno/tree/master/src/SourceGenerators/XamlGenerationTests
> 
> >  GitHub**[unoplatform/uno](https://github.com/unoplatform/uno)**Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - unoplatform/uno

Done :-)

**Comment by jeromelaban** [comment]
Thanks @MartinZikmund !

Could you also add a validation in https://github.com/unoplatform/uno/tree/master/src/SourceGenerators/XamlGenerationTests ?

**Comment by MartinZikmund** [comment]
@jeromelaban it is there already - https://github.com/unoplatform/uno/blob/154fa5c33467844b5350e545664072422726dca6/src/SourceGenerators/XamlGenerationTests/StoryboardTargetTest.xaml

**Comment by jeromelaban** [comment]
Right missed it ;) Sorry.

**Pull request merged**
