### PR TITLE
refactor: Untabified and removed unnecessary white spaces from templates

### PR DESCRIPTION
**Pull request by xperiandri**
## PR Type

What kind of change does this PR introduce?
- Refactoring (no functional changes, no api changes)

Please check if your PR fulfills the following requirements:

- [X] Contains **NO** breaking changes
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by jeromelaban** [comment]
The PR looks good, but could you rebase to latest to resolve the conflicts ?

**Comment by xperiandri** [comment]
@jeromelaban  done

**Review by carldebilly — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
