### PR TITLE
fix!: Change default NotImplementedLogLevel to Debug instead of Error

### LINKED ISSUE #17025: Mute all not implemented messages and add Warnings in XAML for not implemented types uses
### What would you like to be added

All messages showing in the console that come from uno are generally not actionable, even though the uno packages-provided templates make use of not implemented features in XAML.

We should mute those messages down to debug level, and add a XAML generator set of warnings when explicit uses of not implemented types.

### Why is this needed

Make warnings actionable.

### For which platform

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #17025

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.3

**Review by agneszitte — APPROVED** [review]

**Review by carldebilly — APPROVED** [review]

**Pull request merged**
