### PR TITLE
feat: Contact support struct/enums

### PR DESCRIPTION
**Pull request by pkar70**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
Contacts are not supported at all.

## What is the new behavior?
Basic structs (enums, classes) are supported.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
Non-controversial part of #2544; all enums and classes that are common to all platforms.

Internal Issue (If applicable): #3045

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]
@pkar70 Made a small refactor - changed the ContactQuerySearchField backing type to `unit`, so we can use 4294967295 directly. When we merge this, please rebase the Android contacts PR on this. I will be implementing contacts on iOS, so we will get the Android PR merged too 👍

**Comment by pkar70** [comment]
Yes, I will rebase #2544 after merging this.
As my "big" PRs are still waiting, I intend to split them into smaller parts, and rebase "parent" PRs.

If you have time, maybe you could help with #2079 (CalendarDatePicker). I don't know what was previous implementation of Uno.DatePicker for iOS, maybe it also looks like UWP CalendarDatePicker?

**Comment by pkar70** [comment]
Does your change cause current build failure? I'm not sure what means "Removed field System.Int32 Windows.ApplicationModel.Contacts.ContactQuerySearchFields::value__ not found in ignore set."

**Comment by MartinZikmund** [comment]
> Yes, I will rebase #2544 after merging this.
> As my "big" PRs are still waiting, I intend to split them into smaller parts, and rebase "parent" PRs.
> 
> If you have time, maybe you could help with #2079 (CalendarDatePicker). I don't know what was previous implementation of Uno.DatePicker for iOS, maybe it also looks like UWP CalendarDatePicker?

Not sure about the `DatePicker`. Will check it out 👍

**Comment by MartinZikmund** [comment]
image

It was really a `uint` 😀

**Review by davidjohnoliver — APPROVED** [review]

**Pull request merged**
