### PR TITLE
feat: Single project support for windows packaging

### LINKED ISSUE #7556: Update WinUI3 + .NET 6 Template to use Preview MSIX Tooling
## What would you like to be added:
The latest and greatest tooling from WinUI3 uses the preview MSIX tooling to combine the windows project head and the packaging project into one. In Uno Platform assuming your app is called `App1` this would be the `App1.Windows.Desktop` and `App1.Windows.Packaging` projects.

We should update the dotnet template to combine these when using the `dotnet new` command
```
dotnet new unoapp-winui-net6 -n App1
```

## Why is this needed:
Following the WinUI3 project template will simplify our templates and make it easier for developers to use Uno Platform if they are coming directly from WinUI3 projects

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [x] Solution Templates

## Anything else we need to know?
I'm willing to contribute the change

### PR DESCRIPTION
**Pull request by ahoefling**
GitHub Issue (If applicable): closes #7556 

## PR Type

What kind of change does this PR introduce?

- Feature
- Other - dotnet new template change for `unoapp-winui-net6`

## What is the current behavior?
When creating a new Uno Platform App using the dotnet cli with `dotnet new unoapp-winui-net6` it creates 2 projects for the windows target.
* `MyApp.Windows.Desktop`
* `MyApp.Windows.Packaging`

## What is the new behavior?
When creating a new Uno Platform App using the dotnet cli with `dotnet new unoapp-winui-net6` it *now* creates 1 project for the windows target.
* `MyApp.Windows`

When I was comparing the differences between the WinUI3 templates and the Uno Platform WinUI3/NET6 templates I noticed that WinUI3 is using preview MSIX tooling which combines the Desktop and Packaging projects. As this appears to be the direction the tooling is going in, it will be a good idea for us to adopt the same.

Below is a screenshot of a Test App generated using the template compiled locally
image

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
This pull request only contains changes for the winui-net6 dotnet template. I am more than happy to update this PR to make the other templates follow this technique.

Internal Issue (If applicable):
n/a

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for the PR! We'll need to modify the sln file as well, so the project is actually referenced. I'm also pushing an update so we can validate that the winui actually builds, now that some issue has been fixed in WinUI.

**Comment by jeromelaban** [comment]
Ah well, github.dev does not let me commit on your branch, but it's about uncommenting this line: 

https://github.com/unoplatform/uno/blob/571ce99d1e85924654d50be0f916888eb672954e/build/run-net6-template-tests.ps1#L68

**Comment by ahoefling** [comment]
I uncommented the line and changed it to `Windows` as this proposal changes the project name from `Windows.Desktop` to `Windows`. I made this change to simplify the verbiage since there will only be 1 windows project and not 2.

Do we want to include this change on all other templates? I can see benefit of leaving the other templates alone as winui3/net6 is latest and greatest and the other templates may be used from older versions of Visual Studio.

**Comment by ahoefling** [comment]
Fixed issues with commit messages and rebased this PR on the latest changes from master

**Comment by jeromelaban** [comment]
The build failed
```
C:\Users\VssAdministrator\.nuget\packages\microsoft.windows.sdk.buildtools\10.0.22000.196\build\Microsoft.Windows.SDK.BuildTools.props(4,37): error MSB4185: The function "Is64BitProcess" on type "System.Environment" is not available for execution as an MSBuild property function. [D:\a\1\s\UnoAppWinUI\UnoAppWinUI.Windows\UnoAppWinUI.Windows.csproj]
```
and it looks like we're hitting https://github.com/microsoft/WindowsAppSDK/issues/1652.

This should do:
image

**Comment by ahoefling** [comment]
Thanks for the advice on updating the ps1 script. I just pushed changes let's see if that fixes the build

**Comment by jeromelaban** [comment]
Looks like we need to alter the net6 testing agents, I'll take a look.

**Comment by jeromelaban** [comment]
Looks like we have a winner :) Some more manual testing for the template output needs to be done, but it's looking good!

**Comment by jeromelaban** [comment]
The generated template does not work properly, VS does not find the proper project for "packaged" and fails for a missing `Microsoft.XAML.dll` on the other side. I wonder if 2022 Preview 2 will this...

**Review by jeromelaban — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
