### PR TITLE
feat: Handling layout of native control in a `RelativePanel`

### LINKED ISSUE #9381: `RelativePanel` does not handle native views properly
### Current behavior

When native controls are inside of a `RelativePanel` they are not measured and arranged properly.

### Expected behavior

Should be arranged properly.

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

_No response_

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #9381

## PR Type

What kind of change does this PR introduce?

- Bugfix
- Feature

## What is the current behavior?

Not layouting native views.

## What is the new behavior?

Layouting native views.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by jeromelaban** [comment]
https://github.com/unoplatform/uno/issues/9381#issuecomment-1201671460

**Comment by MartinZikmund** [comment]
@jeromelaban as discussed under the issue, should I close this? Technically this should have no effect unless the native view is explicitly added as a direct child, but if it should never happen, I can undo the native view related code and keep just the cleanup of commented out code

**Comment by jeromelaban** [comment]
It looks like we're using these APIs through the native underlying APIs, something that should not be possible cross platform anyways. Was it possible with the previous `RelativePanel` implementation?

**Comment by MartinZikmund** [comment]
@jeromelaban I think it did based on the fact that the code was using the `MeasureElement` and `ArrangeElement` methods for measure & arrange - 
https://github.com/unoplatform/uno/blob/12fb3ffe80ab3e7a05344be51b155ee309e115e6/src/Uno.UI/UI/Xaml/Controls/RelativePanel/RelativePanel.Layout.cs#L26

**Comment by jeromelaban** [comment]
Ok then. Let's add it anyways, though it'll be important to add an android runtime test to validate for regressions.

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
