### PR TITLE
fix(vsix): Don't close opened files when reloading the project

### PR DESCRIPTION
**Pull request by jeromelaban**
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17029

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the new behavior?

When the active project is reloaded to adjust the first TFM, this change avoids closing opened files that are related to that project.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by dansiegel — APPROVED** [review]

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.3

**Review by agneszitte — APPROVED** [review]

**Comment by agneszitte** [comment]
@jeromelaban impossible to backport this change to 5.2 also?

**Comment by jeromelaban** [comment]
@agneszitte it needs testing first.

**Comment by agneszitte** [comment]
@Darsh0307 Could you please help test the following scenario?

1. Open some project files in Visual Studio (both with and without changes, and regardless of whether you've launched the app for a specific platform).
2. Change the **TargetFramework** to test another platform.

If the fixes from @jeromelaban worked properly, the previously opened files should remain open. If the issue persists, you will see the files disappear from the opened tabs in Visual Studio.

Thank you in advance for your help!

**Comment by Darsh0307** [comment]
JFYI 
https://github.com/unoplatform/private/issues/454

**Pull request merged**
