### PR TITLE
docs: fix using-uno-check file name

### PR DESCRIPTION
**Pull request by kojo12228**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

Linux specific documentation for `uno-check` doesn't display correctly, due to space in file name:

image

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by Youssef1313 — APPROVED** [review]
LGTM

**Comment by jeromelaban** [comment]
Good catch! Thanks for your contribution!

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/4.7

**Comment by kojo12228** [comment]
Happy to contribute, thanks for the quick review and merge!

**Pull request merged**
