### PR TITLE
fix: Fix shapes clipping on Android

### LINKED ISSUE #13652: Samples app icons on Android are getting clipped
### Current behavior

image

### Expected behavior

_No response_

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #13652 (reverts one of the changes in https://github.com/unoplatform/uno/pull/13359)

## PR Type

What kind of change does this PR introduce?

### <samp>🤖 Generated by Copilot at 2e82903</samp>

Refactor and fix code style in `Shape.layout.legacy.cs`. Improve stroke thickness and alignment logic for shapes.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by ajpinedam — APPROVED** [review]

**Review by carldebilly — APPROVED** [review]

**Review by dr1rrb — APPROVED** [review]
Please add a link to the PR that is "rollback" by this

**Comment by Youssef1313** [comment]
Merging this to fix the regression. @jeromelaban It was very hard to write a runtime test for this. The RenderTargetBitmap shows the shape unclipped, while it actually renders clipped. So couldn't test this.

**Pull request merged**
