### PR TITLE
build: Copy WinAppSDK fix

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]
I'm surprised that this never worked, still if it helps, let's do it. We may need to add a regression test as well.

**Comment by jeromelaban** [comment]
@Youssef1313 do we still need this one?

**Comment by Youssef1313** [comment]
@jeromelaban We may. I'll need to work on a template test, making sure it fails before the changes and passes after.

**Comment by Youssef1313** [comment]
> I'm surprised that this never worked, still if it helps, let's do it. We may need to add a regression test as well.

We cannot add a regression test in this PR, it will need to be a follow-up after a new version is released because we will need an app that reference a library with a different version.

**Comment by Youssef1313** [comment]
@Mergifyio backport release/stable/5.1

**Comment by Youssef1313** [comment]
@Mergifyio backport release/stable/5.2

**Comment by Youssef1313** [comment]
@Mergifyio backport release/stable/5.3

**Pull request merged**
