### PR TITLE
fix(skia): SKImageInfo.PlatformColorType is incorrect on macOS/arm64

### LINKED ISSUE #8580: Red and blue channels are inverted with Skia.Gtk on M1-based Macs
### Current behavior

When using Skia.Gtk on a M1-based Mac computer the red and blue channels are inverted.

Note: I have not tried this on other platforms. It might not be limited to M1/arm64 based macs.

Screen Shot 2022-04-20 at 2 49 32 PM

In the above image the orange UI elements should be blue.

### Expected behavior

The expected colours should be seen.

### How to reproduce it (as minimally and precisely as possible)

Build and run SampleApps.Sika.Gtk.csproj on a M1 Mac.

### Workaround

It seems `SKImageInfo.PlatformColorType` is returning `Rgba8888`, as documented. However it does not seems to reflect what's required.

Hardcoding this to `SKColorType.Bgra8888` _solves_ the problem.

### Works on UWP/WinUI

_No response_

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

git revision 919cd95b5a21c1390b705fb5d53519ed1a3bfa49
and SkiaSharp 2.88.0-preview.254 for macOS/arm64 support

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

# Requires SkiaSharp 2.88+

The current stable Uno (4.1.9) does not ship a working libSkiaSharp version (2.80.3) for arm64 macs.

In order to have an arm64 slice in the native library a newer, pre-release version of SkiaSharp, 2.88.x, must be used.

See https://github.com/unoplatform/uno/issues/8296 for more details.

# Diff

The following change _fix_ the issue - at least on M1-based macs, but it might break it elsewhere. I'm not _yet_ sure if this is a know issue in Skia[Sharp] / m88 bug wrt `SKImageInfo.PlatformColorType`.

```diff
diff --git a/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs b/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
index 385442c3a..04dea8a3d 100644
--- a/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
+++ b/src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
@@ -75,12 +75,13 @@ namespace Uno.UI.Runtime.Skia
                        var scaledWidth = (int)(width * _dpi.Value);
                        var scaledHeight = (int)(height * _dpi.Value);

-                       var info = new SKImageInfo(scaledWidth, scaledHeight, SKImageInfo.PlatformColorType, SKAlphaType.Premul);
+                       SKColorType platform = SKColorType.Bgra8888;
+                       var info = new SKImageInfo(scaledWidth, scaledHeight, platform, SKAlphaType.Premul);

                        // reset the bitmap if the size has changed
                        if (bitmap == null || info.Width != bitmap.Width || info.Height != bitmap.Height)
                        {
-                               bitmap = new SKBitmap(scaledWidth, scaledHeight, SKColorType.Rgba8888, SKAlphaType.Premul);
+                               bitmap = new SKBitmap(scaledWidth, scaledHeight, platform, SKAlphaType.Premul);
                        }

                        using (var surface = SKSurface.Create(info, bitmap.GetPixels(out _)))
```

### PR DESCRIPTION
**Pull request by spouliot**
- Detect macOS + arm64 and reset default `SKColorType` to `Bgra8888`
- Create the `SKBitmap` using the `SKImageInfo` instance

Addresses #8580

GitHub Issue (If applicable): closes #8580

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

When using Skia.Gtk on a M1-based Mac computer the red and blue channels are inverted.

## What is the new behavior?

`SKColorType.Bgra8888` is used in the software renderer `RenderSurfaceType.Software` for macOS/arm64.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]
Thanks for your contribution!

**Comment by spouliot** [comment]
@jeromelaban I don't think the PR could be related to the failures. Can you re-run it again ? thanks!

**Pull request merged**
