### PR TITLE
ci: Add macOS desktop runtime tests

### PR DESCRIPTION
**Pull request by jeromelaban**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by spouliot** [comment]
```
❌ (F) Check_FontFallback_Shaping()
EXCEPTION>Images have different resolutions. 
expected:(98,34)
actual  :(97,34)
The actual image is not the same as the expected one.
actual RSMD: 0.1720096541053666
threshold: 0.15
```

Looks like a minor difference, where the bitmap's width is smaller, by a pixel, than expected. That test is already ignored for X11.

## screenshot1.png
screenshot1

## screenshot2.png
screenshot2

I think we should bump the threshold to `0.18` to cover the difference. Also we can remove the separate width/height checks since the `ImageAssert.AreSimilarAsync` already does it.

The alternative would be to ignore the test for macOS (like X11) but without testing it we run into the risk of larger regressions.

@Youssef1313 ?

**Comment by spouliot** [comment]
```
❌ (F) When_Large_List_Scroll_To_End_Then_Back_Up_TryClick()
EXCEPTION>Assert.Fail failed. ImageAssert.HasColorAt @ line 1991
====================
Color at (70,65) is not expected
expected: FF1A69A6 #FF1A69A6
actual  : FF1A6AA7 #FF1A6AA7
tolerance : 0
difference: 1
screenshot size: 100x500
```

Also looks like a minor difference and pass if the `tolerance` is set to `1`.

@Youssef1313 ? @ramezgerges ?

## Screenshot

screenshot3

**Comment by spouliot** [comment]
The other failures all seems to be keyboard related, mostly because the shortcuts between [macOS](https://support.apple.com/en-ca/102650) and [Windows](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec#textediting) are different by design.

I'll be fixing them in upcoming commits...

**Comment by ramezgerges** [comment]
> ```
> ❌ (F) When_Large_List_Scroll_To_End_Then_Back_Up_TryClick()
> EXCEPTION>Assert.Fail failed. ImageAssert.HasColorAt @ line 1991
> ====================
> Color at (70,65) is not expected
> expected: FF1A69A6 #FF1A69A6
> actual  : FF1A6AA7 #FF1A6AA7
> tolerance : 0
> difference: 1
> screenshot size: 100x500
> ```
> 
> Also looks like a minor difference and pass if the `tolerance` is set to `1`.
> 
> @Youssef1313 ? @ramezgerges ?

This is a bit weird, why would it be different between platforms (unless there's a bug in the metal backend in skia)? I would try testing this with skiasharp 3 and see if that fixes things. SK3 already fixes a bunch of linux-specific bugs. Anyway, I guess adding a tolence of 1 when __MACOS__ is fine.

**Comment by Youssef1313** [comment]
For Check_FontFallback_Shaping, the one pixel difference is a bug that is acceptable currently. Space widths can differ from font to another, and we may use wrong font to determine space width in some cases.

**Pull request merged**
