### PR TITLE
docs: Update VSCode getting started docs dotnet requirements

### PR DESCRIPTION
**Pull request by johnthepro**
Modify the text to clarify requirements

GitHub Issue (If applicable): N/A

## PR Type

docs: Update getting started docs dotnet requirements

## What is the current behavior?

Unintentionally vague requirements

## What is the new behavior?

Clarifies the need for both .NET SDK versions to be installed.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for your contribution! 

Would you mind changing the commit text to be `docs: Update getting started docs dotnet requirements` so that it fits Conventional Commits?

**Comment by johnthepro** [comment]
Oh jeez! I think I did it right!

**Comment by johnthepro** [comment]
Okay NOW I think I did it right. :)

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
Almost! It's the commit itself that needs to be changed, no the PR title. There's no GitHub web way to do that yet...

**Review by carldebilly — APPROVED** [review]

**Pull request merged**
