### PR TITLE
fix(resourcedictionary): Fix Source path not registered correctly

### PR DESCRIPTION
**Pull request by davidjohnoliver**
If the shared project Import was placed after the Xamarin.iOS.CSharp.targets import, the AssignLinkMetadata task was not setting the Link metadata for shared project items correctly, causing confusion and consternation. This ensures the task will always be run. (XF does the same: https://github.com/xamarin/Xamarin.Forms/commit/bf86534eafcef76988032bc422a6c1d35b65ffd2)

GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

- Bugfix

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

fixes https://github.com/unoplatform/nventive-private/issues/47

### CODE REVIEW

**Review by Xiaoy312 — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
@davidjohnoliver This change definitely causes some additional issues: ` System.InvalidOperationException: Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml'`, on iOS.

**Comment by jeromelaban** [comment]
@mergifyio backport release/beta/3.1

**Pull request merged**
