### PR TITLE
Fix for UWPSyncGenerator issues, aligning generated files

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): #1275 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

Dependency properties are not correctly generated.

Also generated files differ from what the tool generates currently, so there is always a lot of changes even when user makes small change.

## What is the new behavior?

Generator bugs fixed, generated files aligned with latest generated code from the tool.

After running `UWPSyncGenerator` in this PR, tool should make 0 changes.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
@jeromelaban when reviewing, especially check the last commit - **Aligning remaining generated files** as this contains the files which were "weird", for example those which had `false` in some random `#if` directives around `[NotImplemented]` or those which had removed methods, which apparently are still not implemented on some platforms

**Comment by jeromelaban** [comment]
@MartinZikmund constructors have a somehow weird behavior, because most of those are autogenerated by the C# compiler. We most probably need to add a case for that, given that we now validate for API changes.

**Comment by MartinZikmund** [comment]
@jeromelaban Hm, seems this didn't go well at all:

```

src\Uno.UWP\UI\Core\CoreDispatcher.net.cs(19,15): Error CS0111: Type 'CoreDispatcher' already defines a member called 'ProcessEvents' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(46,34): Error CS0111: Type 'ApplicationData' already defines a member called 'SetVersionAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(58,34): Error CS0111: Type 'ApplicationData' already defines a member called 'ClearAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(46,34): Error CS0111: Type 'ApplicationData' already defines a member called 'SetVersionAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(58,34): Error CS0111: Type 'ApplicationData' already defines a member called 'ClearAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(46,34): Error CS0111: Type 'ApplicationData' already defines a member called 'SetVersionAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(58,34): Error CS0111: Type 'ApplicationData' already defines a member called 'ClearAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(46,34): Error CS0111: Type 'ApplicationData' already defines a member called 'SetVersionAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(58,34): Error CS0111: Type 'ApplicationData' already defines a member called 'ClearAsync' with the same parameter types

src\Uno.UWP\Storage\ApplicationData.cs(46,34): Error CS0111: Type 'ApplicationData' already defines a member called 'SetVersionAsync' with the same parameter types
```

I don't understand why these specifically got generated by the tool incorrectly. For example `CoreDispatcher.net.cs` definitely declares this memeber

**Pull request closed without merging**
