### PR TITLE
feat: DualScreen support for multiple device models

### LINKED ISSUE #6507: [DualScreen] Update implementation to use Window Manager
## What would you like to be added:

Support for the newer Dual Screen set of APIs, through https://www.nuget.org/packages/Xamarin.AndroidX.Window/

## For which Platform:

Android

## Anything else we need to know?

The current implementation for dual screen support is located here: 

https://github.com/unoplatform/uno/blob/d57d8ed572184968a801dda815ac30bba96122cc/src/Uno.UI.DualScreen/DuoApplicationViewSpanningRect.cs#L14

It is currently using https://www.nuget.org/packages/Xamarin.DuoSdk, and should be migrated.

### PR DESCRIPTION
**Pull request by conceptdev**
GitHub Issue (If applicable): closes #6507

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

Uno.UI.DualScreen uses a Microsoft-provided library **DisplayMask** which is provided by **Xamarin.DuoSDK** NuGet. This provides an API that is used by the `TwoPaneView` control to intelligently adapt to the screen layout on Surface Duo devices (only).

## What is the new behavior?

Added a new dependency on **Xamarin.AndroidX.Window.WindowJava** which provides a binding to Google's Jetpack Window Manager library. This provides dual-screen/foldable support for Surface Duo devices AND other Android devices that have folding screens and support the Window Manager API. 

`TwoPaneView` should automatically pick up the new device support via the existing `IApplicationViewSpanningRects` interface, however a new interface `INativeFoldableProvider` has been added to expose additional properties to application code. The new inteface exposes some features as `bool` that might be better modeled as new `enum` - pending feedback.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

The PR as it currently stands will have a **breaking change**, since the way the new API is wired up (in _MainActivity.cs_) is different to the current behavior. In the issue #6507 I noted that perhaps this feature should be added in an entirely new project (eg. Uno.UI.Foldable) so that the existing behavior can be kept backwards-compatible.

I decided against adding a new project or modifying anything too drastically without feedback on this plan.

TODO: I also suspect there's a 'first load' issue where the `TwoPaneView` isn't the root view of the application but gets loaded after the app is already spanned. TBC, related to how this API is event driven versus the old API which could on-demand check the screen telemetry.

## Other information

A prototype for this feature is available at:
https://github.com/conceptdev/uno-samples/tree/main/WindowManager

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
> Should I close and re-do the PR with updated commit labels? I missed the Conventional instructions 😬
Just a simple interactive rebase with rewording will do!

For Edge, that's good to know! We'll likely be able to integrate that to match the other APIs. This also means that `INativeFoldableProvider` cannot be mapped to edge APIs, correct?

**Comment by conceptdev** [comment]
I think with just the rects info, Edge can only fully implement `IApplicationViewSpanningRects`. With some math you could calculate `isSeparating` `IsVertical` based on hinge width and dimensions. `TwoPaneView` currently only needs `IApplicationViewSpanningRects`.

There are other web-standards in development that could provide the hinge posture to support `IsFlat`, but Edge/web does not support the hinge sensor currently, so you couldn't fully implement `INativeFoldableProvider` until then. Defaulting to `IsFlat` would probably be a safe choice...

**Comment by jeromelaban** [comment]
It seems that net6 is having some trouble when adding the `Xamarin.AndroidX.Window.WindowJava` package, as it generates some kind of double AndroidManifest.xml file.

**Comment by jeromelaban** [comment]
It's working properly in the samples app, net6 build included.

**Comment by conceptdev** [comment]
Updated PR with new logging infrastructure - TwoPaneView seems to behave again 😃

uno-twopaneview

When the CI build is green I'll finish off refactoring out the `INativeFoldableProvider` (as discussed, for possible future inclusion) and we should be good to go 🤞

**Comment by conceptdev** [comment]
**Status update** - just tidied up the public API (as discussed) to keep it the same as before. Will investigate adding more Jetpack Window Manager features in a future PR, but for now those elements are deleted or `private` if they're needed in the code.

**Still to do** - clean up the logging and either delete my debugging logs or where appropriate use the proper Uno logging pattern

**Question** - I had to remove `DependsOnTargets="SignAndroidPackage"` from the **Samples.Droid.csproj** after updating to VS2022 so that has been checked in; but not sure if it's causing CI issues so will probably need to add it back, and better understand why it's actually causing my local builds to fail.

**SamplesApp on 7.6" foldable**
image

**Comment by jeromelaban** [comment]
> **Still to do** - clean up the logging and either delete my debugging logs or where appropriate use the proper Uno logging pattern

Uno's logging would be appropriate indeed, particularly now that it's adjusted to be linker friendly :)

> **Question** - I had to remove `DependsOnTargets="SignAndroidPackage"` from the **Samples.Droid.csproj** after updating to VS2022 so that has been checked in; but not sure if it's causing CI issues so will probably need to add it back, and better understand why it's actually causing my local builds to fail.

I'm still trying to get around the change in VS2022, I'll merge a fix soon.

**Review by jeromelaban — APPROVED** [review]

**Comment by conceptdev** [comment]
Just resolved latest merge conflicts and removed 'wip' 

I'm not 100% sure the `DependsOnTargets="SignAndroidPackage"` is resolved but otherwise the code seemed to be working last time I tested it!

**Comment by jeromelaban** [comment]
Thanks @conceptdev! The `SignAndroidPackage` package has been addressed in a separate PR, so we're good! Thanks a lot for your work !

**Pull request merged**
