### PR TITLE
ToggleSwitch.Header visibility

### PR DESCRIPTION
**Pull request by pkar70**
GitHub Issue (If applicable): #3437

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?
ToggleSwitch.Header is not visible.

## What is the new behavior?
ToggleSwitch.Header is visible.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [X] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thank you for your contribution. Is the visibility set this way in the original UWP template? If not, the visibility is most likely changed by the control's code.

**Comment by pkar70** [comment]
I don't know how it is in "original UWP template", but I know that this works on Android :)
Maybe it should be made visible somewhere in the code, not in template; maybe it is quick and dirty workaround... But it works with ToggleButton created in .cs code, and with ToggleButton defined in XAML.

**Comment by jeromelaban** [comment]
After digging a little bit, the `HeaderContentPresenter` is kept collapsed to benefit from the `x:Load` feature. To enable the control, you'll need to add a test that validates that either the `Header` or `HeaderTemplate` property is set and change the visibility accordingly.

**Comment by pkar70** [comment]
HeaderContentPresenter  is the only element in row 0 of ToggleSwitch, and height of this row is set to Auto. So, if no Header is set, then height = 0, and visibility=hidden is not necessary... my way is just simpler, and within my abilities :)
I don't know why Header works in other (at least, some other) controls, and doesn't work for ToggleSwitch.

**Comment by jeromelaban** [comment]
`x:Load` is removing the element from the visual tree, so keeping it Collapsed is important.

**Comment by pkar70** [comment]
Ok, where should be added "test that validates that either the Header or HeaderTemplate property is set and change the visibility accordingly", and why it actually works for e.g. TextBox or Slider, and not work for ToggleSwitch?

**Comment by jeromelaban** [comment]
The other controls may not have the appropriate property management, because we did not know about that `x:Load` behavior. So yes, a test that validates that it's possible to set the header here is appropriate.

**Comment by pkar70** [comment]
But WHERE such test should be? I can copy such test from TextBox, as it has correct Header handling, but I don't know where it is coded. Which file (or which class)? Maybe it is somewhere deep hidden in .tt files?

**Comment by jeromelaban** [comment]
There is no test that validates that behavior for the other controls at this point. Create a new one that validates that behavior.

**Comment by pkar70** [comment]
What is difference (and where) between Slider and ToggleSwitch? Both have (in generic.xaml) defined Grid, with first (0) row with Height=Auto, and HeaderContentPresenter with Visibility="Collapsed" in this row. But some code (I didn't find where this is in code) properly sets visibility in Slider, and Header is displayed, and such code is missing from ToggleSwitch.

**Comment by jeromelaban** [comment]
As I mentioned, the original template has an `x:Load` defined, this is the reason it's done this way.

**Comment by pkar70** [comment]
Resolved by another way in #3494

**Pull request closed without merging**
