### PR TITLE
feature: implement all InputScopeNameValue

### PR DESCRIPTION
**Pull request by ghuntley**
## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

- partial enum implementation
- enum values not implemented

## What is the new behavior?

- full implementation with documentation

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

See https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.inputscopenamevalue

### CODE REVIEW

**Comment by ghuntley** [comment]
@carldebilly, sure! What do you think about the following approach:

1. find all references for the enum
2. ignore any enum values have have a consumer (ie "supported")
3. for any enum value that don't have a consumer add `[Uno.NotImplemented]`

**Comment by davidjohnoliver** [comment]
As Carl said, all the new values need be marked `NotImplemented` because they're not actually consumed anywhere. 

If you want to try to actually implement them, the `InputScopeHelper.[platform]` class is what tries to map to native equivalent for Android/iOS. As far as I can see we don't yet implement `InputScope` at all for WASM.

**Pull request merged**
