### PR TITLE
fix(DependencyObjectGenerator): Handle nested classes properly

### LINKED ISSUE #9612: `GenerateNestingContainers` puts classes in wrong order
### Current behavior

For `DependencyPropertyGenerator` and `DependencyObjectGenerator`, the implementation of `GenerateNestingContainers` is incorrect.

Code like this:

image

generates incorrect code:

image

### Expected behavior

Order is of nesting is preserved.

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

_No response_

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #9612

- Simplified the use of `AddToIndentedStringBuilder` helper
- Extended `AddToIndentedStringBuilder` to support appending a base list after the class header.

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]
Is there an external generation test we can add ? (a secondary validation to the unit tests)

**Review by MartinZikmund — APPROVED** [review]

**Comment by Youssef1313** [comment]
@jeromelaban Sorry for the delay. I added a test for DependencyObjectGenerator specifically.

The test asserts both the generated code and that it has no errors. In case want to skip the generated code check and only assert there is no errors, let me know.

**Comment by jeromelaban** [comment]
Thanks, that's a good additional test, but I was thinking more of [one here](https://github.com/unoplatform/uno/tree/master/src/SourceGenerators/XamlGenerationTests).

**Comment by Youssef1313** [comment]
@jeromelaban Is there anything extra the https://github.com/unoplatform/uno/tree/master/src/SourceGenerators/XamlGenerationTests will provide?

**Comment by jeromelaban** [comment]
It will validate the generation in the "full" generation context, something the unit tests don't have.

**Review by jeromelaban — APPROVED** [review]

**Comment by Youssef1313** [comment]
> It will validate the generation in the "full" generation context, something the unit tests don't have.

I'll get to that soon.

**Pull request merged**
