### PR TITLE
Refactor sync gen

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #

🚧 Builds on #6866 🚧  Don't review until the other PR is merged.

Intention was to improve performance, but apparently the improvements I made aren't really noticeable/measurable.

## PR Type

What kind of change does this PR introduce?

- Refactoring (no functional changes, no api changes)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Youssef1313** [comment]
Fixed conflicts and rebased on latest master.

@jeromelaban @MartinZikmund I prefer someone to run the generator locally to make sure this PR doesn't break anything. I can't currently due to problems when restoring NuGet packages for Uno solution.

It might be a good idea to consider having a CI task for running sync generator and making sure the sources doesn't change after running it.

**Comment by jeromelaban** [comment]
Which problems do you have with restoring your solution?

**Comment by Youssef1313** [comment]
@jeromelaban 

image

My connection is a bit slower now, and it seems NuGet has no way to increase the timeout.

**Comment by jeromelaban** [comment]
@Youssef1313 have you tried restoring with the command line and use `--disable-parallel` ? Or maybe use the nuget.exe if the parameter is not available.

**Comment by jeromelaban** [comment]
I wonder, if you could get some local http proxy that even if still fails after the first try in, it could still populate so that subsequent tries would succeed.

**Comment by Youssef1313** [comment]
@jeromelaban The restore in VS got resolved after multiple tries. But the main thing that resolved most packages is `--disable-parallel`. Thanks for that @jeromelaban

I'll look into the failures here and see what I can do.

**Comment by Youssef1313** [comment]
@jeromelaban Now I'm seeing this :(

```
7>C:\Users\PC\Desktop\uno\src\Uno.UI.RemoteControl.VS\Uno.UI.RemoteControl.VS.csproj : error MSB4057: The target "GetCopyToPublishDirectoryItems" does not exist in the project.
7>Done building project "Uno.UI.RemoteControl.VS.csproj" -- FAILED.
7>C:\Users\PC\Desktop\uno\src\Uno.UI.RemoteControl.Host\Uno.UI.RemoteControl.Host.csproj : error MSB4057: The target "GetCopyToPublishDirectoryItems" does not exist in the project.
7>Done building project "Uno.UI.RemoteControl.Host.csproj" -- FAILED.
```

**Pull request closed without merging**
