### PR TITLE
fix(documentation): summary tag now default to display as list item

### LINKED ISSUE #13322: Docs HTML details and summary disclosure - expander absent
## On which page?
This is a general issue in the docs, the disclosure `details` and `summary` elements are styled in such way that the collapse arrow is invisible.

For example:

```md

<details>
  <summary>Long comment (collapsed for brevity)</summary>

  Lorem ipsum dolor sit amet
</details>
```

Output:

<details>
  <summary>Long comment (collapsed for brevity)</summary>

  Lorem ipsum dolor sit amet
</details>

## What's wrong?

The docs' css includes an override which sets `display: block` for these elements, and the expand/collapse arrow isn't present.

It seems that the website is using https://github.com/necolas/normalize.css which overrides the `summary` element.

The source of the issue is here:
https://github.com/unoplatform/uno/blob/master/doc/templates/uno/vendor/docfx.vendor.css#L13

## Additional info

While investigating the issue, I realized that the rest of the styles and stuff in the templates folder are really outdated compared to the new versions in docfx's source (https://github.com/dotnet/docfx/blob/main/templates/pdf.default/styles/docfx.vendor.css).

### PR DESCRIPTION
**Pull request by alextrepa**
GitHub Issue (If applicable): closes #13322 

## PR Type

What kind of change does this PR introduce?
- Bugfix
- Documentation content changes

## What is the current behavior?

Summary tags do not show the arrow because they are displayed as block.

## What is the new behavior?

Summary tags are now back to being displayed as list items.

### <samp>🤖 Generated by Copilot at 8c3f1f6</samp>

This pull request improves the docfx project by simplifying the build script, removing unused dependencies, fixing a CSS bug, reformatting the CSS and JS files, and adding source map comments to the output files. These changes enhance the readability, maintainability, debuggability, and consistency of the documentation website and its source code.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] ~Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)~
- [ ] ~[Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~
- [ ] ~Validated PR `Screenshots Compare Test Run` results.~
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

This should be a temporary fix. We are using an older version of docfx. The templates we use also uses bootstrap 3.4. All version of bootstrap before version 4 had normalize.css as a dependency. This causes the related issue. We are dicussing about updating these dependencies but in the mean time, this fix should do.

It also adds the js and css maps. They will help fix those issues.

### CODE REVIEW

**Comment by sasakrsmanovic** [comment]
Need @weitzhandler to confirm this is fixing the styling he had in mind.

**Review by ajpinedam — APPROVED** [review]
Change looks good. 

I am surprised the package-lock.json file had been ignored for so long.

**Comment by weitzhandler** [comment]
> Need @weitzhandler to confirm this is fixing the styling he had in mind.

Please verify the expander is displayed in the docs pages and is not overtaken by any overriding CSSs.

**Comment by alextrepa** [comment]
> > Need @weitzhandler to confirm this is fixing the styling he had in mind.
> 
> @alextrepa Please verify the expander is displayed in the docs pages and is not overtaken by any overriding CSSs.

I've tested it localy using the prod configurations. The main.css file seems to be the last one loaded. This is why I chose to put the changes there.

**Comment by jeromelaban** [comment]
Let's merge and validate in staging

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.0

**Pull request merged**
