### PR TITLE
fix: Cast to FrameworkElement/Window when accessing Loading/Activated to avoid issues when shadowing

### LINKED ISSUE #18020: VisualState value named "Loading" triggers compile error
### Current behavior

using Visual State value named "Loading" in xaml triggers Compile error.

Error Message:
> Operator '+=' cannot be applied to operands of type 'VisualState' and 'lambda expression' [/Users/moonlily/Projects/UnoVisaulStateSample/VisualStateSample/VisualStateSample/VisualStateSample.csproj]

when I commented out part that using "Loading", error has gone. 

Does name "Loading" is reserved word in Uno Platform?

### Expected behavior

Compile successfully when using Visual State value named "Loading" 

### How to reproduce it (as minimally and precisely as possible)

Use Visual State value named "Loading" in xaml like this.

```xaml
  <StackPanel utu:SafeArea.Insets="VisibleBounds"
      Spacing="8"
      HorizontalAlignment="Center"
      VerticalAlignment="Center">
      <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="CustomStates">
            <!-- This makes compile error -->
            <!-- Error Message: Operator '+=' cannot be applied to operands of type 'VisualState' and 'lambda expression'  -->
                <VisualState x:Name="Loading">
                    <VisualState.Setters>
                         <Setter Target="TextLabel.Foreground" Value="Blue"/>
                    </VisualState.Setters>
                </VisualState>
            <!-- end -->
                <VisualState x:Name="Highlighted"> 
                    <VisualState.Setters>
                        <Setter Target="TextLabel.Foreground" Value="Red"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
      </VisualStateManager.VisualStateGroups>

      <TextBlock x:Name="TextLabel" AutomationProperties.AutomationId="HelloTextBlock"
          Text="Hello Uno Platform"
          HorizontalAlignment="Center" />
      <Button Content="Change to Highlighted State"
          Click="Button_Click_Highlighted"
          HorizontalAlignment="Center" />
      <Button Content="Change to Loading State"
          Click="Button_Click_Loading"
          HorizontalAlignment="Center" />
  </StackPanel>
```

or

you could download and run Sample project on this [repo](https://github.com/yeahg-dev/UnoVisaulStateSample)

### Workaround

Change State name "Loading" to "Loading2".
this value has compiled well.

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

Android, iOS

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #18020

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Comment by yeahg-dev** [comment]
@jeromelaban 
If It's not a problem, Could you backport this changes to latest version?

**Comment by MartinZikmund** [comment]
@mergifyio backport release/stable/5.3

**Comment by xperiandri** [comment]
Was it released to 5.3.108? I still experience the error

**Comment by Youssef1313** [comment]
No, it's not available in that version. cc @jeromelaban

**Pull request merged**
