### PR TITLE
fixed missing Xaml IntelliSense on newly created project

### PR DESCRIPTION
**Pull request by XiaotianNetlift**
GitHub Issue (If applicable): #2364

## PR Type
What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?
When you create a new `Cross-Platform App (Uno Platform)` and open the `MainPage.xaml`, there is the Xaml IntelliSense support is missing.

## What is the new behavior?
Xaml IntelliSense should just work.

## PR Checklist

Please check if your PR fulfills the following requirements:
- [x] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [ ] ~~Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)~~
- [ ] ~~[Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
- [ ] ~~[Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.~~
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by agneszitte-nventive** [comment]
Oh yeah ❤️ !!

**Comment by davidjohnoliver** [comment]
I'm curious what the entries you added do?

**Comment by XiaotianNetlift** [comment]
@jeromelaban @davidjohnoliver 

> Specifies whether to create the project and perform parameter replacement in the specified location, or perform parameter replacement in a temporary location and then save the project to the specified location.
> remark: `CreateInPlace` is an optional element. The default value is `true`.
> -- https://docs.microsoft.com/en-us/visualstudio/extensibility/createinplace-visual-studio-templates?view=vs-2019

I found out by comparing with other `.vstemplate` on the Github. Also, despite the remark is not true, it clearly made a difference when you explicitly set it to `true`.

**Comment by XiaotianNetlift** [comment]
> Nice! Same question as @davidjohnoliver , how did you find those properties ?

I found out by comparing with other `.vstemplate` files on the Github. Namely those found within: https://github.com/mono/CocosSharp/tree/master/ProjectTemplates/Templates/StarterTemplates/FormsMobile/Template

**Pull request merged**
