### PR TITLE
Added partial initialization hookup

### PR DESCRIPTION
**Pull request by weitzhandler**
GitHub Issue (If applicable): #1385

## PR Type

Feature

## What is the current behavior?

Adds hookup to UI controls' initialization process

## What is the new behavior?

Adds a partial `OnInitialization` method that's called from all platforms' constructors, to enable a unified initialization hookup.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Comment by davidjohnoliver** [comment]
Have you actually identified a case where you need this? 

Normally the generated constructors are only called by the Xamarin runtime and usually only in scenarios where the object is about to be collected anyway.

**Comment by weitzhandler** [comment]
> Have you actually identified a case where you need this?

Of course.
Constructors I need for DI constructor injection, but the hookup, is so that we have a unified place to perform initialization logic.

Here's a concrete example:

```c#
#if HAS_UNO && __IOS__
[global::Foundation.Register]
#endif
[SuppressMessage("Design", "CA1010:Collections should implement generic interface", Justification = "Deliberate usage")]
public abstract
#if HAS_UNO
      partial
#endif
      class AppReactivePage<TViewModel> :
      ReactiveUI.Uno.ReactivePage<TViewModel>, IViewFor<TViewModel>, IActivatableView
      where TViewModel : class
{

  /// <summary>
  /// Initializes a new instance of the <see cref="AppReactivePage{TViewModel}"/> class.
  /// </summary>
  // needed so the others are optional.
  protected AppReactivePage()
  {
    AttachHandlers();
  }

#if HAS_UNO
#if __ANDROID__
  /// <summary>
  /// Initializes a new instance of the <see cref="ReactivePage{TViewModel}"/> class.
  /// Native constructor, do not use explicitly.
  /// </summary>
  /// <remarks>
  /// Used by the Xamarin Runtime to materialize native
  /// objects that may have been collected in the managed world.
  /// </remarks>
  /// <param name="javaReference">A <see cref="IntPtr"/> containing a Java Native Interface (JNI) object reference.</param>
  /// <param name="transfer">A <see cref="JniHandleOwnership"/> indicating how to handle handle.</param>
  protected AppReactivePage(IntPtr javaReference, Android.Runtime.JniHandleOwnership transfer)
      : base(javaReference, transfer)
  {
    AttachHandlers();
  }
#endif
#if __IOS__
  /// <summary>
  /// Initializes a new instance of the <see cref="ReactivePage{TViewModel}"/> class.
  /// Native constructor, do not use explicitly.
  /// </summary>
  /// <param name="handle">Handle to the native control.</param>
  /// <remarks>
  /// Used by the Xamarin Runtime to materialize native.
  /// objects that may have been collected in the managed world.
  /// </remarks>
  protected AppReactivePage(IntPtr handle)
      : base(handle)
  {
    AttachHandlers();
  }
#endif
#endif

  void AttachHandlers()
  {
    DataContextChanged += (s, e) => OnDataContextChanged(e.NewValue);
    RegisterPropertyChangedCallback(ViewModelProperty, (s, p) => OnViewModelChanged());

    this.WhenActivated(_ => { });
  }

  protected virtual void OnDataContextChanged(object newValue)
  {
    if (ViewModel != newValue)
      ViewModel = newValue as TViewModel;
  }

  protected virtual void OnViewModelChanged()
  {
    if (DataContext != ViewModel)
      DataContext = ViewModel;
  }
}
```

**Comment by weitzhandler** [comment]
I didn't know it's OK to completely ignore them.
So can I just have a single constructor?
I'll try that.

**Comment by jeromelaban** [comment]
> I didn't know it's OK to completely ignore them.
> So can I just have a single constructor?
> I'll try that.

@weitzhandler do you still need those changes ?

**Comment by weitzhandler** [comment]
I don't know. Lemme close the issue for now. Should I encounter any problems and I'll come back. Thanks!

**Pull request closed without merging**
