### PR TITLE
docs: Use Markdown Video tag instead of `iframe`

### PR DESCRIPTION
**Pull request by morning4coffe-dev**
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno-private/issues/453

## PR Type

What kind of change does this PR introduce?

- Refactoring (no functional changes, no api changes)
- Documentation content changes

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by agneszitte** [comment]
@morning4coffe-dev Also be careful here when using **closes** that will automatically close the related issue when this PR is merged. If it is working, we will need to update more than the Uno repo here
cf. https://github.com/search?q=org%3Aunoplatform+src%3D%22https%3A%2F%2Fwww.youtube-nocookie.com%2Fembed%2F&type=code with all the repos where we are using `<iframe />` at the moment

image

**Comment by morning4coffe-dev** [comment]
Thank you @agneszitte, I updated the PR to be a part of. I didn't realize that otherones couln't be part of this PR.

**Comment by morning4coffe-dev** [comment]
Hmm, this is the [result](https://unodocsprstaging.z13.web.core.windows.net/pr-16305/articles/create-an-app-rider.html?tabs=android)of the Markdown Video tag:
image

**Comment by MartinZikmund** [comment]
Is it possible that this would work without the `>` at the beginning?

**Comment by morning4coffe-dev** [comment]
Closing in favor of https://github.com/unoplatform/uno/pull/16972

**Pull request closed without merging**
