### PR TITLE
feat: ToastNotification and NotificationMirroring definitions

### PR DESCRIPTION
**Pull request by pkar70**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
ToastNotification and NotificationMirroring are not defined.

## What is the new behavior?
ToastNotification and NotificationMirroring are defined.
NotificationMirroring- enum
ToastNotification - defined only this fields that are required for Toast to have any sense.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
 Non-controversial part of #2585

Internal Issue (If applicable):

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]
Made a small formatting update here too, approved 👍

**Comment by pkar70** [comment]
I don't understand error messages from CI build, so I cannot do anything wi

**Comment by MartinZikmund** [comment]
@pkar70 seems like a DevOps issue, I have run the task again

**Comment by pkar70** [comment]
Timeout in ListView test... nothing in common with this PR. Please restart build.

**Review by davidjohnoliver — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
