### PR TITLE
internal: Android working permission helper

### PR DESCRIPTION
**Pull request by pkar70**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?
- Bugfix
- Feature
- Refactoring (no functional changes, no api changes)
All of above, and - at same time - none of above :)

## What is the current behavior?
Current implementation of Android permission helper functions doesn't work.
Currently there is no possibility to invoke system dialog asking for permission from Uno code (e.g. from RequestAccessAsync methods).
So, PR#2024 (geolocator) is labelled as 'help needed' (to split code into levels - as was said in Lobby or in some comments), also PR#2544 (contacts), PR#2757 (calllog), and soon-to-be PR (SMS access) cannot be fully implemented (some code have to be included in app code, not inside Uno).

## What is the new behavior?
New helper methods works inside Uno, and can invoke system dialog asking for permission.

## PR Checklist

Please check if your PR fulfills the following requirements:
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
 I made it as separate PR, to be used in all four PRs mentioned above, as code is common (and I don't want contacts-PR be dependend on e.g. geolocator PR). Also, it can be used from other Uno PRs and from user code.

 I don't edit/modify current Android methods in permissionhelper.cs, as they can be somewhere used (structure of these methods are cumbersome, too complicated for me). 

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for your contribution. Can you add ui tests for it so we can validate that it works as it should ?

**Comment by pkar70** [comment]
Which folder should I use for such test?
It is Windows.Extensions.PermissionHelper class, Android only.

**Comment by jeromelaban** [comment]
Use the namespace name, separated by `_` as mentioned here: https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#creating-ui-tests

**Comment by pkar70** [comment]
Could you please specify which folder, and not refer to document that is not related to my question?
E.g.: should test be placed in shared, or in android?

**Comment by jeromelaban** [comment]
The document I'm referring to is related to your question, and you can place it where any other test is located. Use `#if __ANDROID__` to exclude the platform specific code.

**Comment by pkar70** [comment]
After adding test, I got three conflicts - I do know how to resolve AndroidManifest.xml, but doesn't have any clue how to resolve two others.
I tried to 
`git rebase unoplatform/master`
`git rebase -i unoplatform/master`
`git push -f`
but I got
`Current branch PermissionHelper is up to date.`
`Successfully rebased and updated refs/heads/PermissionHelper`
`Everything up-to-date`

**Comment by pkar70** [comment]
Will be reopened

**Pull request closed without merging**
