### PR TITLE
automatically prompt to install missing components

### LINKED ISSUE #1376: Make the .NET Core 2.2 SDK requirement for WebAssembly more obvious
> I had the same exact problem, but in my case the root cause was that the [.NET Core 2.2 SDK](https://dotnet.microsoft.com/download/visual-studio-sdks) wasn't installed. But no helpful errors pointed me to that!

_Originally posted by @andrewleader in https://github.com/unoplatform/uno/issues/983#issuecomment-520531020_

### PR DESCRIPTION
**Pull request by ghuntley**
GitHub Issue (If applicable): fixes #1376

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

When a developer generates a new solution via the wizard WebAssembly (and other heads) will fail to compile if the the pre-requisite Visual Studio for Windows payloads are not installed.

## What is the new behavior?

After the solution is generated, if a developer does not have the right payloads are installed then they will get a super obvious prompt asking them to install the pre-requisite payloads.

image

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information

`.vsconfig` in this pull-request is the same one we used to build `Uno.UI.sln` minus all Visual Studio extension development payloads.

See below for more information about the feature and for payload identifiers:
- https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/
- https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019

### CODE REVIEW

**Comment by ghuntley** [comment]
As the pull-request is now the `.vsconfig` is not being included when generating a new solution. 

Next steps: 
- pull vsix off CI and re-check
- obtain second set of eyes to review vsix changes

**Comment by jeromelaban** [comment]
Adding solution files (or out of solution files, for that matter) can be done through the [Wizard project](https://github.com/unoplatform/uno/blob/08f2bbb2b4c1c0b647e123d624785f1708ffe863/src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs#L38) and add the file there. This project is still referenced but empty, as it used to be used to add a `nuget.config` file.

It used to be done that way:

```csharp
var nugetConfigPath = Path.Combine(_targetPath, "..\\nuget.config");

if (!File.Exists(nugetConfigPath))
{
    Directory.CreateDirectory(Path.Combine(_targetPath, "..\\PackageCache"));

	using (var reader = new StreamReader(GetType().Assembly.GetManifestResourceStream($"{GetType().Assembly.GetName().Name}.NuGet.config")))
	{
		File.WriteAllText(nugetConfigPath, reader.ReadToEnd());
	}
}
```

The added file needs to be provided as an embedded resource.

**Comment by MatFillion** [comment]
I've had this  problem (missing .net core 2.2 error) when setting up a new Visual Studio 2019, definitely a must to add this warning as soon as possible.

**Comment by ghuntley** [comment]
I think this should be merged before UnoConf. I _might_ have time today to get around to it but probably not. If you have capacity to take over that would be rad.

**Pull request closed without merging**
