### PR TITLE
[Android] BorderLayerRenderer - restore BorderThickness adjustment

### LINKED ISSUE #2263: [Android] Button displays 2 borders
## Current behavior

The button displays 2 borders

## Expected behavior

The button should display 1 border

## How to reproduce it (as minimally and precisely as possible)

Launch the sample and see that the button has 2 borders

Sample:
[BorderDouble.zip](https://github.com/unoplatform/uno/files/3946007/BorderDouble.zip)

## Environment

Nuget Package:
2.1.0-dev.7

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The code in the project has been changed, but the issue is still current
https://dev.azure.com/nventive/Umbrella/_workitems/edit/168888

### PR DESCRIPTION
**Pull request by davidjohnoliver**
When calculating the fill path for a control with a non-zero CornerRadius, ensure to adjust the fill area for the BorderThickness. This adjustment was erroneously removed when CornerRadius handling was refactored in #2190.

GitHub Issue (If applicable): fixes #2263

## PR Type

What kind of change does this PR introduce?

- Bugfix

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
This test result is very different, is this expected  ? https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=11698&view=ms.vss-test-web.build-test-results-tab&runId=1035164&resultId=100248&paneView=attachments

**Comment by davidjohnoliver** [comment]
> This test result is very different, is this expected ? https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=11698&view=ms.vss-test-web.build-test-results-tab&runId=1035164&resultId=100248&paneView=attachments

I get 'Build Not Found' when I click that link. Do you recall which test it was?

**Comment by davidjohnoliver** [comment]
Actually I get 'Build not Found' for the whole Tests tab...

**Comment by davidjohnoliver** [comment]
> This test result is very different, is this expected ? https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=11698&view=ms.vss-test-web.build-test-results-tab&runId=1035164&resultId=100248&paneView=attachments

Update: yes it's a big change, but it seems to be because it was broken before. 

Old | New | Windows:
image

Note the ImageBrush isn't appearing either in old or new, that must be a separate issue.

**Pull request merged**
