### PR TITLE
docs: Moved VisibleBoundsPadding.md to /docs/

### PR DESCRIPTION
**Pull request by hminaya**
GitHub Issue: #1324

## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

File is located @ https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Toolkit/VisibleBoundsPadding.md

## What is the new behavior?

Should be in /docs

### CODE REVIEW

**Comment by davidjohnoliver** [comment]
Nice, thanks Hector!

A couple of things:
 - can you put it in the `articles/features` directory please
 - can you add a link in this file: https://github.com/unoplatform/uno/blob/master/doc/articles/toc.yml#L67 - that'll make it appear in the table-of-contents sidebar in the docs website, so it's discoverable

**Comment by hminaya** [comment]
Thanks for the feedback @davidjohnoliver, I've updated the PR.

**Comment by hminaya** [comment]
@davidjohnoliver 

It seems the Android tests timed out at VS DevOps. https://uno-platform.visualstudio.com/Uno%20Platform/_build/results?buildId=7633

**Comment by hminaya** [comment]
@ghuntley here it is.

**Comment by ghuntley** [comment]
@all-contributors please add @hminaya for docs

**Pull request merged**
