### PR TITLE
feat: Lottie animations support on Android, iOS and macOS

### LINKED ISSUE #2881: Lottie animations on Android, iOS and macOS
## What would you like to be added:

Lottie animations on all platforms.

## Why is this needed:

Because animations are cool!

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #2881

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

Lottie supported on WASM only

## What is the new behavior?

Lottie everywhere.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by agneszitte-nventive** [comment]
Thanks a lot @MartinZikmund 👍 !

**Comment by carldebilly** [comment]
Nice work :-)

**Pull request merged**
