### PR TITLE
test: Move TextBox selection tests to runtime tests

### LINKED ISSUE #6933: [Wasm] The keyboard navigation buttons do not work in a TextBox
### Current behavior

The Home, End and arrow keyboard keys don't have an effect in a `TextBox`.

See https://playgroundcanary.z19.web.core.windows.net/#textbox in Uno 3.10-dev.

### Expected behavior

Home and End, or other navigation keys move the cursor,

### How to reproduce it (as minimally and precisely as possible)

Go to https://playgroundcanary.z19.web.core.windows.net/#textbox, enter some text then press the home button. Notice that the cursor stays at the end.

### Workaround

_No response_

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

_No response_

### Affected platforms

WebAssembly

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### LINKED ISSUE #6993: Range selection tests are failing
### Current behavior

`Calling_Select_With_NegativeValues`, `Calling_Select_With_In_Range_Values`, `Calling_Select_With_Out_Of_Range_Length` and `Calling_Select_With_Out_Of_Range_Start` are failing in CI.

### Expected behavior

_No response_

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

_No response_

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #6993

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Looks like those are not passing for Wasm: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=33075&view=ms.vss-test-web.build-test-results-tab&runId=1578142&resultId=100000&paneView=debug

**Comment by Youssef1313** [comment]
@jeromelaban I haven't confirmed locally on Wasm, but I can't see the failure in CI. Looks like another test that's failing?

**Comment by jeromelaban** [comment]
This is what the failure say:

image

**Comment by Youssef1313** [comment]
Oh sorry, I was searching in the failures by the test names, didn't know the original test name will show up as "RunRuntimeTests"

Will check why they're failing and fix them.

**Comment by Youssef1313** [comment]
@jeromelaban On Wasm, it looks like when the text is set natively, the cursor position is always set to the end.

In UWP, when the text is changed in code-behind, the selection is reset (selection start becomes 0 and length is 0 too). However, that's certainly not the case when the text is changed through key down events.

Part of this overlaps with a potentially more complex problem, caching the invalid selection values and applying them if the text changed and those cached values became valid. Are you okay if we adjusted the assertion for Wasm, and opened an issue for the remaining parts?

In case the "caching" thing isn't something to be imported directly from internal sources, I can give that a try in another PR. (I did that in another control but @davidjohnoliver pointed that it was more complex and needs to be imported. I'm not sure if that's the case for TextBox too)

**Comment by jeromelaban** [comment]
That's fair for now. Let's freeze what works for now, so that regressions can be caught and we'll track the rest.

**Review by MartinZikmund — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
