### PR TITLE
fix: Report a warning when xaml code behind does not have correct base class specified.

### PR DESCRIPTION
**Pull request by mterwoord**
GitHub Issue (If applicable): #3412 

## PR Type

What kind of change does this PR introduce?
Build warning, which warns for issues as described by #3412

## What is the current behavior?

No warning shown anywhere.

## What is the new behavior?

Warning shown.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
It works, even inside the uno solution:

image

Thought it fails the build as a result.

**Review by carldebilly — APPROVED** [review]

**Comment by mterwoord** [comment]
I pushed some new commits which should fix all concerns. 

About the failing test: I suppressed it, as it seems to be intentionally to leave it out there.

**Comment by mterwoord** [comment]
Somehow it seems I'm unable to suppress the error/warning. Anyone got any suggestions?

**Comment by mterwoord** [comment]
I tried with the `SuppressMessageAttribute`, but also using `#pragma warning disable UXAML0002` but both don't work.

**Comment by jeromelaban** [comment]
@mterwoord would you mind fixing the conflicts? There are also some code analysis warnings (e.g. missing readonly)

**Comment by jeromelaban** [comment]
Thanks for your contribution!

**Pull request merged**
