### PR TITLE
build: Avoid `Console.Write` in generators

### PR DESCRIPTION
**Pull request by Youssef1313**
See https://github.com/dotnet/roslyn-analyzers/issues/6185 for info why this is bad.

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
Nice catch!

**Comment by Youssef1313** [comment]
@jeromelaban Something is going wrong with `When_Transforms_Paused_With_FillBehaviorHold_Then_Hold`. I restarted the test run and it's failing.

I can't see any way this can be related to a `Console.Write` → `Console.WriteLine` change in generator .

**Comment by Youssef1313** [comment]
@jeromelaban I think you restarted the tests already one more time, but it's failing again 😕

**Comment by jeromelaban** [comment]
It's likely that this test fails when run alone. Let's merge as-is anyways for now.

**Pull request merged**
