### PR TITLE
Fix for Incorrect Discord Redirector Link

### PR DESCRIPTION
**Pull request by NateTheGreat714**
This is just an extremely small update to fix the incorrect Discord link that I assume nobody has noticed yet. The original link had 4 `w's` making the link "https://wwww.platform....." instead of only 3, which is the global standard abbreviation for a World Wide Web link. Love the Uno Platform, please keep up the amazing work everyone, and hopefully now more people can join the Discord to discuss this project and platform more as well as give and receive more support instantly!

Thanks for your time,
-Nathan Tuttle

P.S. Please also read the "More Information" section in this Pull Request, as it might be an even better solution that works just the same, but additionally adds an extra feature to joining the Discord server that makes the process much easier for users who have Discord installed locally on their device(s)! 😃 

GitHub Issue (If applicable): #

Just a small incorrectly-typed link containing four Ws in the URL prefix after the https:// protocol string.

## PR Type

What kind of change does this PR introduce?

- Refactoring (no functional changes, no api changes)

## What is the current behavior?

Prior to this Pull Request, no web-browser or program will be able to locate the link, as it does not currently exist.

## What is the new behavior?

After/if this Pull Request is accepted, the user will then be sent to the correct Discord server link, rather than a link that does not currently exist.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ✔ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ N/A ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ❌ ] Validated PR `Screenshots Compare Test Run` results.
- [ ✔ ] Contains **NO** breaking changes
- [ ❌ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ✔ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

**Hopefully this section will also get read by somebody**, but you might also want to think about redirecting the user directly to a Discord Invitation link ending with the suffix ".gg" rather than ".com" (you can just swap the suffixes with the current link if you wish, as I have tested it and it works perfectly without issues), as it is much easier to join the server if the application is already installed on a user's computer as it will come right up and automatically join them to the server. If it doesn't detect the program as being installed already, then it will also let them chat over the web through that same link as well. So the ".gg" suffix just adds an extra feature for the people who already have the program installed. Not to mention, for people who don't trust clicking on links, if it is a ".gg" link as I described, they can simply copy and paste it within the Discord application itself to join the server manually.

Internal Issue (If applicable):
N/A.

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for the PR! Would you know where to find some documentation about the `.gg` behavior ?

**Comment by NateTheGreat714** [comment]
> Congrats on your first pull-request! We ❤ the people who are involved in this project, and we’d love to pay it forward by [sending you some swag](https://forms.office.com/Pages/ResponsePage.aspx?id=Ye9TbdG2UEGuC0O5DnXgzai0HkTgxONNjPmzuZ5zgdRUQzFJMVBPSU8xWDBUUlNOTExCWFUwQjNBNy4u). If you have any feedback (or ideas how to improve Uno as a open-source project) please [open a feedback issue](https://github.com/unoplatform/uno/issues/new?labels=kind%2Ffeedback%2C+triage%2Funtriaged&template=feedback.md).
> giphy
> Merci beaucoup 👋

Not sure what this "swag" is, but that link does not work anyway 😅, is there anyway you might be able to resend that swag link? lol

**Comment by NateTheGreat714** [comment]
> Thanks for the PR! Would you know where to find some documentation about the `.gg` behavior ?

No problem at all! I will now delete the fork since I now see it has been merged, but if you keep this pull request here instead of archiving it, I can get back to you tomorrow with much more information on the ``.gg`` link behaviors vs the regular ``.com`` behavior! (Unless there is some way I can message you directly on this that I cannot currently find! I'd be more than happy to supply you with more info on the different link suffixes as soon as I get the chance! Thanks for responding and reviewing this PR so quickly by the way! :) I will get back to you first thing tomorrow morning about the links! Thanks again!

**Comment by sasakrsmanovic** [comment]
Hi @NateTheGreat714 . Thanks for contacting us. I will have the link to contributor form changed. In the meantime can you please email me at sasha at platform.uno so I can get you the swag. Thanks

**Pull request merged**
