### PR TITLE
chore: leak test

### PR DESCRIPTION
**Pull request by Youssef1313**
Related to #11976. Let's see if any test will fail.

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
@jeromelaban I was expecting that the test you added in https://github.com/unoplatform/uno/pull/3936 will fail with this change, but it didn't.

**Comment by jeromelaban** [comment]
If it's not failing, there's a missing test. Apple platforms have implicit pinning of native-inheriting references, causing a circular reference that the .NET GC is not able to handle (and neither does Apple's ref counting).

**Comment by Youssef1313** [comment]
@jeromelaban Looking into this again, the circular reference here is between one type that is UIElement (NSObject), and one type that is just System.Object (no native counterpart).

So, I think as long as the circular reference is not at native side, we should be good and not leaking.

**Comment by Youssef1313** [comment]
@jeromelaban It also appears that there is a test added with the initial introduction of this specific code:

https://github.com/unoplatform/uno/blob/0effad58fd8a6c6e75380f0496c779f654275fc1/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs#L45-L46

**Pull request closed without merging**
