### PR TITLE
Aligning settings with UWP

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): #1104 

## PR Type
What kind of change does this PR introduce?
- Bugfix 

## What is the current behavior?
Adding a `null` value to settings behaves differently on each platform (throws on Android and iOS). Adding value for the same key multiple times works.

## What is the new behavior?
Behavior aligned with UWP:

- Adding a `null` value is equivalent to Remove and does not throw. 
- Attempting to `Add` a value for a setting which already exists throws a descriptive `ArgumentException`.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Comment by jeromelaban** [comment]
Could you add a test for that here:
https://github.com/nventive/Uno/blob/master/src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_ApplicationDataContainer.cs

**Comment by MartinZikmund** [comment]
@jeromelaban definitely!

**Comment by MartinZikmund** [comment]
@jeromelaban I have added the unit tests but I couldn't figure out a way to execute the `Uno.UI.RuntimeTests`... so they may fail :-D . Is there a way to execute them from VS?

**Comment by jeromelaban** [comment]
@MartinZikmund the tests are going to be executed in PRs when #1184 will be fixed :) We'll rerun the checks then

**Comment by jeromelaban** [comment]
Your tests ran in both Android and Wasm 🎉

**Pull request merged**
