### PR TITLE
Correct spelling

### PR DESCRIPTION
**Pull request by hugovk**
## PR Type

What kind of change does this PR introduce?

- Bugfix
- Documentation content changes

Corrects some misspellings and typos.

## PR Checklist

Please check if your PR fulfils the following requirements:

- [x] Tested code with current [supported SDKs](../README.md#supported)
- [n/a] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [n/a] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [n/a] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [n/a] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [n/a] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Comment by hugovk** [comment]
You're welcome!

**Comment by ghuntley** [comment]
@hugovk if you haven't already, could you please leave your details at https://platform.uno/uno-is-joining-hacktoberfest-2019/ so that we can send you some swag?

**Comment by hugovk** [comment]
Done, thank you!

**Comment by ghuntley** [comment]
@all-contributors please add @hugovk for docs

**Comment by carldebilly** [comment]
Wonderful!

**Pull request merged**
