### PR TITLE
fixed ObjectDisposedException in BindingPath

### PR DESCRIPTION
**Pull request by XiaotianNetlift**
GitHub Issue (If applicable): #2570

## PR Type
What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?
In some situation, an ObjectDisposedException is thrown from `BindingPath` and cause the binding to fail.

## What is the new behavior?
No more exception being thrown.

## PR Checklist
Please check if your PR fulfills the following requirements:
- [ ] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information
Internal Issue (If applicable): n/a

### CODE REVIEW

**Comment by XiaotianNetlift** [comment]
Since this issue is presumably based on a race-condition between the event unsubscription and the event being fired, what kind of test do we look for here? The happy path would mean nothing here, while the sad path would probably require some brute-forcing with threads.

**Comment by jeromelaban** [comment]
In this case, this fix is most likely not addressing the issue. PropertyChanged handlers are supposed to be raised on the UI thread, and should fail that way.

Do you have a stack trace available ?

**Comment by XiaotianNetlift** [comment]
Here they are:
```
0 @ handler invoke
>	0x9B in Uno.UI.DataBinding.BindingPath. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:333,8	C#
 	0x46 in nVentive.Umbrella.Presentation.Light.ViewModelBase.RaisePropertyChanged at C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:404,5	C#
 	0x11 in nVentive.Umbrella.Presentation.Light.ViewModelBase.OnDynamicPropertiesPropertyChanged at C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:335,5	C#
 	0x2D in nVentive.Umbrella.Presentation.Light.DynamicProperties. at C:\agent\_work\76\s\src\Umbrella.Presentation\DynamicProperties.cs:176,6	C#
 	0xD in System.DelegateExtensions.<>c__DisplayClass2_0<nVentive.Umbrella.Presentation.Light. at E:\nventive\Agent01\17\s\Rx.NET\Source\System.Reactive.Core\NonGeneric\DelegateExtensions.cs:27,29	C#
 	0x27 in nVentive.Umbrella.Concurrency.BatchScheduler. at C:\agent\_work\76\s\src\Umbrella.Reactive\Concurrency\BatchScheduler.cs:73,6	C#
 	0x44 in nVentive.Umbrella.Concurrency.BatchScheduler.Runner at C:\agent\_work\76\s\src\Umbrella.Reactive\Concurrency\BatchScheduler.cs:108,6	C#
 	0x6 in System.Reactive.Concurrency.Scheduler.Invoke at E:\nventive\Agent01\17\s\Rx.NET\Source\System.Reactive.Core\Reactive\Concurrency\Scheduler.Simple.cs:82,13	C#
 	0x25 in System.Reactive.Concurrency.CoreDispatcherScheduler. at C:\agent\_work\76\s\src\Umbrella.Reactive.UWP\CoreDispatcherScheduler.Xamarin.cs:70,7	C#
 	0x105 in Windows.UI.Core.CoreDispatcher.DispatchItems at D:\code\framework\uno\src\Uno.UWP\UI\Core\CoreDispatcher.cs:262,9	C#
 	0x7 in Windows.UI.Core.CoreDispatcher.CoreDispatcherImplementor.Java.Lang.IRunnable.Run at D:\code\framework\uno\src\Uno.UWP\UI\Core\CoreDispatcher.Android.cs:151,5	C#
 	0xA in Java.Lang.IRunnableInvoker.n_Run	C#
 	0x11 in Android.Runtime.DynamicMethodNameCounter.4	C#

1 @ handler dispose
>	0x2E in Uno.UI.DataBinding.BindingPath. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:353,6	C#
 	0x11 in Uno.Disposables.AnonymousDisposable.Dispose	C#
 	0x62 in Uno.Disposables.CompositeDisposable.Dispose	C#
 	0x3D in Uno.Disposables.SerialDisposable.set_Disposable	C#
 	0x91 in Uno.UI.DataBinding.BindingPath.BindingItem.OnDataContextChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:522,6	C#
 	0x10 in Uno.UI.DataBinding.BindingPath.BindingItem.SetWeakDataContext at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:412,5	C#
 	0x1C in Uno.UI.DataBinding.BindingPath.OnDataContextChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:268,5	C#
 	0x1E in Uno.UI.DataBinding.BindingPath.SetWeakDataContext at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:255,5	C#
 	0x9 in Uno.UI.DataBinding.BindingPath.set_DataContext at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:244,5	C#
 	0x68 in Windows.UI.Xaml.Data.BindingExpression.ApplyBinding at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:401,5	C#
 	0x46 in Windows.UI.Xaml.Data.BindingExpression.set_DataContext at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:67,6	C#
 	0x84 in Windows.UI.Xaml.DependencyPropertyDetailsCollection.ApplyBinding at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyPropertyDetailsCollection.Bindings.cs:164,6	C#
 	0x17 in Windows.UI.Xaml.DependencyPropertyDetailsCollection.ApplyDataContext at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyPropertyDetailsCollection.Bindings.cs:48,5	C#
 	0x6C in Windows.UI.Xaml.DependencyObjectStore.OnDataContextChanged at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.Binder.cs:281,7	C#
 	0x133 in Windows.UI.Xaml.DependencyObjectStore.InnerSetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:485,6	C#
 	0x47 in Windows.UI.Xaml.DependencyObjectStore.SetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:410,6	C#
 	0x73 in Windows.UI.Xaml.DependencyObjectStore.<RegisterInheritedProperties>b__126_0 at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1034,7	C#
 	0x11 in Uno.Disposables.AnonymousDisposable.Dispose	C#
 	0x62 in Uno.Disposables.CompositeDisposable.Dispose	C#
 	0x3D in Uno.Disposables.SerialDisposable.set_Disposable	C#
 	0x64 in Windows.UI.Xaml.DependencyObjectStore.set_Parent at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:131,6	C#
 	0xF in Windows.UI.Xaml.FrameworkElement.OnRemovedFromParent at D:\code\framework\uno\src\Uno.UI\UI\Xaml\FrameworkElement.Android.cs:155,4	C#
 	0xB in Uno.UI.UnoViewGroup.n_OnRemovedFromParent at D:\code\framework\uno\src\Uno.UI.BindingHelper.Android\obj\Debug\MonoAndroid90\generated\src\Uno.UI.UnoViewGroup.cs:816,4	C#
 	0x11 in Android.Runtime.DynamicMethodNameCounter.97	C#
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#
 	0x21 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod	C#
 	0x3A in Uno.UI.UnoViewGroup.RemoveViewFast at D:\code\framework\uno\src\Uno.UI.BindingHelper.Android\obj\Debug\MonoAndroid90\generated\src\Uno.UI.UnoViewGroup.cs:875,5	C#
 	0x3B in Uno.UI.Controls.BindableView.RemoveView at D:\code\framework\uno\src\Uno.UI\Controls\BindableView.Android.cs:153,4	C#
 	0x13 in Uno.UI.ViewExtensions.RemoveViewAndDispose at D:\code\framework\uno\src\Uno.UI\Extensions\ViewExtensions.Android.cs:322,5	C#
 	0x8 in Windows.UI.Xaml.Controls.ContentPresenter.UnregisterContentTemplateRoot at D:\code\framework\uno\src\Uno.UI\UI\Xaml\Controls\ContentPresenter\ContentPresenter.Android.cs:61,4	C#
 	0x1A in Windows.UI.Xaml.Controls.ContentPresenter.set_ContentTemplateRoot at D:\code\framework\uno\src\Uno.UI\UI\Xaml\Controls\ContentPresenter\ContentPresenter.cs:647,6	C#
 	0x11 in Windows.UI.Xaml.Controls.ContentPresenter.OnContentTemplateChanged at D:\code\framework\uno\src\Uno.UI\UI\Xaml\Controls\ContentPresenter\ContentPresenter.cs:620,5	C#
 	0x22 in Windows.UI.Xaml.Controls.ContentPresenter.<>c.<.cctor>b__192_1 at D:\code\framework\uno\src\Uno.UI\UI\Xaml\Controls\ContentPresenter\ContentPresenter.cs:96,16	C#
 	0xF in Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged at D:\code\framework\uno\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:133,4	C#
 	0x121 in Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1461,4	C#
 	0x77 in Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1375,5	C#
 	0x22D in Windows.UI.Xaml.DependencyObjectStore.InnerSetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:500,5	C#
 	0x47 in Windows.UI.Xaml.DependencyObjectStore.SetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:410,6	C#
 	0x1F in Windows.UI.Xaml.DependencyObjectExtensions.SetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectExtensions.cs:190,4	C#
 	0x4C in Uno.UI.DataBinding.BindingPropertyHelper. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:831,34	C#
 	0x1E in Windows.UI.Xaml.Data.BindingExpression.SetTargetValue at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:356,5	C#
 	0x11A in Windows.UI.Xaml.Data.BindingExpression.SetTargetValueSafe at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:455,7	C#
 	0x4 in Windows.UI.Xaml.Data.BindingExpression.SetTargetValueSafe at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:423,4	C#
 	0x3 in Windows.UI.Xaml.Data.BindingExpression.Uno.UI.DataBinding.IValueChangedListener.OnValueChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:418,4	C#
 	0xE in Uno.UI.DataBinding.BindingPath.Uno.UI.DataBinding.IValueChangedListener.OnValueChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:279,4	C#
 	0xE in Uno.UI.DataBinding.BindingPath.BindingItem.RaiseValueChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:691,5	C#
 	0x31 in Uno.UI.DataBinding.BindingPath.BindingItem.<OnDataContextChanged>b__39_0 at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:502,11	C#
 	0x25 in Uno.UI.DataBinding.BindingPath.BindingItem. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:711,7	C#
 	0x6 in Windows.UI.Xaml.DependencyObjectStore. at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.Binder.cs:472,66	C#
 	0x18 in Windows.UI.Xaml.DependencyObjectStore. at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1301,15	C#
 	0x33 in Windows.UI.Xaml.DependencyPropertyCallbackManager.RaisePropertyChanged at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyPropertyCallbackManager.cs:65,17	C#
 	0x12F in Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1464,4	C#
 	0x77 in Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1375,5	C#
 	0x22D in Windows.UI.Xaml.DependencyObjectStore.InnerSetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:500,5	C#
 	0x47 in Windows.UI.Xaml.DependencyObjectStore.SetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:410,6	C#
 	0x1F in Windows.UI.Xaml.DependencyObjectExtensions.SetValue at D:\code\framework\uno\src\Uno.UI\UI\Xaml\DependencyObjectExtensions.cs:190,4	C#
 	0x4C in Uno.UI.DataBinding.BindingPropertyHelper. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:831,34	C#
 	0x1E in Windows.UI.Xaml.Data.BindingExpression.SetTargetValue at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:356,5	C#
 	0x11A in Windows.UI.Xaml.Data.BindingExpression.SetTargetValueSafe at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:455,7	C#
 	0x4 in Windows.UI.Xaml.Data.BindingExpression.SetTargetValueSafe at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:423,4	C#
 	0x3 in Windows.UI.Xaml.Data.BindingExpression.Uno.UI.DataBinding.IValueChangedListener.OnValueChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingExpression.cs:418,4	C#
 	0xE in Uno.UI.DataBinding.BindingPath.Uno.UI.DataBinding.IValueChangedListener.OnValueChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:279,4	C#
 	0xE in Uno.UI.DataBinding.BindingPath.BindingItem.RaiseValueChanged at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:691,5	C#
 	0x31 in Uno.UI.DataBinding.BindingPath.BindingItem.<OnDataContextChanged>b__39_0 at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:502,11	C#
 	0x25 in Uno.UI.DataBinding.BindingPath.BindingItem. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:711,7	C#
 	0xB1 in Uno.UI.DataBinding.BindingPath. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:333,8	C#
 	0x46 in nVentive.Umbrella.Presentation.Light.ViewModelBase.RaisePropertyChanged at C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:404,5	C#
 	0x11 in nVentive.Umbrella.Presentation.Light.ViewModelBase.OnDynamicPropertiesPropertyChanged at C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:335,5	C#
 	0x2D in nVentive.Umbrella.Presentation.Light.DynamicProperties. at C:\agent\_work\76\s\src\Umbrella.Presentation\DynamicProperties.cs:176,6	C#
 	0xD in System.DelegateExtensions.<>c__DisplayClass2_0<nVentive.Umbrella.Presentation.Light. at E:\nventive\Agent01\17\s\Rx.NET\Source\System.Reactive.Core\NonGeneric\DelegateExtensions.cs:27,29	C#
 	0x27 in nVentive.Umbrella.Concurrency.BatchScheduler. at C:\agent\_work\76\s\src\Umbrella.Reactive\Concurrency\BatchScheduler.cs:73,6	C#
 	0x44 in nVentive.Umbrella.Concurrency.BatchScheduler.Runner at C:\agent\_work\76\s\src\Umbrella.Reactive\Concurrency\BatchScheduler.cs:108,6	C#
 	0x6 in System.Reactive.Concurrency.Scheduler.Invoke at E:\nventive\Agent01\17\s\Rx.NET\Source\System.Reactive.Core\Reactive\Concurrency\Scheduler.Simple.cs:82,13	C#
 	0x25 in System.Reactive.Concurrency.CoreDispatcherScheduler. at C:\agent\_work\76\s\src\Umbrella.Reactive.UWP\CoreDispatcherScheduler.Xamarin.cs:70,7	C#
 	0x105 in Windows.UI.Core.CoreDispatcher.DispatchItems at D:\code\framework\uno\src\Uno.UWP\UI\Core\CoreDispatcher.cs:262,9	C#
 	0x7 in Windows.UI.Core.CoreDispatcher.CoreDispatcherImplementor.Java.Lang.IRunnable.Run at D:\code\framework\uno\src\Uno.UWP\UI\Core\CoreDispatcher.Android.cs:151,5	C#
 	0xA in Java.Lang.IRunnableInvoker.n_Run	C#
 	0x11 in Android.Runtime.DynamicMethodNameCounter.4	C#

2 @ handler invoke
// newValueActionWeak.IsDispose: true
>	0x9B in Uno.UI.DataBinding.BindingPath. at D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:333,8	C#
 	0x46 in nVentive.Umbrella.Presentation.Light.ViewModelBase.RaisePropertyChanged at C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:404,5	C#
 	0x11 in nVentive.Umbrella.Presentation.Light.ViewModelBase.OnDynamicPropertiesPropertyChanged at C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:335,5	C#
 	0x2D in nVentive.Umbrella.Presentation.Light.DynamicProperties. at C:\agent\_work\76\s\src\Umbrella.Presentation\DynamicProperties.cs:176,6	C#
 	0xD in System.DelegateExtensions.<>c__DisplayClass2_0<nVentive.Umbrella.Presentation.Light. at E:\nventive\Agent01\17\s\Rx.NET\Source\System.Reactive.Core\NonGeneric\DelegateExtensions.cs:27,29	C#
 	0x27 in nVentive.Umbrella.Concurrency.BatchScheduler. at C:\agent\_work\76\s\src\Umbrella.Reactive\Concurrency\BatchScheduler.cs:73,6	C#
 	0x44 in nVentive.Umbrella.Concurrency.BatchScheduler.Runner at C:\agent\_work\76\s\src\Umbrella.Reactive\Concurrency\BatchScheduler.cs:108,6	C#
 	0x6 in System.Reactive.Concurrency.Scheduler.Invoke at E:\nventive\Agent01\17\s\Rx.NET\Source\System.Reactive.Core\Reactive\Concurrency\Scheduler.Simple.cs:82,13	C#
 	0x25 in System.Reactive.Concurrency.CoreDispatcherScheduler. at C:\agent\_work\76\s\src\Umbrella.Reactive.UWP\CoreDispatcherScheduler.Xamarin.cs:70,7	C#
 	0x105 in Windows.UI.Core.CoreDispatcher.DispatchItems at D:\code\framework\uno\src\Uno.UWP\UI\Core\CoreDispatcher.cs:262,9	C#
 	0x7 in Windows.UI.Core.CoreDispatcher.CoreDispatcherImplementor.Java.Lang.IRunnable.Run at D:\code\framework\uno\src\Uno.UWP\UI\Core\CoreDispatcher.Android.cs:151,5	C#
 	0xA in Java.Lang.IRunnableInvoker.n_Run	C#
 	0x11 in Android.Runtime.DynamicMethodNameCounter.4	C#

nVentive.Umbrella.Concurrency.BatchScheduler: Error: BatchScheduler failed execution

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ManagedWeakReference'.
  at Uno.UI.DataBinding.ManagedWeakReference.get_Target () [0x0000c] in D:\code\framework\uno\src\Uno.UI\DataBinding\ManagedWeakReference.cs:45 
  at Uno.UI.DataBinding.BindingPath+<>c__DisplayClass36_1.<SubscribeToNotifyPropertyChanged>b__0 (System.Object s, System.ComponentModel.PropertyChangedEventArgs args) [0x0009b] in D:\code\framework\uno\src\Uno.UI\DataBinding\BindingPath.cs:333 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at nVentive.Umbrella.Presentation.Light.ViewModelBase.RaisePropertyChanged (System.String propertyName) [0x00039] in C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:404 
  at nVentive.Umbrella.Presentation.Light.ViewModelBase.OnDynamicPropertiesPropertyChanged (System.String propertyName) [0x00000] in C:\agent\_work\76\s\src\Umbrella.Presentation\ViewModelBase.cs:335 
  at nVentive.Umbrella.Presentation.Light.DynamicProperties+<>c__DisplayClass21_0.<OnPropertyChanged>b__1 (System.Reactive.Concurrency.IScheduler s, nVentive.Umbrella.Presentation.Light.PropertyChangedMessage innerMessage) [0x00011] in C:\agent\_work\76\s\src\Umbrella.Presentation\DynamicProperties.cs:176 
  at System.DelegateExtensions+<>c__DisplayClass2_0`1[TState].<AsCoreScheduledAction>b__0 (System.Reactive.Concurrency.IScheduler scheduler, System.Object state) [0x00000] in E:\nventive\Agent01\17\s\Rx.NET\Source\System.Reactive.Core\NonGeneric\DelegateExtensions.cs:27 
  at nVentive.Umbrella.Concurrency.BatchScheduler+<>c__DisplayClass7_0.<ScheduleCore>b__0 () [0x0000f] in C:\agent\_work\76\s\src\Umbrella.Reactive\Concurrency\BatchScheduler.cs:73
```

**Comment by jeromelaban** [comment]
From the stack traces you're providing, the condition seems to be between the update of the datacontext of a path, and the changing of an observed value. That can happen synchronously. The `ManagedWeakReference` becomes disposed when this line is invoked:

https://github.com/unoplatform/uno/blob/885b3e1bd585c1a34b9ab75902dc3bd14e362ebc/src/Uno.UI/DataBinding/BindingPath.cs#L343

It feels like there's a path we're not testing that is not related to threading and that it may hide a more subtle bug. Also, there's `ManagedWeakReference.IsDisposed` that can be used instead of creating variable.

One way that could happen is if this line is not called:

https://github.com/unoplatform/uno/blob/885b3e1bd585c1a34b9ab75902dc3bd14e362ebc/src/Uno.UI/DataBinding/BindingPath.cs#L340

But for that to happen, the object would need to be in the GC finalizer, which does not seem to be the case given the traces you provided.

**Pull request merged**
