### PR TITLE
fix(net8): Adjust WinUI property detection

### PR DESCRIPTION
**Pull request by jeromelaban**
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/discussions/13678

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the new behavior?

.NET 8 changes the ordering of nuget defined props files, This change makes WinUI detection independent of nuget props import and rely on .targets evaluation.

### <samp>🤖 Generated by Copilot at 591797b</samp>

Moved the import of `uno.winui.common.props` to the targets file and added a check for WinAppSDK projects. This fixes a bug where WinUI projects using WinAppSDK were not recognized by Uno.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Comment by nickrandolph** [comment]
@jeromelaban does this need a backport?
I'm seeing breaks in backports for winappsdk1.4 in the template (https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=94897&view=logs&j=335ef1ab-48ae-5186-b973-d0e3cea6d38d&t=16805c7a-e849-5ecb-82da-2506fc8b7e98).
If we do backport, we should make sure it's done after this backport is merged https://github.com/unoplatform/uno/pull/13571

**Comment by tibitoth** [comment]
@jeromelaban How can I use this fix, I tried to install preview packages but I got the same error.

**Comment by jeromelaban** [comment]
@tibitoth this has been release in the latest build of 4.10.x. If you're still having issues, make sure to [open a discussion](https://github.com/unoplatform/uno/discussions).

**Comment by limeniye** [comment]
```
this has been release in the latest build of 4.10.x.
```

@jeromelaban, I apologize for asking, but what about version 5.0.0-dev.****?
Not yet?

**Comment by jeromelaban** [comment]
@limeniye can you open a discussion with more details, this is already on 5.0-dev builds. Thanks!

**Pull request merged**
