### PR TITLE
fix(Geolocator): when requested in non-ui thread

### PR DESCRIPTION
**Pull request by ajpinedam**
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/discussions/16079

## PR Type

What kind of change does this PR introduce?

- Bugfix

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by agneszitte — COMMENTED** [review]
Any tests for these changes @ajpinedam?

**Comment by ajpinedam** [comment]
> Any tests for these changes @ajpinedam?

Not possible to test since it requires a device to get the Location updates. However, I am adding a manual test that reproduces the error, and we could use it to validate the fix.

cc: @agneszitte

**Comment by MartinZikmund** [comment]
@ajpinedam In case of WinUI, can `RequestAccessAsync` actually be called from a non-UI thread? I would expect it to throw

**Comment by ajpinedam** [comment]
@MartinZikmund  Ran the Windows head, and it ran without issues

image

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
