### PR TITLE
feat(template): Move to single location projects

### PR DESCRIPTION
**Pull request by jeromelaban**
GitHub Issue (If applicable): closes #

## PR Type
- Feature

## What is the new behavior?

This change removes the use of shared projects, which cause many issues insde VS, as well as VS Code (incorrect removal, incorrect addition of files, failure to properly explain how to include multiple nuget packages, complex vscode globbing).

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by dansiegel — COMMENTED** [review]
The AndroidManifest.xml / Info.plist's should be updated the remove the properties set by the msbuild properties... so this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.companyname.$ext_safeprojectname$" android:versionCode="1" android:versionName="1.0">
  <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="31" />
  <application android:label="$ext_safeprojectname$"></application>
</manifest>
```
Would become:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <application></application>
</manifest>
```
*NOTE: `uses-sdk` is injected automatically based on the SDK version it is built against and the minimum supported sdk set in the csproj*

**Review by spouliot — COMMENTED** [review]
Do you can to marge https://github.com/unoplatform/uno/pull/10357 before ? inside ? or after this PR ?

One of the nice things about the default net5+ `.csproj` is that they are small and used to change defaults.

In contrast the current .csproj for Uno apps are quite large. It would be nice to move a lot of the config into some files inside Uno.

**Comment by spouliot** [comment]
@dansiegel good catch. There's already an issue about this https://github.com/unoplatform/uno/issues/9903

**Comment by jeromelaban** [comment]
Thanks for the reviews! Indeed, we can remove most of the content of the android xml file.

**Comment by dansiegel** [comment]
You've also got this bit which can be removed from the Info.plist for the iOS, macOS, & MacCatalyst projects as these will be injected by the iOS/Mac SDK using the msbuild props

```xml
<key>CFBundleDisplayName</key>
<string>$ext_safeprojectname$</string>
<key>CFBundleIdentifier</key>
<string>com.companyname.$ext_safeprojectname$</string>
<key>CFBundleShortVersionString</key>
<string>1.0</string>
<key>CFBundleVersion</key>
<string>1.0</string>
```

**Review by spouliot — APPROVED** [review]

**Pull request merged**
