### PR TITLE
automation: automatically invite contributors to the github organization

### PR DESCRIPTION
**Pull request by ghuntley**
## PR Type
What kind of change does this PR introduce?

- Community automation changes

## What is the current behavior?

- Maintainers cannot assign issues to people who are not part of an organisation.
- No rewards (being able to wear the uno badge on their GitHub profile) for contribution.

## What is the new behavior?

- All of above is resolved via automation.
- When a pull-request is merged the robot will invite the author to join the GitHub organisation into the team defined in the configuration file.
- They are added to the community group which has no permissions.
- Maintainers can assign issues to the community.

https://help.github.com/en/articles/repository-permission-levels-for-an-organization

nb. The organization is configured to disable access to all private repositories (admins need to manually whitelist teams on a per repo basis)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Documentation for this automation can be found at https://probot.github.io/apps/invite-contributors/

### CODE REVIEW

**Comment by ghuntley** [comment]
We discussed internally and the idea of allowing all contributors to triage via labels by default is too progressive and ahead of its time. In the future, we could create smaller triage terms if need be.

**Comment by ghuntley-testing** [comment]
:wave: doing some last minute testing of organization ACL's. This user belongs to the community group and no other groups. Here's the outcome:

image

image

image


image


image

**Comment by ghuntley** [comment]
Confirming that it is possible to assign community members to GitHub issues.

image

**Comment by ghuntley** [comment]
⚠️ **important**: Always keep the GitHub organization configured as follows: ⚠️ 
 
image

**Comment by ghuntley** [comment]
Doing some last minute checks over at https://github.com/ghuntley-testing-org

**Comment by ghuntley** [comment]
1. user contributes to organization

image

2. invitation arrives in email

image

3. confirmation that the user is added to the team

image


4. confirmation that the ACL is set correctly.

image

Ready to ship.

**Pull request merged**
