### PR TITLE
feat(DecimalFormatter): Implement FormatDouble and ParseDouble

### PR DESCRIPTION
**Pull request by MohammadHadi2031**
GitHub Issue (If applicable): part of #6908

## PR Type

What kind of change does this PR introduce?

- Feature
## What is the current behavior?

Nothing.

## What is the new behavior?

Can format and parse doubles.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MohammadHadi2031** [comment]
@jeromelaban Thanks for merging #7090. Should I add UI test for NumberBox?

**Comment by jeromelaban** [comment]
> @jeromelaban Thanks for merging #7090. Should I add UI test for NumberBox?

It would be interesting to add those tests indeed, as the feature is gated behind this:

https://github.com/unoplatform/uno/blob/38b35f3ac012e2a71c67d958e4ebc6084a565fd2/src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs#L389

**Comment by MohammadHadi2031** [comment]
I see WebAssembly runtime test failed:
Failed : SamplesApp.UITests.Microsoft_UI_Xaml_Controls.NumberBoxTests.NumberBoxTests.DecimalFormatterTest 

Expected: 1.75d 

But was: 1.7d

But it passes on Android. Actually I couldn't run SamplesApp.Wasm on my computer and tested SamplesApp.Droid and then commited changes into repository. @MartinZikmund I think you are reviewing this PR would you mind guiding me to solve the issue?

**Comment by MohammadHadi2031** [comment]
@jeromelaban Would you mind check it out?

> I see WebAssembly runtime test failed: Failed : SamplesApp.UITests.Microsoft_UI_Xaml_Controls.NumberBoxTests.NumberBoxTests.DecimalFormatterTest
> 
> Expected: 1.75d
> 
> But was: 1.7d
> 
> But it passes on Android. Actually I couldn't run SamplesApp.Wasm on my computer and tested SamplesApp.Droid and then commited changes into repository. Would you mind guiding me to solve the issue?

This is the last step for supporting NumberBox.NumberFormatter. Can we have it in Uno Platform 4.0.0?

**Comment by jeromelaban** [comment]
> @jeromelaban Would you mind check it out?
> 
> > I see WebAssembly runtime test failed: Failed : SamplesApp.UITests.Microsoft_UI_Xaml_Controls.NumberBoxTests.NumberBoxTests.DecimalFormatterTest
> > Expected: 1.75d
> > But was: 1.7d
> > But it passes on Android. Actually I couldn't run SamplesApp.Wasm on my computer and tested SamplesApp.Droid and then commited changes into repository. Would you mind guiding me to solve the issue?
> 
> This is the last step for supporting NumberBox.NumberFormatter. Can it be part of Uno Platform 4.0.0?

Let's rerun the build for now, I do not know what may be different there.

**Comment by jeromelaban** [comment]
So on Skia runtime tests, this looks like a precision issue:
image

Which looks pretty similar to the Error found here:

image

For NumberBox, my guess would be that the control is setting a significant digits number that is not what you expect. 

You mention you're not able to run the Wasm app, what's the issue ?

**Comment by MohammadHadi2031** [comment]
@jeromelaban After releasing VS2022 I removed VS2019. Now I have problems with building SampleApp.Wasm. Building the project is time and memory hungry and I didn't have much time today to solving the problems. I will try again in tow days and inform you. 
I rebased the branch so the pipeline has been started.

**Comment by MohammadHadi2031** [comment]
I remember that I couldn't run wasm app and the problem was that a the project successfully has been built and run but a console window was shown, showing app URL. I entered the URI but the browser couldn't load any thing. Looked like the URI was wrong

**Comment by MohammadHadi2031** [comment]
@jeromelaban Yesterday I tried to build SamplesApp.Wasm but failed. Then I tried to build Uno.UI.Tests and run tests locally but failed to build. It seems that uninstalling VS2019 was a mistake. 
I got these errors: 

Screenshot 2021-11-26 213310

**Comment by jeromelaban** [comment]
So the last validation Skia is providing this error:

image

See https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=1675990&_a=resultSummary&resultId=103454

and 

image

Is looking like a default value precision change.

https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=1675984&_a=resultSummary&resultId=100000

**Comment by MohammadHadi2031** [comment]
> So the last validation Skia is providing this error:
> 
> image
> 
> See https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=1675990&_a=resultSummary&resultId=103454
> 
> and
> 
> image
> 
> Is looking like a default value precision change.
> 
> https://dev.azure.com/uno-platform/Uno%20Platform/_TestManagement/Runs?runId=1675984&_a=resultSummary&resultId=100000

I will check it out in a few days thank you.

**Comment by MartinZikmund** [comment]
@MohammadHadi2031 Hi, what is missing here?

**Comment by MohammadHadi2031** [comment]
@MartinZikmund Hi, my problem is that I couldn't prepare test environment. Tests fails to run. I successfully build and run SampleApps.Wasm and I can load it in the browser but when I run any test the "app" variable is null. `AppInitializer.AttachToApp();` returns null. I changed the WebAssemblyDefaultUri in Constants.cs to the URL used for loading in the browser. I'm trying again since last night. I will share results here. Currently my biggest problem is that building the SampleApps.Wasm need much time.

**Comment by MohammadHadi2031** [comment]
When I tried to run SamplesApp.Wasm with IIS Express I got this error:
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.WebAssembly.DebuggerProxy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by MartinZikmund** [comment]
@MohammadHadi2031 Sorry, I forgot to reply... But I see the build is passing now! Ready for review?

**Comment by MohammadHadi2031** [comment]
> @MohammadHadi2031 Sorry, I forgot to reply... But I see the build is passing now! Ready for review?

Yeh :)

**Review by jeromelaban — APPROVED** [review]
Thanks a lot for your work! Very good PR :)

**Pull request merged**
