### PR TITLE
fix: `AutoSuggestBox` behavior improvements

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

Various features in `AutoSuggestBox` do not behave correctly.

## What is the new behavior?

Adjusted.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by DierkDroth** [comment]
@MartinZikmund is this really going to happen? You're making my day if [this ](https://github.com/unoplatform/uno/issues/9576) would be fixed :-)

**Comment by MartinZikmund** [comment]
> @MartinZikmund is this really going to happen? You're making my day if [this ](https://github.com/unoplatform/uno/issues/9576) would be fixed :-)

Yes please, sorry it took so long, most of the problems should be fixed by this and thd SelectorItem PR 👍 . But it is a tricky control, so if there will be some more strange behavior left, let me know afterwards

**Comment by DierkDroth** [comment]
> > @MartinZikmund is this really going to happen? You're making my day if [this ](https://github.com/unoplatform/uno/issues/9576) would be fixed :-)
> 
> Yes please, sorry it took so long, most of the problems should be fixed by this and thd SelectorItem PR 👍 . But it is a tricky control, so if there will be some more strange behavior left, let me know afterwards

You bet, I will ...

@MartinZikmund thanks again

**Review by Xiaoy312 — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Pull request merged**
