### PR TITLE
feat: Add UI Test template for VSIX

### LINKED ISSUE #3241: [UITesting] Add UI Test project in dotnet new and vsix experiences
## What would you like to be added:

Add a `dotnet new` and VSIX Uno.UITest project experience, using the structure provided by Uno.UITest.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #3241

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

No UI Test template for VSIX

## What is the new behavior?

VSIX has a UI Test template

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Youssef1313** [comment]
Marking as a draft until I get more info on https://github.com/unoplatform/uno/issues/3241#issuecomment-934493428.

**Review by MartinZikmund — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]
Thanks for your contribution!

**Review by agneszitte-nventive — APPROVED** [review]

**Comment by agneszitte-nventive** [comment]
@Youssef1313 can you take a look at the conflicts for your PR please ;) ?

**Comment by Youssef1313** [comment]
Thanks for the ping @agneszitte-nventive. I fixed the conflict, and this is now green :) 🎉

**Comment by jeromelaban** [comment]
Thanks!!

**Pull request merged**
