### PR TITLE
[Templates] Reduced the list of dependencies in .vsconfig to only required Visual Studio components

### LINKED ISSUE #6135: .vsconfig of template requires to install unnecessary stuff
## Current behavior

https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.vsconfig has a lot of unnecessary components and workloads.

Which causes Visual Studio to open a prompt to install them on any new solution creation.

## Expected behavior

As long as this list is enough for Elmish.Uno setup
``` JSON
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.VisualStudio.Workload.NetCrossPlat",
    "Microsoft.VisualStudio.Workload.NetWeb",
    "Microsoft.VisualStudio.Workload.ManagedDesktop",
    "Microsoft.VisualStudio.Workload.Universal",
    "Microsoft.Component.MSBuild",
    "Microsoft.Component.NetFX.Native",
    "Microsoft.ComponentGroup.Blend",
    "Microsoft.NetCore.Component.Runtime.5.0",
    "Microsoft.NetCore.Component.Runtime.3.1",
    "Microsoft.NetCore.Component.DevelopmentTools",
    "Microsoft.NetCore.Component.SDK",
    "Microsoft.NetCore.Component.Web",
    "Microsoft.Net.Component.4.8.SDK",
    "Microsoft.Net.Component.4.8.TargetingPack",
    "Microsoft.Net.ComponentGroup.4.8.DeveloperTools",
    "Microsoft.Net.ComponentGroup.DevelopmentPrerequisites",
    "Microsoft.VisualStudio.ComponentGroup.Web",
    "Microsoft.VisualStudio.ComponentGroup.Web.Client",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions",
    "Microsoft.VisualStudio.Component.AppInsights.Tools",
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Component.Debugger.JustInTime",
    "Microsoft.VisualStudio.Component.DiagnosticTools",
    "Microsoft.VisualStudio.Component.FSharp",
    "Microsoft.VisualStudio.Component.Graphics",
    "Microsoft.VisualStudio.Component.IISExpress",
    "Microsoft.VisualStudio.Component.IntelliCode",
    "Microsoft.VisualStudio.Component.IntelliTrace.FrontEnd",
    "Microsoft.VisualStudio.Component.JavaScript.Diagnostics",
    "Microsoft.VisualStudio.Component.LiveUnitTesting",
    "Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites",
    "Microsoft.VisualStudio.Component.ManagedDesktop.Core",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.VisualStudio.Component.Roslyn.LanguageServices",
    "Microsoft.VisualStudio.Component.NuGet",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.Web",
    "Microsoft.VisualStudio.Component.WebDeploy",
    "Microsoft.VisualStudio.Component.Windows10SDK.19041",
    "Microsoft.VisualStudio.Component.Windows10SDK.18362",
    "Microsoft.VisualStudio.ComponentGroup.MSIX.Packaging",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.TemplateEngine",
    "Microsoft.VisualStudio.ComponentGroup.UWP.NetCoreAndStandard",
    "Microsoft.VisualStudio.ComponentGroup.UWP.Xamarin",
    "Microsoft.VisualStudio.ComponentGroup.UWP.Support",
    "Microsoft.VisualStudio.Component.MonoDebugger",
    "Microsoft.VisualStudio.Component.Merq",
    "Component.Microsoft.Web.LibraryManager",
    "Component.OpenJDK",
    "Component.Xamarin",
    "Component.Xamarin.RemotedSimulator",
    "Component.Android.SDK30",
  ]
}
```
The same list without F# will be pretty enough for Uno.

## How to reproduce it (as minimally and precisely as possible)

1. Create a solution from the template.
2. Open in Visual Studio without Azure workload or some other workload or component that is not present in the current template.
3. See a prompt to install lots of components

## Workaround

Unknown

## Environment

Nuget Package:
- Uno.ProjectTemplates.Dotnet

Nuget Package Version(s):

Affected platform(s):
- Solution Templates

IDE:

-  Visual Studio 2019 (version: 16.10)

### PR DESCRIPTION
**Pull request by xperiandri**
for Xamarin and MAUI templates.
All the dependencies are sorted.
Descrition is here https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022

GitHub Issue (If applicable): closes #6135 

## PR Type

What kind of change does this PR introduce?
- Refactoring (no functional changes, no api changes)

## What is the current behavior?

Proposes to installs unnecessary stuff.
Annoys with an unnecessary notification.

## What is the new behavior?

Installs only required stuff.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by xperiandri** [comment]
@jeromelaban as I understand, nothing additional is required for WinUI.
Even without this item in Desktop development workload it will work
image
Looks like everything is inside Windows App SDK NuGet package

 Do you know?

**Comment by xperiandri** [comment]
So that we can copy these same .vsconfigs to WinUI templates

**Comment by jeromelaban** [comment]
Nothing's required indeed, not for now at least. The only part is that the vsconfig has been updated to include maui dependencies, so it's not a drop-in replacement.

**Comment by xperiandri** [comment]
Then I just replaced corresponding `.vsconfig` files.
What about `unoapp-prism` and `unoapp-uitest`
I suppose `unoapp-prism` is like `unoapp` don't it?
And does `unoapp-uitest` require anything special?

**Review by jeromelaban — APPROVED** [review]
Thanks for your contribution!

**Comment by xperiandri** [comment]
Cool, all the checks passed

**Pull request merged**
