### PR TITLE
fix: Match FrameworkElement.[Measure|Arrange]Override with Windows

### LINKED ISSUE #1554: FrameworkElement default Measure/Arrange override imeplementation
## Current behavior
If you create a `Panel` which arrange all its items and then invoke `base.ArrangeOverride(finalSize)` the first item is re-arranged stretched, while on windows it seems to do nothings.

## Expected behavior
The arranged items are not re-arranged ...

**BUT**

It seems that on UWP you can invoke the base to arrange items (for instance if you only alter the `finalSize` and call the base, it seems that all items are arranged properly)

## How to reproduce it (as minimally and precisely as possible)
Cf. the (private) issue attached in the conversation thread below

## Environment
Nuget Package: Uno.UI
Package Version(s): 1.46
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_
Relevant plugins: _none_

See #97

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #1554

## PR Type

What kind of change does this PR introduce?

### <samp>🤖 Generated by Copilot at 2b75eac</samp>

This pull request refactors the layout logic for `FrameworkElement` and its subclasses by introducing helper methods to measure and arrange the first child element, and by returning the default size in the base `FrameworkElement` methods. This simplifies the code and improves the consistency with the WinUI behavior. The pull request also adds the necessary assembly attributes and using directives to support the media player implementations.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Youssef1313** [comment]
@jeromelaban Is this good to merge?

**Comment by jeromelaban** [comment]
I don't know yet if it is, this is a significant change that needs screenshot validations. Did you check those as well?

**Comment by Youssef1313** [comment]
Yup I checked screenshot comparison a while ago when I have opened the PR. Nothing was looking interesting there.

Note that a behavior change here can only happen for classes that inherit from `FrameworkElement` but not from `Control`. That is why I added few more `MeasureOverride` and `ArrangeOverride` to maintain the existing behavior for those classes, and for other cases avoiding `base.[MeasureOverride|ArrangeOverride]` calls where `base` is referring to `FrameworkElement`.

**Comment by jeromelaban** [comment]
Ok, let's merge as-is, though we'll need to validate the behavior a bit more with the deployed samples app.

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
