### PR TITLE
fix: Avoid disabling Paint AntiAlias when drawing rounded corners

### PR DESCRIPTION
**Pull request by kazo0**
closes https://github.com/unoplatform/uno/issues/8324

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?

image

## What is the new behavior?

image

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Comment by jeromelaban** [comment]
I think we should be adding a test that validates if there are non-plain colors caused by the aliasing. I think the image test helpers can do that.

**Review by ajpinedam — APPROVED** [review]
This is a good finding! 🔥

**Comment by kazo0** [comment]
> I think we should be adding a test that validates if there are non-plain colors caused by the aliasing. I think the image test helpers can do that.

@jeromelaban I'm not sure I understand, by non-plain color you mean we just have something like a White background and a Red border and if we detect any pixels that are not White and not full red (255,0,0) then we assume there is anti-aliasing?

**Comment by jeromelaban** [comment]
I think we should be adding a test that validates if there are non-plain colors caused by the aliasing. I think the image test helpers can do that.

> 

Something like this, yes :)

**Pull request merged**
