### PR TITLE
fix(contentdialog): Do not close popups once filepicker appear.

### PR DESCRIPTION
**Pull request by matizk144**
FilePicker call activity OnPause() method which close aby popups.

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?

Currently opening filepicker from ContentDialog control close ContentDialog control before filepicker appear.
Opening native FilePicker in Android call *OnPause()* method in *ApplicationActivity* which close any popups.

## What is the new behavior?

When System call *OnPause()* method, application don't close any popups. Going forward, opening native FilePicker from ContentDialog allow user to select file, then back to opened ContentDialog (return control) for next steps to do.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for your contribution!

This is potentially a behavior breaking change, as this change was originally present to match iOS's behavior when handling getting out of the application.

@MartinZikmund as you're working on file picking, what happens in this case on iOS? Do popups get closed the same way ?

**Comment by matizk144** [comment]
Also I wondered about behaviour to filter out and close **ContentDialog** popups only. But, as you mentioned.. behaviour should be the same on iOS as well.

**Comment by matizk144** [comment]
> Thanks for your contribution!
> 
> This is potentially a behavior breaking change, as this change was originally present to match iOS's behavior when handling getting out of the application.
> 
> @MartinZikmund as you're working on file picking, what happens in this case on iOS? Do popups get closed the same way ?

Hello Jerome,
If you feel, that is breaking change, I propose to prevent closing contentdialog controls only. The same change I could prepare for iOS as well? What you think?

**Comment by MartinZikmund** [comment]
> > Thanks for your contribution!
> > 
> > This is potentially a behavior breaking change, as this change was originally present to match iOS's behavior when handling getting out of the application.
> > 
> > @MartinZikmund as you're working on file picking, what happens in this case on iOS? Do popups get closed the same way ?
> 
> Hello Jerome,
> If you feel, that is breaking change, I propose to prevent closing contentdialog controls only. The same change I could prepare for iOS as well? What you think?

Hey, sorry for my late reply. It would definitely be nice if the `ContentDialogs` could stay open in this case. Especially for iOS it will be needed for the `FileSavePicker` I am currently preparing. Would you be interested in implementing this?

**Comment by matizk144** [comment]
> > > Thanks for your contribution!
> > > This is potentially a behavior breaking change, as this change was originally present to match iOS's behavior when handling getting out of the application.
> > > @MartinZikmund as you're working on file picking, what happens in this case on iOS? Do popups get closed the same way ?
> > 
> > 
> > Hello Jerome,
> > If you feel, that is breaking change, I propose to prevent closing contentdialog controls only. The same change I could prepare for iOS as well? What you think?
> 
> Hey, sorry for my late reply. It would definitely be nice if the `ContentDialogs` could stay open in this case. Especially for iOS it will be needed for the `FileSavePicker` I am currently preparing. Would you be interested in implementing this?

Yes!
I will do in coming days for Android and iOS. Other platforms (desktop) seems it works as expected. I'm going to add this in this PR.

**Comment by MartinZikmund** [comment]
@matizk144 Are you able to get to this PR soon?

**Comment by matizk144** [comment]
> @matizk144 Are you able to get to this PR soon?

Yes, I'll do it in next 2 weeks. I'm on vacation right now.

**Comment by MartinZikmund** [comment]
@matizk144 Enjoy vacation 🏖️ !

**Review by MartinZikmund — APPROVED** [review]

**Comment by jeromelaban** [comment]
For this particular issue, I wonder if we should still close popups if those are native, as they may stay on top?

**Comment by MartinZikmund** [comment]
This was fixed by #11723

**Pull request closed without merging**
