### PR TITLE
feat: Tizen project template

### LINKED ISSUE #4320: Add Tizen dotnet new template

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #4320

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

Tizen template is missing.

## What is the new behavior?

Tizen app template added.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by MartinZikmund** [comment]
@jeromelaban Is there a simple way to test the template "in action"?

**Comment by jeromelaban** [comment]
The best way is to add support for it in the `dotnet new` experience. If you add a template you have to configure it similar to this one: 

https://github.com/unoplatform/uno/blob/fe212bf9e8f717275e0c9b066af5e0196b5f88d8/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json#L162-L169

The template will automatically be built, when adjusting this part : 
https://github.com/unoplatform/uno/blob/ac86cfb32e4c6b0626baca1410eeceafa03a4bf4/build/run-template-tests.ps1#L37

And this part:
https://github.com/unoplatform/uno/blob/ac86cfb32e4c6b0626baca1410eeceafa03a4bf4/build/run-template-tests.ps1#L61

**Comment by MartinZikmund** [comment]
@jeromelaban The project now builds but I get an exception:

```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'sk_version_get_milestone' in shared library 'libSkiaSharp.so'.
   at SkiaSharp.SkiaApi.sk_version_get_milestone()
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKSurface..ctor(IntPtr h, Boolean owns)
   at SkiaSharp.SKSurface.GetObject(IntPtr handle)
   at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes, SKSurfaceReleaseDelegate releaseProc, Object context, SKSurfaceProperties props)
   at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes)
   at SkiaSharp.Views.Tizen.SKCanvasView.OnDrawFrame()
   at SkiaSharp.Views.Tizen.CustomRenderingView.<.ctor>b__4_1(IntPtr d, IntPtr o)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)
   at Uno.UI.Runtime.Skia.TizenHost..ctor(Func`1 appBuilder, String[] args)
   at App7.Skia.Tizen.Program.Main(String[] args) in C:\Users\marti\source\repos\App7\App7\App7.Skia.Tizen\Program.cs:line 10
```

**Comment by MartinZikmund** [comment]
@jeromelaban Seems that if I reference `SkiaSharp.Views` directly from the Tizen projects, things start working as expected. Maybe the package reference can be added to the .csproj for now.

**Comment by MartinZikmund** [comment]
@jeromelaban I have asked Matt Leibowitz about this and here what he found out:
```
<dependency id="SkiaSharp.Views" version="2.80.0" exclude="Build,Analyzers" />
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Uno.UI.Runtime.Skia.Tizen</id>
    <version>3.2.0-dev.441</version>
    <authors>nventive</authors>
    <owners>nventive</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <icon>uno.png</icon>
    <projectUrl>https://github.com/unoplatform/uno</projectUrl>
    <iconUrl>https://nv-assets.azurewebsites.net/logos/uno.png</iconUrl>
    <description>This package provides the platform support for Skia in Uno Platform projects.</description>
    <copyright>nventive</copyright>
    <repository type="git" url="https://github.com/unoplatform/uno" commit="d57b9addd95989bacdf98b61ef1ddde9365800f9" />
    <dependencies>
      <group targetFramework="Tizen5.0">
        <dependency id="Uno.UI" version="3.2.0-dev.441" exclude="Build,Analyzers" />
        <dependency id="SkiaSharp.Views" version="2.80.0" exclude="Build,Analyzers" />
        <dependency id="Tizen.NET" version="5.0.0.14562" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```
> Not sure what other issues are being caused for the other packages
> We add PrivateAssets="none" to our refs for this
> https://github.com/xamarin/AndroidX/blob/master/source/AndroidXProject.cshtml#L193
> AndroidX also had this issue
> I have no idea why "build" is excluded from this by default... it basically means nothing will work

How do the nuspec references get generated, so that the exclude part can be adjusted?

**Comment by jeromelaban** [comment]
The reference is transitive, defined in Uno.Skia. If we want to change the excluded assets, the PackageReference has to be added explicitly in `Uno.UI.Runtime.Skia.Tizen`, so the `ExcludeAssets` attribute can be added by the Pack target.

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
