### PR TITLE
fix(menuflyout): Fix potential NRE on closing Popups

### PR DESCRIPTION
**Pull request by jeromelaban**
GitHub Issue (If applicable): closes https://github.com/unoplatform/Uno.Gallery/issues/939

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the new behavior?

Potential NRE on closing popup if the presenter has been removed.

### <samp>🤖 Generated by Copilot at 60a585f</samp>

Refactor `MenuFlyout` code to use safe cast and null check for presenter. This prevents potential exceptions and improves code quality.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by agneszitte — COMMENTED** [review]
Do you think it is possible to add a test for this?

**Comment by jeromelaban** [comment]
I'm not able to reproduce the condition in the sample app at this time, it could be a scenario specific to the AppBar.

**Review by kazo0 — APPROVED** [review]

**Comment by kazo0** [comment]
Assuming this'll need a backport?

**Comment by jeromelaban** [comment]
@mergify backport release/stable/4.10 legacy/4x

**Pull request merged**
