### PR TITLE
Resource loader now applies encoding to android resource names

### PR DESCRIPTION
**Pull request by consolelogreece**
GitHub Issue (If applicable): #1881

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?

Silent fail when android asset starts with digit.

## What is the new behavior?

Error is now thrown when android asset starts with digit.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

I haven't been able to test this as I'm currently away and using a Linux machine (I don't know how to run it on Linux), so if this is wrong in any way/ I haven't understood the issue please let me know and I'll come back to it on my windows machine

Internal Issue (If applicable):  #1881

### CODE REVIEW

**Comment by consolelogreece** [comment]
Don't merge, will be working on this tomorrow.

**Comment by jeromelaban** [comment]
Thanks @consolelogreece.

Looking further into that issue, it seems that the number parsing is done properly, but the loading is not done properly. It`s been done here: https://github.com/unoplatform/uno/pull/903/files, but the resource loader does not apply the same transformation: 
https://github.com/unoplatform/uno/blob/340848b83fe56832ca847ea63d6ce415297bf170/src/Uno.UI/UI/Xaml/Media/ImageSource.Android.cs#L358

The change should be that the loader applies the same name transforms.

**Comment by jeromelaban** [comment]
@consolelogreece No worries at all! Yes, this is exactly what I meant by this update :) Thank you very much for persisting.

We'd need to add a UI Test to validate that the content is appropriate, by:
- Adding a [number-leading asset here](https://github.com/unoplatform/uno/tree/master/src/SamplesApp/UITests.Shared/Assets)
- And loading [it here](https://github.com/unoplatform/uno/blob/master/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageSourceUrlMsAppxScheme.xaml) so we can see it in the build artifacts and validate that it does not fail.

Also, what issues have you been having when building ? @ghuntley may be interested in capturing that feedback to we can improve the documentation.

**Comment by consolelogreece** [comment]
For some reason I just can't get it to build. I followed the [documentation](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/debugging-uno-ui.md) to the letter. I keep getting errors like this: 

`
Failed to download package 'runtime.win10-x64.Microsoft.Net.Native.Compiler.2.2.3' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.compiler/2.2.3/runtime.win10-x64.microsoft.net.native.compiler.2.2.3.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.compiler/2.2.3/runtime.win10-x64.microsoft.net.native.compiler.2.2.3.nupkg' has timed out after 100000ms.	
`

I've tried uninstalling Visual studio, tried building in both vs 2017 and vs 2019, tried manually updating with dotnet restore/nuget restore, I don't know what else to do. Research has yielded no answers.

**Comment by jeromelaban** [comment]
The nuget issue is most likely transitive, could you try again ?

**Comment by consolelogreece** [comment]
I've retried multiple times to no avail unfortunately. Does the pr not address the issue by the way?

**Comment by jeromelaban** [comment]
This is strange. This looks like a CDN region error for nuget, as the specified URL works elsewhere. 

Yes, the modification looks appropriate, but it needs to be tested.

One thing that you could do to test the modification [is to use the solution filters](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/debugging-uno-ui.md#faster-dev-loop-with-single-target-framework-builds), which will only load the solution for android, and skip the part that does not work for you.

**Pull request closed without merging**
