### PR TITLE
docs: Adujust PasswordVault

### PR DESCRIPTION
**Pull request by snoordman**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?
- Documentation content changes

## What is the current behavior?
loginCredential variable used while vault.Retrieve() is set in the variable credential

## What is the new behavior?
Updated loginCredential to credential

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Comment by morning4coffe-dev** [comment]
Thanks for the PR, @snoordman! Could you update your commit to match the https://www.conventionalcommits.org/en/v1.0.0/#summary

**Review by morning4coffe-dev — APPROVED** [review]

**Comment by MartinZikmund** [comment]
Thank you for the fix! We are using Conventional commits, so can you please reword the commit message to "docs: Adjust PasswordVault" for example? See details here https://www.conventionalcommits.org/en/v1.0.0/ . Here are instructions how to reword the commit https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages

**Comment by snoordman** [comment]
> Thank you for the fix! We are using Conventional commits, so can you please reword the commit message to "docs: Adjust PasswordVault" for example? See details here https://www.conventionalcommits.org/en/v1.0.0/ . Here are instructions how to reword the commit https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages

done

**Review by jeromelaban — APPROVED** [review]
Thank you for your contribution!

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.1

**Pull request merged**
