### PR TITLE
fix(codegen): BindableMetadata properly globalizing generic types

### PR DESCRIPTION
**Pull request by Xiaoy312**
GitHub Issue (If applicable): 
fixes: #2815

## PR Type

What kind of change does this PR introduce?

- Bugfix
- Build or CI related changes

## What is the current behavior?
BindableTypeProvidersSourceGenerator doesn't fully qualify generic type parameter.

## What is the new behavior?
Generic type are fully qualified, including their generic parameters.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks! Could you add a validation sample here: https://github.com/unoplatform/uno/tree/master/src/SourceGenerators/XamlGenerationTests ?

**Comment by Xiaoy312** [comment]
@jeromelaban I've undone my fix and added a failing scenario for the linked issue, but I was not able to get it to fail. It seems that `BindableTypeProvidersSourceGenerator` are not enabled in/called by `XamlGenerationTests`, since there was no such folder under `obj\debug\${target_platform}\g` of the project.

**Comment by jeromelaban** [comment]
@XiaotianNetlift Indeed, then a test can be added as a normal control in the sample app.

**Comment by XiaotianNetlift** [comment]
Test has been included (with the same commit).

**Pull request merged**
