### PR TITLE
Support for VS 16.3 for the Uno.UI solution

### PR DESCRIPTION
**Pull request by jeromelaban**
## PR Type

What kind of change does this PR introduce?
- Build or CI related changes

## What is the new behavior?

Support for VS 16.3 for the Uno.UI solution

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
@jeromelaban I think the same version bump needs to be done here in the library template as well https://github.com/unoplatform/uno/blob/a3e899cfd44b681c53209ff9a1b94faa80b506ea/src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj#L1

**Comment by jeromelaban** [comment]
This PR cannot pass until Linux support is restored in msbuild extras.

**Comment by jeromelaban** [comment]
The issue is pending on https://github.com/onovotny/MSBuildSdkExtras/pull/186

**Pull request merged**
