### PR TITLE
[WIP] feat: Unified splash screen

### LINKED ISSUE #2616: Add cross-platform splash screen to the default project template
## What would you like to be added:

After writing article on setting up splash screens in Uno, I realized, that it could actually be part of the default template with all platforms using the `SplashScreen.scale-200.png`. This way the experience would match UWP from the first moment.

## Why is this needed:

Easy to set up splash screen.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #2616

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

Splash screen is inconsistent out of the box.

## What is the new behavior?

- Consistent splash screen across all platforms in Samples app and Solution template
- Icons for Samples app
- "Uno Samples" name for Samples app

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by MartinZikmund** [comment]
Only thing missing is to actually verify the solution template works correctly (I don't trust the iOS designer :-D)

**Comment by pkar70** [comment]
And maybe some .md file with guide how to use splash screen? (how to convert UWP splash screen to other platform)

**Comment by MartinZikmund** [comment]
> maybe some .md file with guide how to use splash screen would be of great help (how to convert UWP splash screen to other platform)

Yes, good idea, will do that

**Comment by MartinZikmund** [comment]
Closing for now, will need to be re-done

**Pull request closed without merging**
