### PR TITLE
docs: Fix grammar and typos in Uno-UI-Performance

### PR DESCRIPTION
**Pull request by DieserMerlin**
Fixed some grammar errors, added some dots etc.

GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

## What is the new behavior?

Just fixed some grammar issues and added some missing dots.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x ] Validated PR `Screenshots Compare Test Run` results.
- [x ] Contains **NO** breaking changes
- [x ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Review by davidjohnoliver — APPROVED** [review]
Thanks for your contribution!

**Comment by davidjohnoliver** [comment]
@DieserMerlin The commit needs to be in the [Conventional Commits format](https://platform.uno/docs/articles/uno-development/git-conventional-commits.html) for the CI build to pass, eg `docs: Fix grammar and typos in Uno-UI-Performance`

**Comment by DieserMerlin** [comment]
Sorry, I changed the title of my PR

**Comment by robloo** [comment]
> Sorry, I changed the title of my PR

You'll have to change the commit message itself. This should be easy using:
 * `git commit --amend -m "docs: Fix grammar and typos in Uno-UI-Performance"`
 * You likely need to force push the change to the feature branch after 

In other cases you would need `git rebase`

**Pull request merged**
