### PR TITLE
feat: Add a simple XAML Playground sample

### PR DESCRIPTION
**Pull request by jeromelaban**
## PR Type

What kind of change does this PR introduce?
- Feature

## What is the new behavior?

Add a simple XAML playground to allow for quick testing of custom scenarios directly in the sample app when validating PRs.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
@jeromelaban I made a few improvements:

- Enabled on non wasm via plain `TextBox`
- Made Playground the "welcome" page
- Added shortcut to playground
- Saving the content when run sample is clicked

**Review by MartinZikmund — APPROVED** [review]

**Comment by ramezgerges** [comment]
@jeromelaban I've swapped out the variable CascadiaCode font file with the Regular-only verion. This is due to #13725 which is mostly a skia problem (although I suspect I may find a workaround in the future).

**Comment by jeromelaban** [comment]
@MartinZikmund it does not look like the change is working (at least when run from the staging site). Is it working locally for you?

**Pull request merged**
