### PR TITLE
fix(templates): Fix XAML conditional for Wasm and Skia

### LINKED ISSUE #11282: The new templates broke conditional xaml
### Current behavior

The new templates use a class library, and when it's compiled for net7.0, we don't know if it's skia or wasm and conditional xaml for those don't work. However, conditional xaml should work on Android/iOS/macOS since they can be determined from `TargetFramework` (I have only tried Wasm and Skia though)

Conditional XAML is supposed to work per the value of `XamarinProjectType` which is set here:

https://github.com/unoplatform/uno/blob/a6eda7c5d1ab8d2b34cfc443fbd54e9432b8cf16/src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props#L71-L72

The XAML file is processed in the classlib which doesn't know `UnoRuntimeIdentifier` (in fact, if the classlib is built for net7.0, the output is cached for both wasm and skia since both are net7.0)

### Expected behavior

Conditional xaml should work the same as before with the shared project.

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

I have tried a little trick but it **didn't work**, though I thought it's worth mentioning.

In `Skia.Gtk.csproj`, reference the classlib as follows:

(Note: The same will be done for all other projects - but I was testing only for Skia to get something working first)

```xml
  <ItemGroup>
    <ProjectReference Include="..\ProjectName\ProjectName.csproj">
      <SetTargetFramework>TargetFrameworks=$(TargetFramework)</SetTargetFramework>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
      <Properties>XamarinProjectType=$(XamarinProjectType)</Properties>
    </ProjectReference>
  </ItemGroup>
```

Then in the classlib, to avoid a `GetTargetPath` error from MSBuild, I removed all the `TargetFrameworks` properties and replaced it with just `<TargetFramework>net7.0</TargetFramework>`.

**This unfortunately didn't work.**

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #11282

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
This is an interesting idea, but this is likely to cause issues at multiple levels, namely for nuget, but also for msbuild itself:

```
11:26:04:877	3>c:\vs\odd\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1830,5): error : Project '..\..\ClassLibrary2\ClassLibrary2.csproj' targets 'net7.0-wasm1.0;net7.0-skia1.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v7.0'.
```

**Comment by Youssef1313** [comment]
@jeromelaban I'm not sure how I can reproduce this error. Any steps to repro?

**Comment by Youssef1313** [comment]
> This is an interesting idea, but this is likely to cause issues at multiple levels, namely for nuget, but also for msbuild itself:
> 
> ```
> 11:26:04:877	3>c:\vs\odd\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1830,5): error : Project '..\..\ClassLibrary2\ClassLibrary2.csproj' targets 'net7.0-wasm1.0;net7.0-skia1.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v7.0'.
> ```

This error seems to indicate that `ClassLibrary2.csproj` doesn't have a `net7.0` target, while the template is "supposed" to have it. Am I missing something?

**Comment by jeromelaban** [comment]
That was indeed the problem. This still needs a lot more testing with the many parts of the pipeline.

**Comment by Youssef1313** [comment]
@jeromelaban Anything I need to do on my end?

**Comment by jeromelaban** [comment]
Yes, we need to work more on the downstream effects of such a template change, particularly when dealing with nuget packages. Most of the changes you made should also be in uno's targets, not in the project templates.

**Comment by jeromelaban** [comment]
This will be addressed implicitly by the inclusion of `net8.0-browser`.

**Pull request closed without merging**
