### PR TITLE
fix: Always activate window on `Activate()`

### LINKED ISSUE #18620: `Window.Activate()` should bring the window in front
### Current behavior

Using `-desktop` `Window.Activate()` currently does bring the window in front on Windows, but does not on Linux and macOS.

### Expected behavior

`Window.Activate()` brings the window in front.

### NuGet package version(s)

5.6.0-dev.252

### Affected platforms

Skia (Linux X11), Skia (macOS)

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #18620

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

Activate does not actually activate the window if not shown yet.

## What is the new behavior?

Activated.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]

**Review by ajpinedam — APPROVED** [review]

**Review by spouliot — APPROVED** [review]

**Comment by MartinZikmund** [comment]
@spouliot I am seeing this in macOS runtime tests after my changes, which is very odd:

image

I can't see a way for it to get into this infinite loop, as `CloseCore` on macOS does not call any managed code, unless I am missing something 👀 . Trying to run the windowing runtime tests locally seems to work ok too, so not sure what could be the difference

**Comment by spouliot** [comment]
@MartinZikmund there are 2 callbacks (native code calling back to managed code) in `UIWindow.m`

* uno_get_window_should_close_callback
* uno_get_window_close_callback

They map to code inside `Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs`

* https://github.com/unoplatform/uno/blob/46b77257597437ac8690015e584a8a9bc398d2fb/src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs#L506
* https://github.com/unoplatform/uno/blob/46b77257597437ac8690015e584a8a9bc398d2fb/src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs#L525

Maybe one of them is causing the recursion ?

I'll have a look later today...

**Comment by spouliot** [comment]
The stack trace mention `Uno.UI.RuntimeTests.Tests.BindingTests.When_XBind_In_Window()` but I don't get the problem when I run that runtime test on your branch.

Is there a specific way to trigger this ?

**Comment by MartinZikmund** [comment]
@spouliot exactly, I can't reproduce it locally, and looking at the changes don't see a significant difference between the code before and after my PR 🤔 ...

**Pull request merged**
