### PR TITLE
draft

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Youssef1313** [comment]
@jeromelaban CAn you restart the CI here please?

**Comment by jeromelaban** [comment]
The problem here is that if there are two types with the same name in different assemblies, there may be a clash. It's not something we validate inside uno.

**Comment by Youssef1313** [comment]
@jeromelaban If they are in different assemblies, that should be different compilations too? What's the problem if the same name is used across different compilations?

**Comment by jeromelaban** [comment]
The problem here is disambiguation of the same FullName in different assemblies, but in the same compilation.

**Comment by Youssef1313** [comment]
@jeromelaban I'm not following with that. We generate code for symbols that are declared in source, shouldn't they all have the same assembly, specifically, it's [`compilation.Assembly`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.assembly?view=roslyn-dotnet-4.3.0#microsoft-codeanalysis-compilation-assembly). If a symbol doesn't belong to `compilation.Assembly`, I think we will never generate code for it.

**Comment by jeromelaban** [comment]
> @jeromelaban I'm not following with that. We generate code for symbols that are declared in source, shouldn't they all have the same assembly, specifically, it's [`compilation.Assembly`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.assembly?view=roslyn-dotnet-4.3.0#microsoft-codeanalysis-compilation-assembly). If a symbol doesn't belong to `compilation.Assembly`, I think we will never generate code for it.

That's fair, I had in mind that the original use was for symbols coming from other assemblies, but this is not the case anymore. Maybe it should be renamed to `GetGeneratedFileNameHint()` or something to make it clear, or removed altogether and used inline.

**Comment by jeromelaban** [comment]
@Youssef1313 still needed?

**Pull request closed without merging**
