### PR TITLE
docs: Update for "How to use Uno.Material" 

### LINKED ISSUE #8475: "How to use Uno.Material" documentation is out of date
## On which page?
https://platform.uno/docs/articles/guides/uno-material-walkthrough.html

## What's wrong?

Step 2 within the "Section 2: Using Uno.Material library" section makes reference to Chip/ChipGroup/Card/Divider which have now all been moved to the Uno.Toolkit.UI.Material package.

These changes will also need to be reflected in the referenced UnoMaterialSample, an issue tracking the needed changes for the sample is here: https://github.com/unoplatform/Uno.Samples/issues/90

### PR DESCRIPTION
**Pull request by DavidPerikala**
GitHub Issue (If applicable): closes #8475

## PR Type

What kind of change does this PR introduce?

Documentation content changes

## What is the current behavior?

Documentation under How to use Uno.Material -> "Section 2: Using Uno.Material library" section makes reference to Chip/ChipGroup/Card/Divider which have now all been moved to the Uno.Toolkit.UI.Material package

## What is the new behavior?

Documentation reflects the updated package and the usages. 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Comment by MartinZikmund** [comment]
Thanks a lot for the PR! Two things are needed to merge it:

1. Reword the commit to use conventional commits message syntax: "docs: Update for How to Use Uno.Material" (you will need to force push the reword)
2. Sign the CLA (there is a link to that above)

**Comment by DavidPerikala** [comment]
Done, Thank you. 
Have accepted the CLA, but it's doesn't update. Am I missing anything?

**Comment by MartinZikmund** [comment]
@DavidPerikala thanks, merged successfully! Congratulations on your first PR!

**Comment by DavidPerikala** [comment]
Thank you @MartinZikmund. Happy to help!

**Pull request merged**
