### PR TITLE
fix: Adjust the default icon scale

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
TODO: The default should probably be platform-specific?

On Windows 1.0 generally makes the most sense, as otherwise the icon is barely visible on the taskbar

**Review by morning4coffe-dev — COMMENTED** [review]
I agree we should make this platform-specific. This fix is very nice for Windows, but I think it will break on other platforms now.

**Comment by jeromelaban** [comment]
@MartinZikmund should we make the value platform specific? At runtime maybe?

**Comment by MartinZikmund** [comment]
That's what I want to do - I just need to debug what the default should be on each target based on how a icon that stretches toward the edge of the bounds will look like.

**Review by Youssef1313 — APPROVED** [review]

**Pull request merged**
