### PR TITLE
fix(navview): reflect changes when NavigationViewItem.MenuItems changes

### LINKED ISSUE #15608: `NavigationView` `MenuItems` not refreshing correctly on iOS or Android
### Current behavior

On Windows i can change the menu items and the UI reflects these changes. with the same code they do not get updated on iOS or Android.  Attached is a small repro of the issue.  When runnin on any platform, open the Level 1 menu to show the sub menu items, then click Add item to home, it will add a new item to the list (works on windows) and then you can click Clear items from home (works on windows) both of these do not work on iOS or Android.

[NavigationViewTest.zip](https://github.com/unoplatform/uno/files/14381651/NavigationViewTest.zip)

### Expected behavior

I would expect the iOS and Android menus items to reflect the changes like they do in windows

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

None that i can find at this point

### Works on UWP/WinUI

Yes

### Environment

Other

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

Visual Studio 2022, Visual Studio Code, Rider macOS

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by ramezgerges**
GitHub Issue (If applicable): closes #15608

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]
🚀

**Comment by ramezgerges** [comment]
The fix is failing on android for some reason. I compared the stack traces between skia and Android and everything is identical. The problem is that the native `AddViewFast` call fails when trying to add a `NavigationViewItem` inside the `ItemsRepeater`. I couldn't investigate further.

**Comment by MartinZikmund** [comment]
It seems the WASM failures are unrelated? Maybe we can rebase on latest master

**Comment by Youssef1313** [comment]
@MartinZikmund Yup it's a CI fluke.

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.3

**Pull request merged**
