### PR TITLE
New docs styling

### PR DESCRIPTION
**Pull request by mcereda95**
## PR Type

The new style for docfx is fixed after the rebase

## What is the current behavior?

after the rebase, the new style was broken: navbar, sidebar and some fonts were no longer working

## What is the new behavior?

the issues have been fixed and the new design matches the figma file

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 9258a87</samp>

This pull request updates the documentation website of Uno Platform to improve its appearance and responsiveness on different devices. It modifies the styles and scripts of various components, such as the navbar, the side navigation, and the title section. It also switches to the `dart-sass` implementation of the `sass` module for better compatibility and performance.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
NA

Internal Issue (If applicable):
https://dev.azure.com/nventive/UNO%20Marketing/_workitems/edit/280519

### CODE REVIEW

**Comment by mcereda95** [comment]
I add a new commit because I noticed during the QA that navbar was scrollable in certain window size 
image

**Review by MartinZikmund — APPROVED** [review]

**Comment by nickrandolph** [comment]
Not enough spacing between menu items
image

**Comment by MartinZikmund** [comment]
Would it make sense to merge this as first step and do the next updates one by one? To me it feels this already is a huge step forward, even though I have quite many additional comments next, but this as the first step would already make big UX improvement

**Comment by MartinZikmund** [comment]
The default view is very odd on mobile:

image

One would intuitively press the hamburger menu, which is instead the menu for the whole website. 

Then there is the block with just "Overview" there - user has no idea what it is referring to.

Then only below it is a "button" that opens the ToC - which does not immediately look clickable. Compare this to Auth0 docs for example:

image

They ditch the "common header" of the website in favor of purely docs specific header, where the hamburger menu **is** the TOC.

**Comment by morning4coffe-dev** [comment]
I think we should not hide the "In this article" on mobile. I like how MS docs does this, they put it on the top of the article, so the user is able to quicky see what is the article about and jump where they want to go.
image

**Comment by morning4coffe-dev** [comment]
> Not enough spacing between menu items image

I second this a lot. I know it won't be easy, but we should also support something like, for example, GitHub does. When you open it on a device with a detachable keyboard, they make the menu items bigger. I think this would also improve the navigation greatly on mobile.

**Comment by morning4coffe-dev** [comment]
This looks a little weird on mobile, when it's too long. I think it should collapse the first few items 
image
I have something like this in mind:
image

**Comment by morning4coffe-dev** [comment]
Corner radius on the bottom, but not on the top element 😁 
image

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.0

**Pull request merged**
