### PR TITLE
build: Enable nullable by default (auto-generated commit)

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9964

This PR is quite large but is automated. So I thought the automation could be reviewed for correctness and we get things done quickly in a single PR.

Otherwise, I'll have to keep adding `<Nullable>enable</Nullable>` to individual projects and then move to Directory.Build.props after we finish all projects. This will also be a slower progress for this task.

Code I used to generate the first commit:

```csharp
using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

var files = Directory.GetFiles(@"C:\Users\PC\Desktop\uno\src\", "*.cs", SearchOption.AllDirectories);
foreach (var file in files)
{
    if (file.Contains("\\Generated\\") || file.Contains("\\src\\SolutionTemplate\\") || file.Contains("\\src\\UnoItemTemplate\\"))
    {
        continue;
    }

    var isNullableEnabled = file.Contains(@"\src\SamplesApp\UnoIslands.WinForms\") || file.Contains(@"src\Uno.XamlTrimmingValidator\") || file.Contains(@"src\SourceGenerators\Uno.UI.SourceGenerators.Tests\") ||
        file.Contains(@"\src\Uno.UI.Runtime.Skia.Linux.FrameBuffer\") || file.Contains(@"\src\AddIns\Uno.UI.Lottie\") || file.Contains(@"src\Uno.Docs.InlineTOCGenerator") || file.Contains(@"src\SourceGenerators\Uno.UI.SourceGenerators.net6.Tests\");
    var text = File.ReadAllText(file);
    Debug.Assert(!text.Contains("#if true || "));
    var compilationUnit = SyntaxFactory.ParseCompilationUnit(text.Replace("#if", "#if true || "));
    if (compilationUnit.Members.Count == 0)
    {
        continue;
    }

    var firstMemberToken = compilationUnit.Members[0].GetFirstToken();
    var currentToken = compilationUnit.GetFirstToken();
    var foundNullable = false;
    while (true)
    {
        // If #nullable enable is found, remove it
        // If #nullable disable is found, keep it.
        // If nothing is found, depends on the default for the project.

        if (currentToken.GetAllTrivia().Any(t => t.IsKind(SyntaxKind.NullableDirectiveTrivia)))
        {
            foundNullable = true;
            var nullableTrivia = (NullableDirectiveTriviaSyntax)currentToken.GetAllTrivia().ToArray().First(t => t.IsKind(SyntaxKind.NullableDirectiveTrivia)).GetStructure();
            if (nullableTrivia.SettingToken.IsKind(SyntaxKind.EnableKeyword))
            {
                // remove #nullable enable because it's the default.
                var newToken = currentToken.WithLeadingTrivia(FilterTrivia(currentToken.LeadingTrivia)).WithTrailingTrivia(FilterTrivia(currentToken.TrailingTrivia));
                var newCompilationUnit = compilationUnit.ReplaceToken(currentToken, newToken);
                File.WriteAllText(file, newCompilationUnit.ToFullString().Replace("#if true || ", "#if"));
            }
            else if (nullableTrivia.SettingToken.IsKind(SyntaxKind.DisableKeyword))
            {
                // Keep any existing #nullable disable.
            }
            else
            {
                throw new Exception("We shouldn't get here.");
            }
        }

        if (currentToken == firstMemberToken)
        {
            break;
        }

        currentToken = currentToken.GetNextToken(includeDirectives: true);
    }

    if (!foundNullable && !isNullableEnabled)
    {
        File.WriteAllText(file, "#nullable disable\r\n\r\n" + compilationUnit.ToFullString().Replace("#if true || ", "#if"));
    }
}

static IEnumerable<SyntaxTrivia> FilterTrivia(SyntaxTriviaList list)
{
    int i = 0;
    while (i < list.Count)
    {
        var trivia = list[i];
        if (trivia.IsKind(SyntaxKind.NullableDirectiveTrivia))
        {
            while (++i < list.Count && list[i].IsKind(SyntaxKind.EndOfLineTrivia))
            {
            }
        }
        else
        {
            i++;
            yield return trivia;
        }
    }
}
```

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Youssef1313** [comment]
I'll fix the failures soon.

**Comment by Youssef1313** [comment]
@jeromelaban Could you take a look please?

**Comment by jeromelaban** [comment]
Thanks for the PR. The changes are structurally ok and there are two things to change:
- You changed the encoding in many files (the UTF8 BOM was removed)
- The API sync generator should be changed to include the `#nullable disable`. The WinUI build re-generates the files at each build, and it's curious that it's not failing in some way as a result.

**Comment by Youssef1313** [comment]
@jeromelaban Generated files are nullable-disabled by default :)

**Comment by Youssef1313** [comment]
> * You changed the encoding in many files (the UTF8 BOM was removed)

I'll take a look at this one.

**Comment by jeromelaban** [comment]
> @jeromelaban Generated files are nullable-disabled by default :)

These are not actual "source generators" generated files, how come they are nullable disabled by default?

**Comment by jeromelaban** [comment]
> We set that in editorconfig:

Missed that bit, thanks!

**Comment by Youssef1313** [comment]
@jeromelaban Is this good now?

**Comment by jeromelaban** [comment]
Almost. just a few merge conflicts, and we're good.

**Comment by jeromelaban** [comment]
I think it's looking good now, thanks!

**Review by jeromelaban — APPROVED** [review]

**Comment by Youssef1313** [comment]
@jeromelaban This is green now. Hopefully it's ready to merge

**Comment by Youssef1313** [comment]
@jeromelaban Can we merge this please? Thanks!

**Comment by jeromelaban** [comment]
There are a few conflicts since the recent updates.

**Pull request closed without merging**
