### PR TITLE
Fix for nav menu in doc

### PR DESCRIPTION
**Pull request by nv-jbleau**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by feverxdreams — APPROVED** [review]

**Review by nv-ksavaria — APPROVED** [review]

**Review by LHuss — APPROVED** [review]

**Comment by jeromelaban** [comment]
Could you include a screenshot of the behavior for this change ? It'll be easier to track in the future. Thanks !

**Comment by nv-jbleau** [comment]
@jeromelaban like this ? 
image

**Comment by jeromelaban** [comment]
And the screenshot before, to show what's been fixed, if it's visible. Thanks !

**Comment by nv-jbleau** [comment]
@jeromelaban  and here is before fix 
image

**Review by jeromelaban — APPROVED** [review]
Thanks !

**Pull request merged**
