### PR TITLE
refactor: Remove `HAS_EXPENSIVE_TRYFINALLY`

### LINKED ISSUE #11977: Cleanup `HAS_EXPENSIVE_TRYFINALLY` once we move to .NET 7+
https://github.com/dotnet/runtime/issues/50783 was fixed in .NET 7 and later.

Once we build only against .NET 7+, we should clean it up.

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #11977

## PR Type

What kind of change does this PR introduce?

### <samp>🤖 Generated by Copilot at 136d5fa</samp>

This pull request removes obsolete code and simplifies the implementation of various UI controls and data binding classes by removing conditional compilation directives and unnecessary logic that were used to work around a WebAssembly performance issue with try/finally blocks. The issue has been fixed by the runtime, so the code can be unified and optimized across different platforms. The affected files include `BindingExpression.cs`, `Frame.cs`, `Grid.cs`, `Slider.mux.cs`, `TextBlock.cs`, `TextBox.cs`, `DependencyObjectStore.Binder.cs`, `DependencyObjectStore.cs`, `ElementStub.cs`, `FrameworkTemplate.cs`, `ResourceDictionary.cs`, `Style.cs`, `VisualStateGroup.cs`, `DefaultArrayPoolBucket.cs`, `BindingPath.BindingItem.cs`, `ItemsControl.cs`, and `FrameworkElement.cs`.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
With this done, can we also remove `AggressiveInlining` like these? @jeromelaban @Youssef1313 

https://github.com/unoplatform/uno/blob/410c4f3c912252f4a706e764da3e453d43a53de9/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs#L1356-L1361

**Review by jeromelaban — APPROVED** [review]
Looks good. We'll need to make some validations to ensure that there's no additional perf issues that come up as a result of this change.

There are a few other locations where we used while(movenext) because of this specific issue that could also be changed back, but those are not behavior changing, just harder to read.

**Comment by Youssef1313** [comment]
> With this done, can we also remove `AggressiveInlining` like these? @jeromelaban @Youssef1313
> 
> https://github.com/unoplatform/uno/blob/410c4f3c912252f4a706e764da3e453d43a53de9/src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs#L1356-L1361

@MartinZikmund I think no. Instead, we should actually combine the `InnerXYZ` (e.g, InnerArrangeOverride) methods with the `XYZ` (e.g, ArrangeOverride) methods so that they are a single method.

**Comment by Youssef1313** [comment]
> We'll need to make some validations to ensure that there's no additional perf issues that come up as a result of this change.

@jeromelaban When will we be able to confirm that this doesn't cause any performance regressions? We can do further cleanup once this is confirmed.

**Comment by jeromelaban** [comment]
@Youssef1313 The gallery is a good app to validate this, though with such a change there's a need to re-create an AOT profile and profile the app again.

**Pull request merged**
