### PR TITLE
fix(menuflyout): Ensure MenuFlyout nested submenus stay on screen

### LINKED ISSUE #6928: [Wasm]: `MenuFlyoutSubItem` opens in the wrong direction for the second and subsequent opens
### Current behavior

For the first time the items are opened, it behaves correctly:

image

For the second and subsequent opens, it overflows:

image

### Expected behavior

Subsequent opens should behave the same as the first one.

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#d2c01ca7

### Workaround

_No response_

### Works on UWP/WinUI

Yes

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

WebAssembly

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by davidjohnoliver**
Fix bug where nested submenus could be shown offscreen on the 2nd and later times they appeared.

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5639 , fixes #6928 

## PR Type

- Bugfix

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Does this fix https://github.com/unoplatform/uno/issues/6928 as well?

**Comment by davidjohnoliver** [comment]
> Does this fix #6928 as well?

yes it should, good catch! :)

**Review by carldebilly — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Comment by duke7553** [comment]
@davidjohnoliver Hi David. I was wondering if this work changes the behavior in a way that makes https://github.com/unoplatform/Uno.Gallery/pull/261 unnecessary. Though, I still question the experience nested MenuFlyouts offer on mobile devices.

Totally up to you. Would be willing to close that PR if this one solves it.

**Comment by davidjohnoliver** [comment]
> @davidjohnoliver Hi David. I was wondering if this work changes the behavior in a way that makes [unoplatform/Uno.Gallery#261](https://github.com/unoplatform/Uno.Gallery/pull/261) unnecessary. Though, I still question the experience nested MenuFlyouts offer on mobile devices.
> 
> Totally up to you. Would be willing to close that PR if this one solves it.

Hey Luke, I didn't test locally on Android and iOS, but it's shared code so I assume it's fixed. In that case yes I think you can safely close https://github.com/unoplatform/Uno.Gallery/pull/261 . If you wish, you can wait until @sakshi173 has a chance to verify the fix. :)

**Pull request merged**
