### PR TITLE
docs: Improve the "Using the Uno.Sdk" documentation

### PR DESCRIPTION
**Pull request by agneszitte**
## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## Description

Improve the "Using the Uno.Sdk" documentation

### CODE REVIEW

**Comment by agneszitte** [comment]
@Mergifyio backport release/stable/5.2

**Review by ajpinedam — APPROVED** [review]
Beautiful!

**Review by MartinZikmund — APPROVED** [review]

**Pull request merged**
