### PR TITLE
fix(gtk): Align VirtualKey with WinUI

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

## What is the current behavior?

On Gtk, when keyboard layout is not English (Arabic in my case), pressing Ctrl+V on TextBox does nothing.

The root cause is that we get VirtualKey.None instead of VirtualKey.V

## What is the new behavior?

VirtualKey on Gtk is now aligned with WinUI.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by ramezgerges — APPROVED** [review]

**Review by MartinZikmund — APPROVED** [review]

**Comment by jeromelaban** [comment]
@Youssef1313 did you validate that this still works in WSL?

**Comment by Youssef1313** [comment]
Nope I haven't tested WSL. I'll test 👀

**Comment by ramezgerges** [comment]
I've tested and it works with Arabic and English

**Comment by carldebilly** [comment]
That's an impressive negative contribution ;-)

**Pull request merged**
