### PR TITLE
fix(Skia): [WPF] Issue #7829 SynchronizationContext

### LINKED ISSUE #7829: [Skia][WPF] RenderSize is `[0,0]` when generating the control in the event handler
### Current behavior

Considering a code like this:

```csharp
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            Do();
        }

        async void Do()
        {
            var border = new Border()
            {
                Background = new SolidColorBrush(Windows.UI.Colors.Red),
            };
            GeneratedContent.Children.Add(border);
            await Task.Yield();
            Console.WriteLine(border.RenderSize);
        }
```
If you run the Skia.WPF project, the line: `Console.WriteLine (border.RenderSize);` returns 0,0 in UWP works as expected.

### Expected behavior

Give RenderSize

### How to reproduce it (as minimally and precisely as possible)

- Download [Dispatcher_Issue.zip](https://github.com/unoplatform/uno/files/7874791/Dispatcher_Issue.zip)
- Add breckpoint at line `Console.WriteLine(border.RenderSize);'
- Run in UWP Project
- Click on Generate
- You can see correctly RenderSize
- Run Skia WPF
- Click on Generate
- RenderSize is 0,0

### Workaround

Add the following code at the beginning of the method how to generate the UI:

```csharp
var ctx = new Uno.UI.Dispatching.CoreDispatcherSynchronizationContext(Uno.UI.Dispatching.CoreDispatcher.Main
				, Uno.UI.Dispatching.CoreDispatcherPriority.Normal);
System.Threading.SynchronizationContext.SetSynchronizationContext(ctx);
```

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Tested on `Uno.UI 4.0.11` abd `Uno.UI 4.1.0-dev.324`

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 1.1

### Relevant plugins

_No response_

### Anything else we need to know?

WPF replace CoreDispatcherSynchronizationContext with own DispatcherSynchronizationContext

### PR DESCRIPTION
**Pull request by workgroupengineering**
GitHub Issue (If applicable): closes #7829

## PR Type

What kind of change does this PR introduce?

- Bugfix

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by workgroupengineering** [comment]
Can anyone review this PR?

**Review by jeromelaban — COMMENTED** [review]
I've added this test, which matches what you've mentioned:
image

But it does not seem to ~~reproduce~~ fix the issue, can you validate on your end?

**Comment by workgroupengineering** [comment]
> I've added this test, which matches what you've mentioned: image
> 
> But it does not seem to ~reproduce~ fix the issue, can you validate on your end?

If run in test it works as expected but if run in [Real Test APP](https://github.com/unoplatform/uno/files/7874791/Dispatcher_Issue.zip) the issue is present.  I have tryed with 4.1.0-dev.461.

**Comment by jeromelaban** [comment]
It would be important to understand what's different in the sample app, it's supposed to behavior the same way. Can you add the test in the runtime tests and see what results you're getting ?

**Comment by workgroupengineering** [comment]
> It would be important to understand what's different in the sample app, it's supposed to behavior the same way. Can you add the test in the runtime tests and see what results you're getting ?

I try.

How can I do to indicate that the test must be performed only in wpf?

I need to create a real WPF window and call event a via the window API.

**Comment by jeromelaban** [comment]
The test should theoretically work on all platforms, but if we need to limit it to Skia, we'll be able to. Can you add it and launch a build? We'll see how far it goes :)

**Comment by MartinZikmund** [comment]
@jeromelaban Is there some way to the test could avoid requiring separate runtime test project for WPF specifically 🤔 ? (it does not seem so based on the fact the test needs to access `WpfHost`, but it would be nicer to be able to avoid the additional project.

**Comment by jeromelaban** [comment]
> @jeromelaban Is there some way to the test could avoid requiring separate runtime test project for WPF specifically 🤔 ? (it does not seem so based on the fact the test needs to access `WpfHost`, but it would be nicer to be able to avoid the additional project.

I don't think it's necessary at this point. The test that requires a window to validate, this feels like a too low-level replacement for a UI test engine that would do this in a generic way. 

The solution to override the synchronization context for all event going out seems a bit too wide as well, particularly if it's about events going out of Uno's APIs, for which the entry point is known. Let's change those entry points for now to set the proper synchronization context. We can create a test that uses the new pointer injection to validate that we get the proper synchronization context out inside of uno pointer or generic input handlers.

**Pull request closed without merging**
