### PR TITLE
fix: TextBox.VerticalContentAlignment

### LINKED ISSUE #3481: TextBox content vertical alignement on macOS
## Current behavior

Vertical alignment of `TextBox` text on macOS is not accurately centered.

## Expected behavior

Text should be vertically centered

## How to reproduce it (as minimally and precisely as possible)

https://github.com/MartinZikmund/messages-multiplatform-uno-sample

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

### PR DESCRIPTION
**Pull request by ajpinedam**
GitHub Issue (If applicable): #
closes #3481 

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?
TextBox VerticalContentAlignment is not respected

## What is the new behavior?

TextBox VerticalContentAlignment is set and displayed correctly

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
This was reported as macOS but I was able to reproduce it in other platforms (Android, iOS).

Internal Issue (If applicable):

### CODE REVIEW

**Comment by ajpinedam** [comment]
Tested on the Message App by @MartinZikmund 

messages

**Comment by ajpinedam** [comment]
using different Content Alignments (Top, Bottom, Center):
 
different_aligments

**Review by MartinZikmund — APPROVED** [review]

**Comment by jeromelaban** [comment]
Looks like it changes quite a few screenshots: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=20109&view=logs&j=167da950-bbef-5aad-38a7-6d840ba21545&t=a6c7bcf9-43aa-5935-7f96-f6e803f379db&l=164 Could you validate if any of those are legitimate ?

**Comment by ajpinedam** [comment]
> Looks like it changes quite a few screenshots: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=20109&view=logs&j=167da950-bbef-5aad-38a7-6d840ba21545&t=a6c7bcf9-43aa-5935-7f96-f6e803f379db&l=164 Could you validate if any of those are legitimate ?

@jeromelaban  Is there a way to see the screenshots?

**Comment by ajpinedam** [comment]
> Looks like it changes quite a few screenshots: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=20109&view=logs&j=167da950-bbef-5aad-38a7-6d840ba21545&t=a6c7bcf9-43aa-5935-7f96-f6e803f379db&l=164 Could you validate if any of those are legitimate?

@jeromelaban  I validated a few of the failing screenshots and they are failing because of a different theme:

Default_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name_UITests_Shared_Windows_UI_Xaml_Automation_AutomationProperties_Name

**Review by carldebilly — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Pull request merged**
