### PR TITLE
docs: resolve grammatical and linguistic issues

### PR DESCRIPTION
**Pull request by TheBinitGhimire**
Signed-off-by: Binit Ghimire <thebinitghimire@gmail.com>

GitHub Issue: None

## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

Currently, there are few grammatical and linguistic issues in the _README.md_ file

## What is the new behavior?

I have made changes to fix the existing grammatical and linguistic issues in the file.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Comment by TheBinitGhimire** [comment]
I think this PR needs to go through manual checking since it isn't an update to the code, but instead to the README.md file.

**Comment by ghuntley** [comment]
@all-contributors please add @TheBinitGhimire for docs

**Comment by TheBinitGhimire** [comment]
Hi,

Please let me know if anything needs to be done here from my side!

Looking forward to receive new updates regarding this PR!

Thanks,
Binit Ghimire

**Pull request merged**
