### PR TITLE
fix: NavigationViewItem with empty MenuItems rendering with exception

### PR DESCRIPTION
**Pull request by aesteves900**
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8470

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

When I have a NavigationViewItem with empty menuitems like this:

<muxc:NavigationViewItem x:Name="Views"
                         Content="{x:Bind Vm.Culture.NavItemViews}" 
                         Icon="Repair" 
                         SelectsOnInvoked="False"
                         Visibility="{x:Bind Vm.HasViews, Mode=OneWay}"
                         ToolTipService.ToolTip="{x:Bind Vm.Culture.NavItemViews}" >
    <muxc:NavigationViewItem.MenuItems>
    </muxc:NavigationViewItem.MenuItems>
</muxc:NavigationViewItem>
the following exception occures:

Uno.UI.Dispatching.CoreDispatcher[0]
      Dispatcher unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.UI.Xaml.Controls.NavigationViewItem.PropagateDepthToChildren(Int32 depth)
   at Microsoft.UI.Xaml.Controls.NavigationView.OnRepeaterElementPrepared(ItemsRepeater ir, ItemsRepeaterElementPreparedEventArgs args)
   at Microsoft.UI.Xaml.Controls.NavigationView.OnRepeaterUnoBeforeElementPrepared(ItemsRepeater itemsRepeater, ItemsRepeaterElementPreparedEventArgs args)
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.OnUnoBeforeElementPrepared(UIElement element, Int32 index)
   at Microsoft.UI.Xaml.Controls.ViewManager.GetElementFromElementFactory(Int32 index)
   at Microsoft.UI.Xaml.Controls.ViewManager.GetElement(Int32 index, Boolean forceCreate, Boolean suppressAutoRecycle)
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.GetElementImpl(Int32 index, Boolean forceCreate, Boolean suppressAutoRecycle)
   at Microsoft.UI.Xaml.Controls.RepeaterLayoutContext.GetOrCreateElementAtCore(Int32 index, ElementRealizationOptions options)
   at Microsoft.UI.Xaml.Controls.VirtualizingLayoutContext.GetOrCreateElementAt(Int32 index, ElementRealizationOptions options)
   at Microsoft.UI.Xaml.Controls.ElementManager.EnsureElementRealized(Boolean forward, Int32 dataIndex, String layoutId)
   at Microsoft.UI.Xaml.Controls.FlowLayoutAlgorithm.Generate(GenerateDirection direction, Int32 anchorIndex, Size availableSize, Double minItemSpacing, Double lineSpacing, UInt32 maxItemsPerLine, Boolean disableVirtualization, String layoutId)
   at Microsoft.UI.Xaml.Controls.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, UInt32 maxItemsPerLine, ScrollOrientation orientation, Boolean disableVirtualization, String layoutId)
   at Microsoft.UI.Xaml.Controls.StackLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize)
   at Microsoft.UI.Xaml.Controls.Layout.Measure(LayoutContext context, Size availableSize)
   at Microsoft.UI.Xaml.Controls.ItemsRepeater.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.InnerMeasureCore(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureCore(Size avai

## What is the new behavior?

No exceptions throw.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ x] Validated PR `Screenshots Compare Test Run` results.
- [ x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
@aesteves900 I think the bug is caused by a different code path - your changes are for the `Windows.UI.Xaml.Controls.NavigationView`, but the issue is for the `Microsoft.UI.Xaml.Controls.NavigationView`. Try investigating code in this area - https://github.com/unoplatform/uno/tree/master/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView . As for the problem itself - I think the `NavigationView` collections are initialized properly in the constructor:

https://github.com/unoplatform/uno/blob/5ed2c1091417ca7df2e32172ea05996e5e22ed36/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs#L215-L219

So in this case the problem will be specifically in the `NavigationViewItem`, which however seems to initialize the collection as well. There is a bug however - it uses `List<object>` instead of `ObservableCollection<object>`, so that is one thing that I missed and should be changed:

https://github.com/unoplatform/uno/blob/5ed2c1091417ca7df2e32172ea05996e5e22ed36/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.cs#L73

But that won't fix the problem yet most likely, so try debugging the `PropagateDepthToChildren` method to see where the null reference could occur, ideally by replicating the XAML in the issue and trying it out directly while debugging Uno

**Comment by aesteves900** [comment]
> `PropagateDepthToChildren`

@MartinZikmund , thank you!

I'm following your suggestion to solve the problem in a more deep way.

**Comment by aesteves900** [comment]
> > @aesteves900 I think the bug is caused by a different code path - your changes are for the `Windows.UI.Xaml.Controls.NavigationView`, but the issue is for the `Microsoft.UI.Xaml.Controls.NavigationView`. Try investigating code in this area - https://github.com/unoplatform/uno/tree/master/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView . As for the problem itself - I think the `NavigationView` collections are initialized properly in the constructor:
> > https://github.com/unoplatform/uno/blob/5ed2c1091417ca7df2e32172ea05996e5e22ed36/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs#L215-L219
> > 
> > So in this case the problem will be specifically in the `NavigationViewItem`, which however seems to initialize the collection as well. There is a bug however - it uses `List<object>` instead of `ObservableCollection<object>`, so that is one thing that I missed and should be changed:
> > https://github.com/unoplatform/uno/blob/5ed2c1091417ca7df2e32172ea05996e5e22ed36/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.cs#L73
> > 
> > But that won't fix the problem yet most likely, so try debugging the `PropagateDepthToChildren` method to see where the null reference could occur, ideally by replicating the XAML in the issue and trying it out directly while debugging Uno
> > >  GitHub**[uno/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView at master · unoplatform/uno](https://github.com/unoplatform/uno)**Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - uno/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView at master · unoplatform/uno
> 
> >  GitHub**[uno/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView at master · unoplatform/uno](https://github.com/unoplatform/uno)**Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - uno/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView at master · unoplatform/uno


@MartinZikmund , I followed your suggestion, but I have had no luck. The stack trace has more than 16kb, and looks like a recursive error. Any other clue?

**Comment by MartinZikmund** [comment]
@aesteves900 Have you been able to find some further clues to this?

**Pull request closed without merging**
