### PR TITLE
perf(android): Use specialized code for layout interop

### PR DESCRIPTION
**Pull request by jeromelaban**
GitHub Issue (If applicable): #8597 

## PR Type

What kind of change does this PR introduce?
- Refactoring (no functional changes, no api changes)

## What is the new behavior?

Use slim versions of some highly used android APIs.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
This PR is blocked by https://github.com/dotnet/linker/issues/3112

**Comment by jeromelaban** [comment]
May be retried with .NET 8

**Comment by FrozDark** [comment]
@jeromelaban 
Can it be retried with .NET 8 Preview?

**Comment by jeromelaban** [comment]
@FrozDark I'm not sure we'll be able to, that is unless .NET 7 also contains the fix that blocked this issue.

**Pull request closed without merging**
