### PR TITLE
fix: Make `ContentPropertyAttribute.Name` a field instead of a property

### LINKED ISSUE #10841: `ContentPropertyAttribute.Name` should be a field, not a property, to match Windows
### Current behavior

https://github.com/unoplatform/uno/blob/6f8f11cfede6571f4bb3ff674b40fd8921291f11/src/Uno.UI/UI/Xaml/Markup/ContentPropertyAttribute.cs#L25

### Expected behavior

https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.contentpropertyattribute.name?view=winrt-22621

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #10841

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by MartinZikmund** [comment]
I think this is a potentially breaking change, as some library authors are using this attribute 🤔

**Comment by Youssef1313** [comment]
> I think this is a potentially breaking change, as some library authors are using this attribute 🤔

Yes, but not much of a big deal, I think?

**Comment by MartinZikmund** [comment]
Would rather wait for @jeromelaban for this one, maybe could be done as part of major version bump otherwise

**Comment by jeromelaban** [comment]
@MartinZikmund @Youssef1313 This will be creating a breaking change, we'll need wait for this one.

**Comment by Youssef1313** [comment]
@jeromelaban Let me know when the breaking changes branch is created. Meanwhile, I'll close for now and re-open on the branch when created.

**Pull request closed without merging**
