### PR TITLE
fix: Remove resizetizer target to avoid compiling error #13819

### LINKED ISSUE #13819: Unable to build samples app due to `_AddResizetizerWindowIconExtensions`
### Current behavior

Currently trying to build Samples app for mobile targets fails due to `_AddResizetizerWindowIconExtensions`:

```
The target "_AddResizetizerWindowIconExtensions" does not exist in the project.
```

### Expected behavior

_No response_

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

_No response_

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by mcNets**
GitHub Issue (If applicable): closes #13819

[Unable to build samples app due to _AddResizetizerWindowIconExtensions](https://github.com/unoplatform/uno/issues/13819)

## PR Type 

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

Building Samples app for mobile targets fails due to `_AddResizetizerWindowIconExtensions`

## What is the new behavior?

It builds

### <samp>🤖 Generated by Copilot at 8b1d3eb</samp>

The pull request updates the app icon generation for the SamplesApp.netcoremobile project to use the WinUI single-project feature. This simplifies the project file and aligns it with the `Uno.WinUI.AppManifest` package.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

I removed the current Target

```
	<Target Name="_UnoRemoveGeneratedIcon" 
			BeforeTargets="CoreCompile"
			DependsOnTargets="_AddResizetizerWindowIconExtensions">
		<!-- Remove Uno.Resizetizer generated SetIcon that is compatible only with WinUI -->
		<ItemGroup>
			<Compile Remove="@(_WindowIconExtension)"/>
		</ItemGroup>
	</Target>
```

and the project reference until `_AddResizetizerWindowIconExtensions` is added.

Internal Issue (If applicable):

https://github.com/unoplatform/uno/issues/13819

### CODE REVIEW

**Comment by mcNets** [comment]
I've realized now that there is a second file `mergedstyles.xaml' commited. Should I delete it from the PR?

**Comment by jeromelaban** [comment]
Thanks for looking into it! There's another PR that takes care of it, though: https://github.com/unoplatform/uno/pull/13823

**Comment by mcNets** [comment]
🤷‍♂️
I'll try it again !

**Comment by pictos** [comment]
@jeromelaban can we close this one?

**Pull request closed without merging**
