### PR TITLE
Basic iPadOS mouse support

### LINKED ISSUE #3134: iPadOS mouse events recognized as touch
## Current behavior

Mouse events on iPad are recognized as touch

## Expected behavior

Pointer type should be mouse

## How to reproduce it (as minimally and precisely as possible)

-

## Environment

Nuget Package: latest

Package Version(s): latest

Affected platform(s): 

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): fixes #3134 

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

iPadOS mouse pointer is reported as touch.

## What is the new behavior?

iPadOS mouse pointer is now reported as mouse.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Potentially breaking change - updated the solution template with `UIApplicationSupportsIndirectInputEvents` key in Info.plist - this way mouse is properly reported by the system.

### CODE REVIEW

**Comment by MartinZikmund** [comment]
@dr1rrb Thanks! I will take a look at your suggestions and check 👍

**Comment by MartinZikmund** [comment]
> Great! When I tried I didn't notice that we had to set a property in the app to get the correct type.
> 
> Based on what I saw, none of the following is supported yet, but just in case:
> 
> * If the mouse does supports right click, we should make sure to set properties properly here https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs#L66
> * If we are able to track the mouse even while the button is not pressed, we should update the over visual states of controls. For instance I saw that the `Button` is [not configure to generate them on iOS](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Mixins/iOS/VisualStatesMixins.tt#L6) (I would assume that we can probably just configure the `hasCommonOverState` for the same controls [as WASM](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Mixins/Wasm/VisualStatesMixins.tt))
> * On same hypothesis, we probably have to update the hooks to get all the events https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs#L70

Alright, I checked :-D . 

- Right-click is "somehow" supported, but currently, it just triggers 3D touch action and I don't see a way to differentiate it in `UITouch` instance.
- Hover states do not work well, as the mouse cursor does not seem to raise any events until it is actually clicked - so "pointer moved" is not executed.

The docs are seriously lacking currently. Hopefully, they will add proper documentation with the next version of iPadOS and then it will be possible to implement this better.

**Comment by dr1rrb** [comment]
> 
> 
>  
> @dr1rrb Alright, I checked it :-D .
> 
>     * Right-click is "somehow" supported, but currently, it just triggers 3D touch action and I don't see a way to differentiate it in `UITouch` instance.
> 
>     * Hover states do not work well, as the mouse cursor does not seem to raise any events until it is actually clicked - so "pointer moved" is not executed.
> 
> 
> The docs are seriously lacking currently. Hopefully, they will add proper documentation with the next version of iPadOS and then it will be possible to implement this better.
> 
>

Yeah I'm expecting that future versions of ~~iOS~~ iPadOS are going to significantly improve mouse support, it's probably better to wait for it. Thanks for validating!

**Pull request merged**
