### PR TITLE
fix: Skia.GTK PersonPicture image stretch UniformToFill from tiled None

### LINKED ISSUE #7815: [Gallery][Skia.GTK] `PersonPicture` - Uno image is missing in circle
### Current behavior

personpicture

### Expected behavior

personpicture correct

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK.
2. Click on “PersonPicture” from the "Component" list.
3. Observe that Uno image is missing in circle.

### Workaround

_No response_

### Works on UWP/WinUI

_No response_

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by silviuo**
GitHub Issue (If applicable): closes #7815 

## PR Type

What kind of change does this PR introduce?

## What is the new behavior?

image

### <samp>🤖 Generated by Copilot at 6516a5a</samp>

Fix photo display issues in `PersonPicture` control by using conditional XAML for `ImageBrush`.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
@silviuo I'd rather see what does not work in stretching for `Image`. Are you able to extract a test specifically for that scenario, but outside of PersonPicture`?

**Comment by silviuo** [comment]
@jeromelaban 
Here is a sample app from a default blank template:
[SampleImageFill.zip](https://github.com/unoplatform/uno/files/12455321/SampleImageFill.zip)

The issue applies to the ImageBrush Fill Stretch property on all shapes, it's not PersonPicture specific. It's the fact that PersonPicture is using an Ellipse. 

This is what it looks like in Skia
image

This is the correct Win version for comparison
image

Please let me know what more tests could help give you a better idea of the possible root cause or what I should be investigating next. Thank you!

**Comment by jeromelaban** [comment]
> Please let me know what more tests could help give you a better idea of the possible root cause or what I should be investigating next. Thank you!

Thanks. Changing this style will also impact Wasm. Could you take a look at that target as well?

**Comment by silviuo** [comment]
> > Please let me know what more tests could help give you a better idea of the possible root cause or what I should be investigating next. Thank you!
> 
> Thanks. Changing this style will also impact Wasm. Could you take a look at that target as well?

In the attached sample app, Wasm looks the same as Windows. In the screenshots of the original description, you can see Wasm is not affected by the changes. This was the code used to test:
image

**Comment by silviuo** [comment]
[SampleImageFill.zip](https://github.com/unoplatform/uno/files/12578823/SampleImageFill.zip)

Here is an updated sample app showing that the issue applies to all Stretch enum values, not just UniformToFill:

image

**Comment by silviuo** [comment]
I also wanted to mention that the code lines under comments "ImageBrush is not stretching properly https://github.com/unoplatform/uno/issues/4951" in `src/Uno.UI/Microsoft/UI/Xaml/Controls/PersonPicture/PersonPicture.xaml` is no longer needed for wasm. I removed the code, tested and wasm works fine without the workaround needed for #4951. The workaround right now is only useful to partially solve skia, as you can see in the description of this PR. Partially, because it's not applied to PersonPicture BadgeImageSource.

**Comment by Youssef1313** [comment]
I'm working currently on fixing the image brush stretch on skia.

**Comment by Youssef1313** [comment]
@silviuo Should we close this PR as the underlying Skia bug is now fixed?

**Pull request closed without merging**
