### PR TITLE
fix(FileSavePicker.wasm): FileSavePicker dialog now shows all file type extensions.

### LINKED ISSUE #5685: FileSavePicker FileTypeChoices incorrect
## Current behavior

I have this code:

```
            var savePicker = new Windows.Storage.Pickers.FileSavePicker();
            savePicker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.DocumentsLibrary;
            savePicker.FileTypeChoices.Add("C/C++ source files", new List<string>() { ".cpp", ".c", ".cc", ".cxx", ".c++", ".cp" });
            savePicker.SuggestedFileName = "Hacked";
            Windows.Storage.StorageFile file = await savePicker.PickSaveFileAsync();
```

However, instead of showing these file types, they show `.cp`, `.com`, `.exe`, `.bin`.

image

## Expected behavior

It shows the right file types, like in the my UWP-only project:

image

## How to reproduce it (as minimally and precisely as possible)
- Create a Uno project.
- Open a `FileSavePicker`, like in the code above.
- Build the WASM project.

## Workaround
Found none.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

`FileOpenPicker` seems to work well. Only FileSavePicker fails.

### PR DESCRIPTION
**Pull request by trungnt2910**
GitHub Issue (If applicable): fixes #5685

## PR Type
- Bugfix

What kind of change does this PR introduce?

## What is the current behavior?

Some file type extensions, added by `FileTypeChoices.Add` are missing.

Code: 
```
picker.FileTypeChoices.Add("C/C++ source files", new List<string>() { ".cpp", ".c", ".cc", ".cxx", ".c++", ".cp" });
```

Result:
Only shows `.cp` extension, and also some other irrelevant `.com`, `.exe`, and `.bin`.
image

## What is the new behavior?

Shows all included extensions, as well as the irrelevant extensions `.com`, `.exe`, and `.bin`.
image

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by trungnt2910** [comment]
I can remove the `.exe`, `.bin`, and `.com` files, by using every file's mime type as `*/*`, but I don't know if it brings in any security problem:
```C#
var acceptItem = new NativeFilePickerAcceptTypeItem() { MimeType = "*/*", Extensions = choice.Value.ToArray() };

acceptType.Accept = new NativeFilePickerAcceptTypeItem[] { acceptItem };
```

Result:

image

**Comment by MartinZikmund** [comment]
@trungnt2910 I would not use `*/*` to avoid this issue, as that would mean the "wildcard" option would always be there. Instead it might be worth considering removing the `application/octet-stream` fallback from `MimeTypeService` and ignore extensions without appropriate mapping to force the user to provide a custom MIME time manually.

**Comment by trungnt2910** [comment]
> force the user to provide a custom MIME time manually

You mean forcing the caller to provide MIME types whenever they use the API? Does this means breaking cross platform behavior?

Or do you mean making the end user of the app choose the types?

**Comment by MartinZikmund** [comment]
@trungnt2910 I meant instead of mapping all "unknown" types to the `octet-steam` in `MimeTypeService`, these types would be ignored. So in case the developer wanted: ".jpg, .xyz, .gif". only ".jpg, .gif" would show up in the dialog. To get the ".xyz", they would have to provide custom mapping to Uno via `WinRTFeatureConfiguration` (which could even be `*/*` as a wildcard)

**Comment by trungnt2910** [comment]
> @trungnt2910 I meant instead of mapping all "unknown" types to the `octet-steam` in `MimeTypeService`, these types would be ignored. So in case the developer wanted: ".jpg, .xyz, .gif". only ".jpg, .gif" would show up in the dialog. To get the ".xyz", they would have to provide custom mapping to Uno via `WinRTFeatureConfiguration` (which could even be `*/*` as a wildcard)

So this **does** force developers to write platform-specific code. It might make quite many people wonder why `.xyz` is shown on their UWP test app but not on their website.

**Comment by MartinZikmund** [comment]
@trungnt2910 The current behavior is the same though, as you get the `.com`, `.exe`, etc. instead of the custom `.xyz` extension. That might be even weirder :-D . The `WinRTFeatureConfiguration` approach is documented as part of the file picker docs, so I wouldn't consider it a big problem. Unfortunately there is no way to make a fully platform-independent solution without these edge cases which require the developer's intervention... The `*/*` as a fallback might be a good workaround though, as that would be just a full wildcard, better than the `.com`, etc..

**Comment by trungnt2910** [comment]
> @trungnt2910 The current behavior is the same though, as you get the `.com`, `.exe`, etc. instead of the custom `.xyz` extension. That might be even weirder :-D . The `WinRTFeatureConfiguration` approach is documented as part of the file picker docs, so I wouldn't consider it a big problem. Unfortunately there is no way to make a fully platform-independent solution without these edge cases which require the developer's intervention... The `*/*` as a fallback might be a good workaround though, as that would be just a full wildcard, better than the `.com`, etc..

Another reason why I thought about `*/*` might be a good solution:

Code:
```C#
picker.FileTypeChoices.Add("HTML file", new List<string>() { ".html" });
```

Result:
image

I only want the user to save as `.html`, but the browser added a ton of other extensions, because I specified `text/html`.
In this case, I had to register the type as `application/my-custom-html`, which somehow breaks the purpose of MIME types (No better than `*.*`, I guess).

**Comment by trungnt2910** [comment]
image

I've already included an image in a comment above.

**Comment by MartinZikmund** [comment]
@trungnt2910 Ah, missed that. Ok, let's use the `*/*` workaround here 👍

**Review by MartinZikmund — APPROVED** [review]

**Review by carldebilly — APPROVED** [review]

**Pull request merged**
