### PR TITLE
Fixed the no date selected issue on Time Picker for IOS

### PR DESCRIPTION
**Pull request by GuillaumeSE**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

- Bugfix

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences
- [x] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

https://nventive.visualstudio.com/Umbrella/_workitems/edit/157504

### CODE REVIEW

**Comment by davidjohnoliver** [comment]
Please edit the PR to include a link to the associated issue.

image

**Comment by jeromelaban** [comment]
This change needs a UI Test (validate with a screenshot on android, even if iOS is not yet available), and changes to the release notes.

**Pull request merged**
