### PR TITLE
feat: Port `ComboBoxAutomationPeer`

### PR DESCRIPTION
**Pull request by morning4coffe-dev**
GitHub Issue (If applicable): part of #14344 

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the new behavior?
Ported the `ComboBoxAutomationPeer` from WinUI.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Comment by jeromelaban** [comment]
@morning4coffe-dev it looks like the app crashes on iOS for some tests: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=108678&view=ms.vss-test-web.build-test-results-tab&runId=2642523&resultId=100038&paneView=debug

**Comment by MartinZikmund** [comment]
The execution issue is most likely related to https://github.com/unoplatform/uno/blob/da44a00bc662070ca2db872514ed8a8ecaa31342/src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt#L985 but I am not exactly sure why yet. Will have to debug on macOS. In the meantime - please adjust the file so that the order of members aligns with the WinUI `.cpp` file, as that will make it easier to maintain future changes

**Comment by morning4coffe-dev** [comment]
@MartinZikmund Sorted. 😉

**Pull request merged**
