### PR TITLE
Adjust the Android UI Tests build

### PR DESCRIPTION
**Pull request by jeromelaban**
## PR Type

What kind of change does this PR introduce?
- Build or CI related changes

## What is the new behavior?

Applied workaround to build Android sample app only, and not the full solution.

This change reduces 20 minutes of build time for the android samples.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Here's a file that contains the original issue, where the nuget restore walks up the directories to find a matching sln file. The build fails because some projects are being restore that are not part of the graph coming from the specifically built project and that the TargetFramework is overriden (to avoid multi-targeted projects to build more than they need).

[build-android-ui-tests-only.zip](https://github.com/unoplatform/uno/files/5730171/build-android-ui-tests-only.zip)

**Comment by clairernovotny** [comment]
@jeromelaban can you please file an issue on nuget/home? That's probably the best place for this one.

**Review by ajpinedam — APPROVED** [review]

**Comment by jeromelaban** [comment]
This change reduces 20 minutes of build time for the android samples.

**Comment by jeromelaban** [comment]
@clairernovotny thanks for the research, I'll open an issue on nuget then, likely with a smaller repro.

**Pull request merged**
