### PR TITLE
Update all MUX control localizations

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

Some localizations are missing or are not latest

## What is the new behavior?

Updated **(except for `TabView` which includes some functional changes, in separate PR)**

No code changed, just resws

image

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by ajpinedam** [comment]
I was like "what's this!!!". Easy peasy!

Thanks Martin.

image

**Review by ajpinedam — APPROVED** [review]
Thanks Martin!

**Review by jeromelaban — APPROVED** [review]

**Comment by Youssef1313** [comment]
Note: https://github.com/unoplatform/uno/pull/6790 would have done this automatically.

**Comment by MartinZikmund** [comment]
@Youssef1313 I remember, but it could also cause issue - e.g. `TabView` has changed in a way where new version of the code is also needed as some strings were removed and new added - so they would not work with the old version of the control. I know that is rare, but can happen. "Luckily" the MUX public repo will mostly be dormant from now on, so further updates will probably not happen...

**Pull request merged**
