### PR TITLE
Correct template version

### PR DESCRIPTION
**Pull request by krdmllr**
## PR Type

- Documentation content changes 

## What is the current behavior?

The template version to install was incorrect and did not contain `unoapp`

## What is the new behavior?

Updated to the latest stable version.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

-

Internal Issue (If applicable):
-

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for the PR!

You'll need to update your commit message to follow Conventional Commits (see the [PR template](https://github.com/unoplatform/uno/blob/master/.github/pull_request_template.md)). While you're at it, changing the version to 2.2.0 instead of the dev bits will also be a good update.

Thanks !

**Comment by jeromelaban** [comment]
Thanks for the updated, though the commit text should be `docs: Update the dotnet new version to 2.2.0`.

Apologies for making you re-do your commits. Conventional Commits are not perfect but for now it's good intermediate solution for managing release notes.

**Comment by krdmllr** [comment]
Closed for #3081

**Pull request closed without merging**
