### PR TITLE
fix: tooltip remains opened when host control is no longer visible

### LINKED ISSUE #6200: ToolTip data binding does not work
## Current behavior

When `ToolTip` is data-bound, it does not update when property changes:

```
<Button ToolTipService.ToolTip="{x:Bind Test.Text, Mode=OneWay}" />
```

## Expected behavior

Should work as in UWP.

## How to reproduce it (as minimally and precisely as possible)

See above.

## Workaround

It works when expanded:

```
<Button>
    <ToolTipService.ToolTip>
        <ToolTip Content="{x:Bind Test.Text, Mode=OneWay}" />
    </ToolTipService.ToolTip>
</Button>
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

### PR DESCRIPTION
**Pull request by Xiaoy312**
GitHub Issue (If applicable): #internal, fixes #6200

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?
Tooltip remains opened when the host control is no longer visible

## What is the new behavior?
Tooltip should be closed in that case.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
Internal Issue (If applicable): see cross-linked issue.

### CODE REVIEW

**Review by jeromelaban — COMMENTED** [review]
I think we can add a UI test for this ? It looks like the same one that @MartinZikmund was working on.

**Comment by MartinZikmund** [comment]
This is a separate issue, my PR handles loading/unloading + Content changes, but not visibility changes. Both can be merged, but there will be conflicts, as now the event handlers are no longer instance, but static.

**Comment by MartinZikmund** [comment]
This is the PR with my changes - #6296

**Comment by Xiaoy312** [comment]
@MartinZikmund I actually have another implementation of `TooltipService`, that handles the binding issue #6050, and possibly your #6200 too. And, in addition, it also handles the edge case like when the tooltip is `string.Empty` (it should not appear at all).

MAybe we can discuss to merge all 3 together?

**Comment by Xiaoy312** [comment]
update: ui test added & automated

**Comment by MartinZikmund** [comment]
> @MartinZikmund I actually have another implementation of `TooltipService`, that handles the binding issue #6050, and possibly your #6200 too. And, in addition, it also handles the edge case like when the tooltip is `string.Empty` (it should not appear at all).
> 
> MAybe we can discuss to merge all 3 together?
> 
> edit: forgot the code

As your code handles more scenarios, maybe use it as the basis and just cherry-pick what is useful from mine. I think it could be nice to have the internal attached property which stores the `ToolTip` instance (in my code `ToolTipObject` property) as that is similar to what WinUI uses and can avoid the "instance"-based event handlers and is then enough to use `static` ones, which can easily be unsubscribed.

**Comment by Xiaoy312** [comment]
todo: test

**Review by jeromelaban — APPROVED** [review]
Can you add a control validation that uses the tooltip service (particularly one that goes through the Loaded subscription added by this PR) to ensure that there's no leak ?

See this:https://github.com/unoplatform/uno/blob/d57d8ed572184968a801dda815ac30bba96122cc/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs#L39-L68

**Review by MartinZikmund — APPROVED** [review]

**Pull request merged**
