### PR TITLE
perf: Enable LINQ-related performance analyzers

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): Part of #6882

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by spouliot — APPROVED** [review]
❤️ it

**Review by jeromelaban — APPROVED** [review]
Very nice :) I'm still surprised there weren't more occurrences than that.

**Comment by jeromelaban** [comment]
Build errors:
```
C:\a\1\s\src\Uno.UI.Tests\Windows_Data_Xml\DomTests\Given_XmlDocument.cs(36,39): error CS1503: Argument 1: cannot convert from 'uint' to 'int' [C:\a\1\s\src\Uno.UI.Tests\Uno.UI.Tests.csproj]
C:\a\1\s\src\Uno.UI.Tests\Windows_Globalization\Given_CalendarFormatter.cs(24,23): error CA1826: Do not use Enumerable methods on indexable collections. Instead use the collection directly. [C:\a\1\s\src\Uno.UI.Tests\Uno.UI.Tests.csproj]
```

**Comment by Youssef1313** [comment]
> I'm still surprised there weren't more occurrences than that.

There should be more. Converting to a draft until I finish everything.

**Comment by Youssef1313** [comment]
@jeromelaban This is ready for another look.

**Comment by Youssef1313** [comment]
> I'm still surprised there weren't more occurrences than that.

The remaining occurrences weren't too much. I think the reason is that the analyzers look only for `IReadOnlyList<T>`, so they don't really catch every LINQ usage that can be eliminated.

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
@Youssef1313 [this error](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=53921&view=logs&j=d98e504e-8588-55b3-b746-2633e1f2cf9f&t=7fa2a37e-c421-5cfa-f653-e608391f00ed&l=107) happens often, would you know if it is related to this PR?

**Comment by Youssef1313** [comment]
@jeromelaban Did you intend to comment on https://github.com/unoplatform/uno/pull/9692?
I guess it's related, but I don't know why it happens.

https://github.com/unoplatform/uno/pull/9758 is a trial to see if this gets fixed.

**Pull request merged**
