### PR TITLE
feat: MapStyle and MapInputEventArgs

### PR DESCRIPTION
**Pull request by pkar70**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
not implemented.

## What is the new behavior?
implemented.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
 Only for less UNO0001 warnings in my apps :)

Internal Issue (If applicable):

### CODE REVIEW

**Review by MartinZikmund — APPROVED** [review]

**Comment by MartinZikmund** [comment]
There are some errors in build, probably `using` statements missing 👍

**Comment by pkar70** [comment]
Yes, "using" or explicit types :)
I have problems on my desktop; switching branches in Vstudio can take 5 minutes or more (with Android solution filter); so sometimes I simply open Uno folder not as VStudio solution (switching branches takes seconds).

**Comment by pkar70** [comment]
can this build be restarted?

**Comment by MartinZikmund** [comment]
@pkar70 Sometimes it is faster to close the solution, then switch branches, and then reopen

**Comment by pkar70** [comment]
Seems like CI errors are from UI test, completely not related to this PR. Can build be restarted again?

**Comment by pkar70** [comment]
How this PR can interfere, and led to "Failed to restore D:\a\1\s\UnoAppWinUI\UnoAppWinUI.Wasm\UnoAppWinUI.Wasm.csproj" error in CI build?

**Pull request merged**
