### PR TITLE
chore: enable When_RepeatForever_ShouldLoop and When_Render_Then_CanRenderOnCanvas on skia

### PR DESCRIPTION
**Pull request by ramezgerges**
These tests already work locally, but they had problem during CI. Let's see if they're still flaky

### CODE REVIEW

**Comment by ramezgerges** [comment]
When_Render_Then_CalendarOnCanvas is failing in CI very similarly to the way it fails on android (not CI). The fix for android is being fixed in https://github.com/unoplatform/uno/pull/13070, so perhaps it's a similar problem @Youssef1313.

**Comment by Youssef1313** [comment]
@ramezgerges The fix for `When_Render_Then_CanRenderOnCanvas` is now merged to master and the test is unskipped. Can you rebase on latest master?

**Comment by jeromelaban** [comment]
Let's retry one more to validate some more :)

**Review by jeromelaban — APPROVED** [review]
Looking good!

**Pull request merged**
