### PR TITLE
Added CornerRadius support to more default styles to match UWP

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): #2710 

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

Noticed some other control styles were missing `CornerRadius` handling, too.

## What is the new behavior?

The following controls now respect `CornerRadius`:

- `Button`
- `ToggleButton`
- `HyperlinkButton`
- `RadioButton`
- `ScrollViewer`
- `ListView`
- `GridView`
- `ListViewHeaderItem`
- `GridViewHeaderItem`
- `ListViewItem`
- `GridViewItem`
- `ProgressBar`
- `ProgressRing`
- `ToggleSwitch`
- `FlipViewItem`
- `Frame`
- `ComboBoxItem`
- `TextBox`
- `PasswordBox`

`ComboBox` support was added in #2711 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Comment by MartinZikmund** [comment]
Seems I accidentally also did Format Document on the `Generic.xaml` should I reset and redo the `CornerRadius` changes, or is it ok?

**Comment by jeromelaban** [comment]
In Generic.xaml it's best if you do. It'll be easier to track modifications when we'll migrate to a later version of WinUI

**Comment by MartinZikmund** [comment]
> In Generic.xaml it's best if you do. It'll be easier to track modifications when we'll migrate to a later version of WinUI

Done :-)

**Comment by MartinZikmund** [comment]
> Update release notes

Fixed, I force push'd them away 😀

**Comment by danielkornev** [comment]
A question:

image

This is how WASM renders TextBox with Corner Radius. Why is there black thing behind the area that's cut by the corners? 

and when user clicks on it it becomes white:

image

I suspect cornerradius isn't correctly cutting the corners as it is expected?

**Comment by MartinZikmund** [comment]
Yes, that seems wrong, can you please create an issue (bug) for this?

**Comment by jeromelaban** [comment]
Looks like something @carldebilly may be interested in :)

**Comment by danielkornev** [comment]
sure thing
https://github.com/unoplatform/uno/issues/3110

**Pull request merged**
