### PR TITLE
chore: Update Expander and ColorPicker to latest WinUI

### LINKED ISSUE #6345: Update `Expander` to latest code
## What would you like to be added:

Update `Expander` to latest WinUI code

## Why is this needed:

Alignment

## For which Platform:

All

### PR DESCRIPTION
**Pull request by robloo**
GitHub Issue (If applicable): Closes #6345

## PR Type

What kind of change does this PR introduce?

- Bugfix
- Feature

**WARNING : The ColorPicker is not updated to the latest 2.6 styles. It's currently not known how Uno will integrate both styles together. These files will need to be added in a later commit.**

The Expander is updated to the latest styles as it was only released for v2.6 and has only one set of styles.

## What is the new behavior?

Ports latest fixes for the ColorPicker and updates all Expander code to match WinUI.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] ~Docs have been added/updated which fit [documentation template]~(https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [ ] ~Associated with an issue (GitHub or internal) and uses the [automatic close keywords]~(https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

 - Expander includes the complete and latest style updates. This means it already fits in with the 2.6 styles. While this may be out of place with the other controls it's necessary right now as Expander only has one set of styles and is so far unreleased.
 - ColorPicker does not include any of the 2.6 style updates (only the arrow key inversion bug fix was included here). It is assumed all 2.6 styles will be updated at once in the future.

Internal Issue (If applicable):

### CODE REVIEW

**Review by davidjohnoliver — APPROVED** [review]

**Comment by MartinZikmund** [comment]
@robloo what is missing for this PR? Would like to merge it soon, as we prepare the WinUI 2.6 styles and the new style is not compatible with the old template 😀

**Comment by robloo** [comment]
I'll be sure to have this finished within the next few days assuming the build issues are fixed. That was the biggest issue where due to VS issues the project simply would fail to build after the first time. It wasnt worth the time to find a work around.

Otherwise, XAML needs some things re-disabled. I also need to test the code (like clipping). Finally, I'll see if there have been any more changes upstream.

**Comment by robloo** [comment]
@MartinZikmund I completed this PR. However, I still can't test it. Most projects don't build for me and I'm still not sure why (some do build so it's no longer the original VS issues I was having) The Android 11 emulator just gives a black screen as well. This is not something I'll spend more time on so will rely on the CI tests.

**Comment by MartinZikmund** [comment]
@robloo awesome, thanks! I am approving the PR in the meantime so it can get merged after the build succeeds

**Review by MartinZikmund — APPROVED** [review]

**Pull request merged**
