### PR TITLE
ci: Avoid restoring the whole solution unnecessarily when running sync generator

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

### <samp>🤖 Generated by Copilot at 3d05cb8</samp>

Simplify nuget restore task for sync generator. Use solution filters that only include `Uno.UI` and its dependencies to speed up and stabilize the API synchronization with UWP.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Restoring the whole solution is needed for Roslyn to function properly and generate the synced APIs.

**Comment by jeromelaban** [comment]
@ramezgerges The restore list is already trimmed down, we could probably trim it down further, but I don't think it will yield important results.

**Comment by Youssef1313** [comment]
> The restore list is already trimmed down, we could probably trim it down further, but I don't think it will yield important results.

Restore is taking about 1 minute 15 seconds, and is expected to shrink to ~40 seconds. The save here is half a minute and indeed probably might not be worth it.

Let's see if it gets green or near green with the last change. If not, I'll close as it won't be worth the time.

**Comment by Youssef1313** [comment]
The conversion job is green. So hopefully everything else should get green as well.

**Comment by jeromelaban** [comment]
It seems to reduce the restore time, let's merge :)

**Pull request merged**
