### PR TITLE
feat: OpenStreamForReadAsync without token

### PR DESCRIPTION
**Pull request by pkar70**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
There is method `OpenStreamForReadAsync(CancellationToken ct)`, but no method `OpenStreamForReadAsync()` .

## What is the new behavior?

Method `OpenStreamForReadAsync()` is implemented.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information
I hope I would not be required to create test for this method.

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for your PR! 

This is unfortunately not a valid change, as the method does not exist on the `StorageFile` type, and the original one that takes a token should not have been there either (I'll reference it in #2240 so we can remove it).

Note that this method already exists here as an extension:
https://github.com/unoplatform/uno/blob/6927750e398683a01db98d97061ff0413467c1ed/src/Uno.UWP/System.IO/WindowsRuntimeStorageExtensions.cs#L10

**Comment by pkar70** [comment]
If this method exist, why Visual Studio underline OpenStreamForReadAsync with info that method is not implemented in Uno?

**Comment by jeromelaban** [comment]
You added a new method, not a not-implemented method. 

The one you're seeing is probably another method. If you go the definition of that not-implemented method you're seeing, where does it lead you to ?

**Comment by pkar70** [comment]
When I use not my Uno compilation but 2.2.0-dev380, Visual Studio wants cancelationtoken parameter:
image
it leads to:
image

**Comment by jeromelaban** [comment]
Yes, that's what I meant in my original comment. The method you're adding does not exist in the API, if you want to use that method without a `CancellationToken`, you need to add a using to use this method:

https://github.com/unoplatform/uno/blob/6927750e398683a01db98d97061ff0413467c1ed/src/Uno.UWP/System.IO/WindowsRuntimeStorageExtensions.cs#L10

**Comment by pkar70** [comment]
But I want my app code build in standard UWP, and in Android. Without changing code.
I don't care how method is implemented, as extension to IStorageFile, or inside StorageFile. I just want to use this method.
I don't know why 'your method' is not visible by Visual Studio, and why it want me to add cancellation token parameter.

**Comment by jeromelaban** [comment]
I understand that you want to use a method that has this signature, yet the change you're proposing is not the one that will fix this. The method is located somewhere else.

Can you provide a repro case that works on UWP, and that demonstrates the issue in Uno ?

**Comment by jeromelaban** [comment]
Can you create a sample that I can validate ? A screenshot is not enough.

**Comment by pkar70** [comment]
I got it.
When I add `using System.IO;`, OpenStreamForReadAsync() is not underlined. 
And when I removed `OpenStreamForReadAsync(CancellationToken ct)` from StorageFile.cs , Visual Studio doesnt complain about missing CancellationToken, and suggest adding `using System.IO;`.

**Pull request closed without merging**
