### PR TITLE
docs: Fix the document of Animation output log filter.

### PR DESCRIPTION
**Pull request by lindexi**
## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

We can not find any animation log after `builder.AddFilter("Windows.UI.Xaml.Media.Animation", LogLevel.Debug);`

## What is the new behavior?

We can find the animation log after `builder.AddFilter("Microsoft.UI.Xaml.Media.Animation", LogLevel.Debug);`

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

I test the code in my demo project, and I can find the log message of animation in console.

```csharp
            builder.AddFilter("Windows.UI.Xaml.Media.Animation", LogLevel.Debug);
            builder.AddFilter("Microsoft.UI.Xaml.Media.Animation", LogLevel.Debug);
```

See my demo code: https://github.com/lindexi/lindexi_gd/blob/72617d0df7ae8e54548ce217dd50d5bfa5054133/UnoDemo/WernujarlerhelkayFebairleewel/WernujarlerhelkayFebairleewel/App.xaml.cs#L101-L102

### CODE REVIEW

**Comment by lindexi** [comment]
@jeromelaban Can I ask any update here?

**Review by MartinZikmund — APPROVED** [review]

**Comment by MartinZikmund** [comment]
We can later probably just drop the WUX namespace mention from the doc, but for now it is fine 👍

**Comment by lindexi** [comment]
Thank you @MartinZikmund

**Comment by morning4coffe-dev** [comment]
https://github.com/Mergifyio backport release/stable/5.3

**Pull request merged**
