### PR TITLE
fix(droid): flyout having no size in certain case

### PR DESCRIPTION
**Pull request by Xiaoy312**
GitHub Issue (If applicable): closes unoplatform/uno.toolkit.ui#869

## PR Type
What kind of change does this PR introduce?
- Bugfix

### <samp>🤖 Generated by Copilot at fa26fb3</samp>

Added a new `Subtract` extension method to `LayoutHelper` to simplify size calculations. Refactored `PopupPanel.CalculatePopupPlacement` to use the new method and improve code readability.

## PR Checklist
Please check if your PR fulfills the following requirements:
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by Xiaoy312** [comment]
reserving top comment

**Review by MartinZikmund — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]
🚀

**Comment by jeromelaban** [comment]
@margifyio backport release/stable/5.0

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.0

**Pull request merged**
