### PR TITLE
Alter Android ResourcesGenerationTask to use `LibraryResourceDirectories`

### LINKED ISSUE #10686: Android build often fails on APT-related issues
### Current behavior

When building `net7.0-android`, APT often fails:
```
12>Building target framework: net7.0-android
12>Resources\values\resources_resw-strings.xml : error APT2126: file not found.
12>Done building project "Uno.UI.RuntimeTests.netcoremobile.csproj" -- FAILED.
```

So far I see this most commonly with `Resources.resw` and `Transitive-ingredient01.png` in the `Uno.UI.RuntimeTests` project.

### Expected behavior

Should not fail build.

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

Clean and rebuild the project.

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

Android

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by dellis1972**
GitHub Issue (If applicable): closes #10686

## PR Type

What kind of change does this PR introduce?
- Bugfix

### <samp>🤖 Generated by Copilot at 050dde8</samp>

This pull request enhances the Uno platform's resource generation for Android libraries by introducing new properties and items, and updating the `ResourcesGenerationTask_v0` task. It also improves the compatibility with the Xamarin.Android SDK's `LibraryResourceDirectories` feature.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by dellis1972** [comment]
> Many thanks @dellis1972! This is a very interesting change! Could you rewrite you commit so it starts with `fix: `? It will allow the CI to validate the change further.

Already done. I'm still working on this (hence the draft) but it works for Maui, so it should work for your case also.

**Comment by dellis1972** [comment]
I think this is ready.

**Review by Youssef1313 — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]
Very nice @dellis1972! Thanks a lot for contributing this, I tested it on larger apps and I could not repro!

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.0

**Comment by dellis1972** [comment]
> Very nice @dellis1972! Thanks a lot for contributing this, I tested it on larger apps and I could not repro! We'll keep in mind the `LibraryResourceDirectories` item for additional resources if any.

The main issue was the fact the resources being generated were not in the `obj\<config>\res` folder. That was causing some issues. If you are generating things in a `obj` subfolder of your own its best to use `LibraryResourceDirectories`.

**Pull request merged**
