### PR TITLE
fix: ContentDialog bugfixes

### LINKED ISSUE #5702: ContentDialog.ShowAsync() fails with Failed to raise 'PointerReleasedEvent': System.InvalidOperationException
## Current behavior

Code: 
```C#
var dialog = new SomethingThatInheritsFromContentDialog();
await dialog.ShowAsync();
```

When the dialog calls `Hide()`, the function throws an exception:
```
fail: Windows.UI.Xaml.UIElement[0]
dotnet.js:1       Failed to raise 'PointerReleasedEvent': System.InvalidOperationException
dotnet.js:1         at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) [0x00009] in /__w/1/s/mono/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/TaskCompletionSource.cs:298 
dotnet.js:1         at Windows.UI.Xaml.Controls.ContentDialog+<>c__DisplayClass21_0.<Hide>g__Complete|0 (Windows.UI.Xaml.Controls.ContentDialogClosingEventArgs args) [0x00069] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ContentDialog\ContentDialog.cs:129 
dotnet.js:1         at Windows.UI.Xaml.Controls.ContentDialog.Hide (Windows.UI.Xaml.Controls.ContentDialogResult result) [0x00047] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ContentDialog\ContentDialog.cs:138 
dotnet.js:1         at Windows.UI.Xaml.Controls.ContentDialog.<ProcessPrimaryButton>g__Complete|52_0 (Windows.UI.Xaml.Controls.ContentDialogButtonClickEventArgs a) [0x00019] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ContentDialog\ContentDialog.cs:353 
dotnet.js:1         at Windows.UI.Xaml.Controls.ContentDialog.ProcessPrimaryButton () [0x0002d] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ContentDialog\ContentDialog.cs:365 
dotnet.js:1         at Windows.UI.Xaml.Controls.ContentDialog.OnPrimaryButtonClicked (System.Object sender, Windows.UI.Xaml.RoutedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ContentDialog\ContentDialog.cs:291 
dotnet.js:1         at (wrapper delegate-invoke) <Module>.invoke_void_object_RoutedEventArgs(object,Windows.UI.Xaml.RoutedEventArgs)
dotnet.js:1         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.OnClick (Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.cs:304 
dotnet.js:1         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.RaiseClick (Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.cs:294 
dotnet.js:1         at Windows.UI.Xaml.Controls.Primitives.ButtonBase.OnPointerReleased (Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x00065] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\ButtonBase\ButtonBase.cs:266 
dotnet.js:1         at Windows.UI.Xaml.Controls.Control+<>c.<.cctor>b__348_11 (System.Object sender, Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:867 
dotnet.js:1         at Windows.UI.Xaml.UIElement.InvokeHandler (System.Object handler, Windows.UI.Xaml.RoutedEventArgs args) [0x000e7] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:826 
dotnet.js:1         at Windows.UI.Xaml.UIElement.RaiseEvent (Windows.UI.Xaml.RoutedEvent routedEvent, Windows.UI.Xaml.RoutedEventArgs args, Windows.UI.Xaml.UIElement+BubblingContext ctx) [0x0007f] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:613 
dotnet.js:1         at Windows.UI.Xaml.UIElement.RaisePointerEvent (Windows.UI.Xaml.RoutedEvent evt, Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x0000d] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Pointers.cs:933 
```

## Expected behavior

After the dialog is closed, the function should return normally.

## How to reproduce it (as minimally and precisely as possible)

1. Create a Uno Platform project
2. Create a `ContentDialog`
3. Call the above code.
4. Compile for WASM.

## Workaround

If you only `await` ContentDialog.ShowAsync() once, ignore the exception.
If you call any other `async` function, after calling `ContentDialog.ShowAsync()`, it will fail, so:
Call any random `async` function before calling your real function:

```C#
private async Task SleepAsync()
{
    await Task.Run(() =>
    {
        System.Diagnostics.Debug.WriteLine("Sing me to sleep...");
        System.Threading.Thread.Sleep(1000);
        System.Diagnostics.Debug.WriteLine("I'm wide awake.");
    });
}
private async void Button_Clicked(object sender, RoutedEventArgs args)
{
        await dialog.ShowAsync();
        await SleepAsync();
        await DoImportantWorkAsync();
}
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Latest

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [x] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Xamarin Forms renderer for WASM also seems to be affected. Issue description [here](https://stackoverflow.com/questions/66746614/displaypromptasync-hangs-on-uno-platform-for-xamarin-forms-wasm).

### PR DESCRIPTION
**Pull request by trungnt2910**
GitHub Issue (If applicable): fixes #5702

## PR Type

What kind of change does this PR introduce?

- Bugfix

### Dialog Closing:
```C#
        private async void Dialog_Closing(object sender, ContentDialogClosingEventArgs args)
        {
            var deferral = args.GetDeferral();
            await Task.Delay(5000);
            System.Diagnostics.Debug.WriteLine("Done handling event.");
            deferral.Complete();
        }

        private async void Button_Tapped(object sender, TappedRoutedEventArgs args)
        {
            var dialog = new SampleContentDialog();
            dialog.Closing += Dialog_Closing;
            await dialog.ShowAsync();
            System.Diagnostics.Debug.WriteLine("Dialog returned.");
        }
        
        private async void Button1_Tapped(object sender, TappedRoutedEventArgs args)
        {
            var dialog = new SampleContentDialog();
            await dialog.ShowAsync();
            System.Diagnostics.Debug.WriteLine("Dialog returned.");
        }
```

`Button_Tapped` output:
> Dialog returned.

5 seconds later:

> Done handling event.
> An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll
> An attempt was made to transition a task to a final state when it had already completed.

`Button1_Tapped`: throws `System.InvalidOperationException`.

### Buttons:
- Tap a button on the `ContentDialog` to make the dialog close.
- Tap another button, before the dialog closes.
- The `Closing` event is triggered twice, before the first event completes.

### Dialog Closing

`Button_Tapped` output:
> Done handling event.
> Dialog returned.

Quits quietly without an exception.

`Button1_Tapped`: Quits quietly without an exception.

### Buttons:
When the dialog is hiding, all button clicks and calls to `Hide()` are ignored. This is consistent with UWP.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by davidjohnoliver — COMMENTED** [review]
After checking the issue and investigation notes from @dr1rrb , seems like this could be addressed in a simpler way by just calling `Task.TrySetResult()` instead of `SetResult()`, instead of adding a flag and associated logic? 

Would that make sense or am I missing something?

**Comment by trungnt2910** [comment]
I've thought about that, but decided to do this, because:
The `SetResult` in the button handlers are unnecessary and sometimes undesirable.
In all cases where `Hide(result)` returns `true`, `_tcs.SetResult(result)` is called by `Hide(result)`. The duplicate call in the button handlers does nothing.
The only exception is the one I described in the pull request: You handle the `Closing` event with a deferral. This time, the function from the button handler is called first, causing `ShowAsync()` to return, **before** the dialog actually closes. Then, 5 seconds later, [this line](https://github.com/unoplatform/uno/blob/3b076aedf2d74f4c1317a0775ef6c2c027081912/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs#L129) raises an exception (fatal on WPF).
In this case, `_tcs.SetResult(result)` causes undesirable behavior: `ShowAsync()` returned **before** the dialog actually closes!

**Comment by trungnt2910** [comment]
> instead of adding a flag and associated logic?

The flag and associated logic is added as a fix to another issue that I came across while fixing the first. (The first commit looks quite simple, [here](https://github.com/unoplatform/uno/pull/5816/commits/890e912f0cd8697218b415d62bbd1142437b7518).
On UWP, while a `ContentDialog` is hiding, it does not respond to any button clicks or calls to `Hide()` from other threads.
On Uno, however, the buttons and calls are still handled, leading to unexpected behavior.

**Comment by davidjohnoliver** [comment]
> > instead of adding a flag and associated logic?
> 
> The flag and associated logic is added as a fix to another issue that I came across while fixing the first. (The first commit looks quite simple, [here](https://github.com/unoplatform/uno/pull/5816/commits/890e912f0cd8697218b415d62bbd1142437b7518).
> On UWP, while a `ContentDialog` is hiding, it does not respond to any button clicks or calls to `Hide()` from other threads.
> On Uno, however, the buttons and calls are still handled, leading to unexpected behavior.

I see, that makes sense.

For changes like this with subtle implications, we normally want to have a unit test to guard against regressions in the future. Could you try to author a test that repros the bug you described? A test in `Uno.UI.RuntimeTests` would be most appropriate, like the one below. There's documentation [here](https://platform.uno/docs/articles/uno-development/creating-runtime-tests.html#authoring-tests) on adding RuntimeTests.

https://github.com/unoplatform/uno/blob/5d1620f38827cbd361d7d9fc1822466ac33d0277/src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs#L18-L43

**Review by davidjohnoliver — APPROVED** [review]

**Pull request merged**
