### PR TITLE
fix(Border): [Android] disable Antialias

### PR DESCRIPTION
**Pull request by workgroupengineering**
GitHub Issue (If applicable): closes #

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

Adds antialias pixels in Background Shape and Thickness Shape of Border
## What is the new behavior?

Like UWP, do no adds antialias pixels

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jeromelaban** [comment]
Thanks for the PR. Could you explain the change? Would you have screenshots that show the issue being fixed?

**Review by MartinZikmund — APPROVED** [review]

**Comment by MartinZikmund** [comment]
Wondering whether this could also fix https://github.com/unoplatform/uno/issues/6490

**Review by ajpinedam — APPROVED** [review]

**Comment by jeromelaban** [comment]
Thanks for your contribution!

**Comment by MartinZikmund** [comment]
Confirm this fixed https://github.com/unoplatform/uno/issues/6490 as well, nice!

**Pull request merged**
