### PR TITLE
fix: Update Nav Back Button styles

### LINKED ISSUE #12673: [Gallery][Wasm/Android/iOS]Button(Fluent)-Both 'Back' buttons size are similar but for windows the sizes for Back buttons are different
### Current behavior

button issue

### Expected behavior

back button same size correct

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallery app on Skia.GTK.
Click on “Button” from the "Component" list.
Go to the fluent section.
Go to Back button section.
Notice that both Back buttons size are similar but for windows the sizes for back buttons are different

### Workaround

_No response_

### Works on UWP/WinUI

None

### Environment

_No response_

### NuGet package version(s)

_No response_

### Affected platforms

WebAssembly, Android, iOS

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by lesterbotello**
GitHub Issue (If applicable): closes #12673, #12672

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the current behavior?

Back navigation button styles look differently in Android/WASM/iOS, etc. than their Windows counterpart.

## What is the new behavior?

Back navigation button UI behavior is consistent across platforms.

### <samp>🤖 Generated by Copilot at b776a03</samp>

This pull request updates the styles and resources for the navigation back button in the Uno Platform. It makes the back button use the same colors and font icon as the other button styles in the default theme, and replaces the AnimatedIcon control with a FontIcon in the Fluent Design System themes. This improves the consistency, compatibility, and performance of the back button across different themes and platforms. It also adds some buttons with the modified styles to the Buttons.xaml file in the SamplesApp, to demonstrate their appearance and functionality.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] ~~Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)~~
- [ ] ~~[Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
- [ ] ~~Validated PR `Screenshots Compare Test Run` results.~~
- [X] Contains **NO** breaking changes
- [X] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [X] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

Internal Issue (If applicable):
[](https://github.com/unoplatform/uno/issues/12673)

### CODE REVIEW

**Review by agneszitte — COMMENTED** [review]
Before going further on the review @lesterbotello, if the resources changed, it will need to follow the related WinUI files and precise the latest related commit. @MartinZikmund if you can confirm please.
image

**Comment by lesterbotello** [comment]
> @lesterbotello As @agneszitte mentioned, do the changes come from the WinUI repo? If yes, the commit reference should be updated to match (and potentially should check if something else hasn't changed on their side while at it) https://github.com/microsoft/microsoft-ui-xaml/tree/main/dev/NavigationView

Thanks @MartinZikmund / @agneszitte. Interestingly, copying the styles from the respective WinUI resources results in the referenced bug on all platforms (including Windows) I'm kind of confused because the button's appearance don't seem to match the style names (see the image below for a visual explanation).

Does this mean this is the intended design? Or does it mean this is a bug in WinUI itself?

If the answer is the former, then this PR is probably not necessary after all.

NavigationBackButtonStyles

**Comment by MartinZikmund** [comment]
@lesterbotello so you mean the screenshot above is from Windows 👀 ? If the bug is present there then we probably should remain "aligned" - e.g. have the bug as well, but we should report it to them to understand why the visuals are mixed up and if it is actually intended for some weird reason

**Comment by lesterbotello** [comment]
Closing this pull request as this has been confirmed as a bug in WinUI. An issue has been opened: https://github.com/microsoft/microsoft-ui-xaml/issues/8636

**Pull request closed without merging**
