### PR TITLE
feat: FindFirst/LastFocusableElement

### LINKED ISSUE #2378: MasterDetailsView fails on collapse with FocusManager.FindFirstFocusableElement not implemented
## Current behavior

When the available space becomes less than minimum width, the `MasterDetailsView` hides the **master sidebar**. That's expected. However, in this scenario, a Exception is thrown when this happens.

## How to reproduce it (as minimally and precisely as possible)

1. Clone this repo's specific commit: https://github.com/SuperJMN-Zafiro/UnoDesigner/commit/b5e9dbfba1ede59ec729795b5ed34ac3ae06768c
2. Run **the Android head**.
4. Switch the emulator to portrait mode
3. Click on New document
4. Move the Slider (the gray vertical bar) to the left until the exception is thrown.
> DependencyObject FocusManager.FindFirstFocusableElement(DependencyObject searchScope) is not implemented in Uno.'

## Demo of the issue:

Dr34GxNMGF

## Environment

Package Version(s):
Uno.UI 2.1.0-dev.384

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [X] Resharper (version: 2019.3.1)

### LINKED ISSUE #3092: MasterDetailsView throws exception when item is selected
The UWP toolkit's `MasterDetailsView` does not work properly in Uno Platform due to `FindFirstFocusableElement` not being implemented.

## Current behavior

`NotImplementedException` is thrown when user selects an item in `MasterDetailsView`

## Expected behavior

Should not throw.

## How to reproduce it (as minimally and precisely as possible)

Use `MasterDetailsView` and select an item.

## Environment

Nuget Package: master

Package Version(s): master

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): fixes #2378, fixes #3092 

## PR Type

What kind of change does this PR introduce?

- Feature

## What is the current behavior?

Support for `FocusManager.FindFirstFocusableElement` and `FindLastFocusableElement`

## What is the new behavior?

Methods are implemented on iOS, Android, macOS, and return null on WASM.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

**Comment by MartinZikmund** [comment]
> Looks good, can you add a test please

I have actually found out Uno's codebase considers only TextBox fields as focus able, whereas in UWP it can by any Control (like Button), is that something that should be adjusted or is there a particular reason for it to be this way?

**Comment by davidjohnoliver** [comment]
> > Looks good, can you add a test please
> 
> I have actually found out Uno's codebase considers only TextBox fields as focusable (see the logic in `IsFocusableView`), whereas in UWP it can by any Control (like Button), is that something that should be adjusted or is there a particular reason for it to be this way?

Hmm, it looks like something that should be adjusted, it's probably a reflection of the fact that the primary use case we've had for programmatic focus up until now has been text entry in forms. Perhaps @MatFillion has more insight?

**Comment by MartinZikmund** [comment]
> > > Looks good, can you add a test please
> > 
> > 
> > I have actually found out Uno's codebase considers only TextBox fields as focusable (see the logic in `IsFocusableView`), whereas in UWP it can by any Control (like Button), is that something that should be adjusted or is there a particular reason for it to be this way?
> 
> Hmm, it looks like something that should be adjusted, it's probably a reflection of the fact that the primary use case we've had for programmatic focus up until now has been text entry in forms. Perhaps @MatFillion has more insight?

I have created #3130 to track this inconsistency, can we merge this PR for now with the existing behavior? I need it to use `MasterDetailView` in my app :-) .

**Comment by MatFillion** [comment]
Your assumptions are sound, we probably never needed it before so it wasn't implemented. Does this PR change the behavior for controls or behaviors not using FindFirstFocusableElement or it's scoped to specifically that method? (just to assess the impact on existing applications and potential breaking changes)

@MartinZikmund @davidjohnoliver

**Comment by MartinZikmund** [comment]
> Your assumptions are sound, we probably never needed it before so it wasn't implemented. Does this PR change the behavior for controls or behaviors not using FindFirstFocusableElement or it's scoped to specifically that method? (just to assess the impact on existing applications and potential breaking changes)
> 
> @MartinZikmund @davidjohnoliver

In this PR there is no behavior change, apart from that the `FindFirstFocusableElement` and `FindLastFocusableElement` methods now no longer throw. The existing methods work the same way as previously 👍

**Pull request merged**
