### PR TITLE
docs: new styling

### PR DESCRIPTION
**Pull request by rfabre**
## PR Type

The style for docfx was updated to match Figma changes

## What is the current behavior?

N/A

## What is the new behavior?

N/A

### <samp>🤖 Generated by Copilot at abbb6d7</samp>

This pull request updates the SCSS and JS files for the documentation website templates. The changes improve the styling, layout, and responsiveness of the website elements, such as the navbar, the side affix, the code blocks, and the buttons. The changes also fix some typos, align the breakpoints, and apply the design guidelines. The changes move the breakpoints logic to a separate file and define new color variables for consistency and maintainability.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

## Other information

N/A

Internal Issue (If applicable):
https://dev.azure.com/nventive/UNO%20Marketing/_workitems/edit/280519

### CODE REVIEW

**Review by sasakrsmanovic — APPROVED** [review]
Approving but would love to see this on staging first so I can validate the new styling is true to its design. @jeromelaban

**Review by agneszitte — APPROVED** [review]

**Comment by agneszitte** [comment]
Will sync with @jeromelaban before we decide to merge the changes

**Comment by agneszitte** [comment]
> Will sync with @jeromelaban before we decide to merge the changes

@sasakrsmanovic it was decided with @jeromelaban that we will merge these changes when you will be back.

**Review by ajpinedam — APPROVED** [review]

**Comment by jeromelaban** [comment]
These changes are likely obsolete, if the changes are still needed re-create a PR. @sasakrsmanovic @mtmattei

**Comment by agneszitte** [comment]
It is planned with @alextrepa that he will be able to rebase the changes with the latest so we can test the changes.
(cc @nickrandolph)

**Comment by MartinZikmund** [comment]
It would be very nice to have the new typography merged, it would improve UX tenfold

**Comment by jeromelaban** [comment]
FYI, @alextrepa, there's now an automatic temporary site that is created to validate that the changes are reflected properly.

**Comment by agneszitte** [comment]
@jeromelaban / @nickrandolph 
I am closing this PR as the work was done by @mcereda95 with this PR https://github.com/unoplatform/uno/pull/14618

**Pull request closed without merging**
